/**
 * EL CATÁLOGO DE AGENTES CON CONTRATO.
 *
 * DE DÓNDE SALEN ESTOS ROLES. No están inventados: se derivan de los que ya
 * existen en el árbol. Contando los ficheros de `sectors/`, los roles reales
 * más poblados son Analytics (43 sectores), SEO (29), Social (23), Email (23),
 * Reviews (22), Precios (21), ContentMarketing (10), Ads (10), Retention (7),
 * Clientes (7), LocalSEO (4) y LeadGeneration (4).
 *
 * Lo que faltaba no eran agentes: era que declararan qué necesitan saber, hasta
 * dónde pueden llegar solos y cómo se sabe si su salida vale. Los 1.994
 * ficheros no leen el contexto del cliente — reciben un `brief` armado a mano
 * en la ruta.
 *
 * ESTE FICHERO NO SUSTITUYE A NADIE TODAVÍA. Declara el contrato de cada rol.
 * La migración de los 1.994 hacia estos contratos es la Fase 6, y exige
 * characterization tests antes de tocar un solo fichero.
 *
 * REGLA: cada departamento `operativo` tiene aquí al menos un agente. Uno
 * declarado sin agentes es un organigrama de presentación, y
 * `losDepartamentosNoEstanVacios.test.ts` lo pone en rojo.
 */

import type { ContratoDeAgente } from "./contratoDeAgente";

/** Diez minutos. Un agente que tarda más está atascado, no trabajando. */
const TIMEOUT = 10 * 60_000;

export const CATALOGO: readonly ContratoDeAgente[] = [
  // ══ Estrategia ═══════════════════════════════════════════════════════════
  {
    id: "estratega",
    rol: "Decide qué hacer por este cliente y en qué orden",
    objetivo: "Que cada objetivo del cliente tenga un plan con acciones concretas y medibles",
    responsabilidad: "El plan. Si el plan es malo, es suyo, aunque la ejecución fuera impecable.",
    departamento: "estrategia",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "sector", imprescindible: true },
      { dimension: "presupuestos", imprescindible: false },
      { dimension: "competidores", imprescindible: false },
      { dimension: "historial", imprescindible: false },
    ],
    produce: "plan",
    herramientas: ["memory.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "prometer un resultado concreto en un plazo concreto sin línea base medida",
      "proponer acciones cuyo coste supere el presupuesto declarado por el cliente",
    ],
    escalaSi: [
      "los objetivos del cliente son incompatibles entre sí",
      "el presupuesto declarado no da para ninguna acción con efecto esperable",
    ],
    rubrica: [
      "cada acción del plan apunta a un objetivo declarado del cliente",
      "cada acción dice cómo se sabrá si funcionó",
      "el plan cabe en el presupuesto y en el tiempo declarados",
    ],
    kpis: ["objetivos con plan", "planes revisados tras medir"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Analítica ════════════════════════════════════════════════════════════
  {
    id: "analista",
    rol: "Mide qué ha pasado y a qué se debió",
    objetivo: "Que cada acción tenga un resultado medido y no una impresión",
    responsabilidad: "Los números. No los interpreta a favor de nadie.",
    departamento: "analitica",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "analytics", imprescindible: false },
      { dimension: "crm", imprescindible: false },
      { dimension: "resultados", imprescindible: false },
    ],
    produce: "medicion",
    herramientas: ["analytics.read", "crm.read"],
    consecuencias: ["toca_datos_personales"],
    autonomia: "L3_EJECUTAR_REVERSIBLE",
    nuncaHace: [
      "presentar una correlación como una causa",
      "declarar un ganador de un experimento sin muestra suficiente",
      "rellenar un hueco de datos con una estimación presentada como medida",
    ],
    escalaSi: [
      "no hay línea base contra la que comparar",
      "los datos de dos fuentes se contradicen más de lo explicable por su método",
    ],
    rubrica: [
      "toda cifra dice de qué fuente sale y de qué periodo",
      "lo que no se pudo medir aparece como no medido, no como cero",
    ],
    kpis: ["acciones con resultado atribuido", "objetivos con línea base"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: false,
  },

  // ══ SEO ══════════════════════════════════════════════════════════════════
  {
    id: "seo-estratega",
    rol: "Decide por qué búsquedas hay que pelear y en qué orden",
    objetivo: "Ganar visibilidad en las búsquedas que traen clientes, no las que traen visitas",
    responsabilidad: "La selección de búsquedas y su prioridad.",
    departamento: "seo",
    necesita: [
      { dimension: "sector", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "servicios", imprescindible: true },
      { dimension: "ubicaciones", imprescindible: false },
      { dimension: "competidores", imprescindible: false },
      { dimension: "keywords", imprescindible: false },
    ],
    produce: "prioridad_seo",
    herramientas: ["search.read", "memory.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "proponer palabras clave sin relación con lo que el cliente vende",
      "recomendar prácticas que penalizan: texto oculto, enlaces comprados, contenido duplicado",
    ],
    escalaSi: ["el sector tiene restricciones legales sobre lo que se puede afirmar"],
    rubrica: [
      "cada búsqueda propuesta tiene intención compatible con lo que el cliente vende",
      "la prioridad se justifica con dificultad y volumen, no con corazonadas",
    ],
    kpis: ["visibilidad", "posiciones ganadas", "tráfico orgánico cualificado"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "seo-tecnico",
    rol: "Audita que la web se pueda rastrear, indexar y cargar",
    objetivo: "Quitar los impedimentos técnicos antes de invertir en contenido",
    responsabilidad: "El diagnóstico técnico y su prioridad por impacto.",
    departamento: "seo_tecnico",
    necesita: [{ dimension: "activos", imprescindible: true }],
    produce: "auditoria_tecnica",
    herramientas: ["web.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: ["modificar la web del cliente sin aprobación"],
    escalaSi: ["la web no responde o bloquea el rastreo"],
    rubrica: [
      "cada hallazgo dice qué página afecta y qué se pierde por él",
      "los hallazgos van ordenados por impacto, no por facilidad",
    ],
    kpis: ["errores de rastreo resueltos", "páginas indexadas", "velocidad"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: false,
  },
  {
    id: "seo-local",
    rol: "Trabaja la visibilidad de quien busca cerca y compra hoy",
    objetivo: "Que aparezca en el mapa cuando alguien de su zona busca lo que vende",
    responsabilidad: "La ficha, las citaciones y la coherencia de datos locales.",
    departamento: "seo_local",
    necesita: [
      { dimension: "ubicaciones", imprescindible: true },
      { dimension: "servicios", imprescindible: true },
      { dimension: "empresa", imprescindible: true },
    ],
    produce: "plan_local",
    herramientas: ["search.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: ["inventar una dirección o un horario que el cliente no ha declarado"],
    escalaSi: ["los datos de contacto del cliente son incoherentes entre fuentes"],
    rubrica: ["nombre, dirección y teléfono coinciden en todo lo propuesto"],
    kpis: ["visibilidad en el mapa", "acciones desde la ficha"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: false,
  },

  // ══ Contenido y copy ═════════════════════════════════════════════════════
  {
    id: "copywriter",
    rol: "Escribe lo que el cliente diría si supiera escribirlo",
    objetivo: "Textos que convierten y suenan a la marca, no a plantilla",
    responsabilidad: "Lo que se dice y cómo suena.",
    departamento: "copy",
    necesita: [
      { dimension: "brand_voice", imprescindible: true, confianzaMinima: 0.9 },
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "restricciones", imprescindible: false },
      { dimension: "ofertas", imprescindible: false },
      { dimension: "buyer_personas", imprescindible: false },
    ],
    produce: "copy",
    herramientas: [],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: [
      "afirmar un dato del cliente que no está en su contexto",
      "usar cifras de resultados que nadie ha medido",
      "escribir en un tono distinto del declarado por el cliente",
    ],
    escalaSi: [
      "el sector exige descargos legales que el texto no puede llevar",
      "la propuesta de valor declarada es incompatible con la oferta",
    ],
    rubrica: [
      "no contiene ninguna afirmación que no se pueda sostener",
      "respeta el tratamiento y el tono declarados",
      "un solo mensaje principal por pieza",
    ],
    kpis: ["aprobado a la primera", "conversión de la pieza"],
    timeoutMs: TIMEOUT,
    reintentos: 2,
    exigeIaReal: true,
  },
  {
    id: "content-marketing",
    rol: "Decide sobre qué se publica, cuándo y en qué formato",
    objetivo: "Un calendario que responde a las preguntas que sus clientes se hacen",
    responsabilidad: "El calendario y su coherencia con la estrategia.",
    departamento: "contenido",
    necesita: [
      { dimension: "icp", imprescindible: true },
      { dimension: "sector", imprescindible: true },
      { dimension: "objetivos", imprescindible: true },
      { dimension: "canales", imprescindible: false },
      { dimension: "keywords", imprescindible: false },
    ],
    produce: "calendario",
    herramientas: ["memory.read"],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: ["programar publicaciones sin aprobación cuando el cliente la exige"],
    escalaSi: ["el calendario propuesto excede lo que el cliente puede sostener"],
    rubrica: [
      "cada pieza responde a una pregunta real de su cliente ideal",
      "la frecuencia es sostenible con los recursos declarados",
    ],
    kpis: ["piezas publicadas", "tráfico por pieza"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Marca y creatividad ══════════════════════════════════════════════════
  {
    id: "guardian-de-marca",
    rol: "Comprueba que todo lo que sale suena y se ve como el cliente",
    objetivo: "Coherencia entre piezas, canales y momentos",
    responsabilidad: "Que nada salga con una voz que no es la suya.",
    departamento: "marca",
    necesita: [
      { dimension: "brand_voice", imprescindible: true },
      { dimension: "marca", imprescindible: false },
      { dimension: "restricciones", imprescindible: false },
    ],
    produce: "veredicto_de_marca",
    herramientas: [],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: ["aprobar una pieza que contradice el tono declarado"],
    escalaSi: ["no hay voz de marca declarada y la pieza va a publicarse"],
    rubrica: ["dice qué falla y dónde, no sólo que falla"],
    kpis: ["piezas coherentes con la voz declarada"],
    timeoutMs: TIMEOUT,
    reintentos: 0,
    exigeIaReal: true,
  },
  {
    id: "creativo",
    rol: "Diseña las piezas visuales de una campaña",
    objetivo: "Creatividades que se entienden en dos segundos y se distinguen del resto",
    responsabilidad: "Lo visual: composición, jerarquía, formato por canal.",
    departamento: "creatividad",
    necesita: [
      { dimension: "marca", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "creatividades", imprescindible: false },
    ],
    produce: "diseno",
    herramientas: [],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: ["usar imágenes de las que el cliente no tiene derechos"],
    escalaSi: ["no hay activos de marca y la pieza va a un canal público"],
    rubrica: ["se lee en móvil", "respeta la paleta declarada", "un solo foco por pieza"],
    kpis: ["creatividades producidas", "rendimiento por creatividad"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Medios de pago ═══════════════════════════════════════════════════════
  {
    id: "planificador-de-medios",
    rol: "Decide dónde invertir y cuánto para conseguir el objetivo",
    objetivo: "El menor coste por resultado, no el mayor alcance",
    responsabilidad: "El reparto del presupuesto entre canales y campañas.",
    departamento: "paid_media",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "presupuestos", imprescindible: true, confianzaMinima: 0.9 },
      { dimension: "icp", imprescindible: true },
      { dimension: "audiencias", imprescindible: false },
      { dimension: "resultados", imprescindible: false },
    ],
    produce: "plan_de_medios",
    herramientas: ["ads.read"],
    consecuencias: ["gasta_dinero"],
    autonomia: "L4_EJECUTAR_ACOTADO",
    nuncaHace: [
      "superar el presupuesto autorizado",
      "lanzar una campaña sin la autorización de gasto correspondiente",
      "cambiar pujas fuera del tope por operación declarado",
    ],
    escalaSi: [
      "el presupuesto declarado no llega al mínimo del canal",
      "el coste por resultado sube por encima del objetivo dos periodos seguidos",
    ],
    rubrica: [
      "cada euro propuesto va contra un objetivo declarado",
      "hay una hipótesis de por qué ese canal para ese público",
    ],
    kpis: ["CPA", "ROAS", "presupuesto ejecutado sobre autorizado"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Canales ══════════════════════════════════════════════════════════════
  {
    id: "social-media",
    rol: "Lleva la presencia del cliente en sus redes",
    objetivo: "Conversación y alcance en las redes donde están sus clientes",
    responsabilidad: "Qué se publica en cada red y cómo se responde.",
    departamento: "social",
    necesita: [
      { dimension: "brand_voice", imprescindible: true },
      { dimension: "canales", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "ofertas", imprescindible: false },
    ],
    produce: "plan_social",
    herramientas: ["social.read"],
    consecuencias: ["publica_en_nombre_del_cliente"],
    autonomia: "L5_APROBACION_HUMANA",
    nuncaHace: [
      "publicar sin aprobación cuando el cliente la exige",
      "responder a una crisis de reputación sin escalarla",
      "adaptar una pieza a una red sin respetar sus límites de formato",
    ],
    escalaSi: [
      "hay un comentario negativo con alcance creciente",
      "el tema toca algo sensible del sector",
    ],
    rubrica: ["cada pieza está adaptada a su red, no copiada entre ellas"],
    kpis: ["alcance", "interacción", "tiempo de respuesta a comentarios"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "email-lifecycle",
    rol: "Decide qué se le dice a cada contacto según su momento",
    objetivo: "Que cada correo llegue a quien le sirve y no al resto",
    responsabilidad: "La segmentación y la secuencia.",
    departamento: "email_lifecycle",
    necesita: [
      { dimension: "brand_voice", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "crm", imprescindible: false },
      { dimension: "ofertas", imprescindible: false },
    ],
    produce: "secuencia",
    herramientas: ["crm.read"],
    consecuencias: ["contacta_personas", "toca_datos_personales"],
    autonomia: "L5_APROBACION_HUMANA",
    nuncaHace: [
      "enviar a quien no ha dado su consentimiento",
      "enviar a quien se ha dado de baja",
      "enviar sin enlace de baja visible",
    ],
    escalaSi: ["la tasa de quejas sube por encima del umbral del proveedor"],
    rubrica: [
      "cada correo tiene un solo objetivo",
      "el segmento se justifica con un criterio comprobable",
    ],
    kpis: ["entregabilidad", "apertura", "conversión por secuencia", "bajas"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "reputacion",
    rol: "Vigila y responde lo que se dice del cliente",
    objetivo: "Que las opiniones se respondan y las malas no se enquisten",
    responsabilidad: "El tono y la rapidez de la respuesta pública.",
    departamento: "reputacion",
    necesita: [
      { dimension: "brand_voice", imprescindible: true },
      { dimension: "ubicaciones", imprescindible: false },
    ],
    produce: "respuestas",
    herramientas: ["reviews.read"],
    consecuencias: ["publica_en_nombre_del_cliente"],
    autonomia: "L5_APROBACION_HUMANA",
    nuncaHace: [
      "discutir públicamente con un cliente insatisfecho",
      "responder a una reseña que menciona un caso clínico o legal sin escalar",
    ],
    escalaSi: ["la reseña acusa de algo con consecuencias legales o sanitarias"],
    rubrica: ["la respuesta reconoce el problema antes de explicarlo"],
    kpis: ["valoración media", "reseñas respondidas", "tiempo de respuesta"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Comercial ════════════════════════════════════════════════════════════
  {
    id: "crm-higiene",
    rol: "Mantiene la base de contactos usable",
    objetivo: "Que ningún contacto se pierda, se duplique ni se quede sin dueño",
    responsabilidad: "La calidad del dato de contacto.",
    departamento: "crm",
    necesita: [{ dimension: "crm", imprescindible: false }],
    produce: "informe_crm",
    herramientas: ["crm.read", "crm.write"],
    consecuencias: ["toca_datos_personales"],
    autonomia: "L3_EJECUTAR_REVERSIBLE",
    nuncaHace: [
      "fusionar dos contactos sin dejar rastro de qué se fusionó",
      "borrar un contacto: se archiva",
    ],
    escalaSi: ["dos contactos parecen la misma persona pero difieren en datos clave"],
    rubrica: ["cada cambio deja el estado anterior recuperable"],
    kpis: ["contactos sin dueño", "duplicados", "tiempo hasta el primer contacto"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: false,
  },
  {
    id: "captacion",
    rol: "Genera contactos cualificados",
    objetivo: "Contactos que encajan con el cliente ideal, no volumen",
    responsabilidad: "La calidad de lo que entra en el embudo.",
    departamento: "captacion",
    necesita: [
      { dimension: "icp", imprescindible: true },
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "canales", imprescindible: false },
    ],
    produce: "plan_captacion",
    herramientas: [],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: ["proponer compra de bases de datos de contactos"],
    escalaSi: ["el coste por contacto cualificado supera su valor estimado"],
    rubrica: ["cada fuente propuesta dice qué contactos traerá y por qué encajan"],
    kpis: ["leads", "leads cualificados", "coste por lead cualificado"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "cro",
    rol: "Propone y evalúa experimentos de conversión",
    objetivo: "Que de las visitas que ya hay salgan más clientes",
    responsabilidad: "La hipótesis, el diseño del experimento y su lectura.",
    departamento: "cro",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "analytics", imprescindible: false },
      { dimension: "icp", imprescindible: false },
    ],
    produce: "experimento",
    herramientas: ["analytics.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "declarar un ganador sin muestra suficiente",
      "cambiar el criterio de éxito después de ver los datos",
    ],
    escalaSi: ["el tráfico no da para alcanzar significación en un plazo razonable"],
    rubrica: [
      "la hipótesis dice qué se espera y por qué",
      "el criterio de éxito se fija ANTES de empezar",
    ],
    kpis: ["experimentos concluidos", "mejora de conversión demostrada"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "funnels",
    rol: "Diseña el camino desde el clic hasta la conversión",
    objetivo: "Menos fricción en cada paso, sin perder la información necesaria",
    responsabilidad: "La estructura del embudo y sus pasos.",
    departamento: "funnels",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "ofertas", imprescindible: false },
    ],
    produce: "embudo",
    herramientas: [],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: ["pedir datos que no se van a usar"],
    escalaSi: ["el embudo exige un pago y no hay pasarela conectada"],
    rubrica: ["cada paso justifica su existencia por lo que aporta"],
    kpis: ["conversión del embudo", "abandono por paso"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Producto digital ═════════════════════════════════════════════════════
  {
    id: "web",
    rol: "Construye y mantiene la web del cliente",
    objetivo: "Una web que carga, funciona y se puede cambiar sin romperla",
    responsabilidad: "Que la web esté disponible y sea modificable.",
    departamento: "web",
    necesita: [
      { dimension: "marca", imprescindible: true },
      { dimension: "servicios", imprescindible: true },
      { dimension: "activos", imprescindible: false },
    ],
    produce: "sitio",
    herramientas: ["web.read"],
    consecuencias: ["publica_en_nombre_del_cliente"],
    autonomia: "L5_APROBACION_HUMANA",
    nuncaHace: ["publicar cambios en producción sin aprobación"],
    escalaSi: ["un cambio afecta a la pasarela de pago o al formulario legal"],
    rubrica: ["funciona en móvil", "carga en menos de tres segundos", "sin enlaces rotos"],
    kpis: ["disponibilidad", "velocidad", "incidencias"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "ecommerce",
    rol: "Optimiza el catálogo y el proceso de compra",
    objetivo: "Que quien llega al carrito termine comprando",
    responsabilidad: "Fichas, búsqueda interna y pasos hasta el pago.",
    departamento: "ecommerce",
    necesita: [
      { dimension: "productos", imprescindible: true },
      { dimension: "icp", imprescindible: true },
      { dimension: "brand_voice", imprescindible: false },
    ],
    produce: "optimizacion_catalogo",
    herramientas: ["ecommerce.read"],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: ["cambiar precios", "cambiar el stock declarado"],
    escalaSi: ["el catálogo tiene productos sin precio o sin imagen"],
    rubrica: ["cada ficha responde a las tres dudas que impiden comprar"],
    kpis: ["conversión", "ticket medio", "abandono de carrito"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Control ══════════════════════════════════════════════════════════════
  {
    id: "qa-entregable",
    rol: "Decide si un entregable puede salir",
    objetivo: "Que no salga nada que después haya que retirar",
    responsabilidad: "El veredicto. Es independiente de quien lo produjo.",
    departamento: "qa",
    necesita: [{ dimension: "restricciones", imprescindible: false }],
    produce: "veredicto_qa",
    herramientas: [],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "revisar un entregable que ha producido él mismo",
      "aprobar algo cuya procedencia no es de un modelo real cuando el servicio lo exige",
    ],
    escalaSi: ["el entregable roza una restricción legal del sector"],
    rubrica: ["dice qué falla, dónde y por qué importa"],
    kpis: ["entregables bloqueados", "defectos detectados tras publicar"],
    timeoutMs: TIMEOUT,
    reintentos: 0,
    exigeIaReal: false,
  },
  {
    id: "compliance",
    rol: "Marca los límites de lo que se puede afirmar",
    objetivo: "Que ninguna pieza exponga al cliente a una sanción",
    responsabilidad: "Los descargos obligatorios y las afirmaciones prohibidas.",
    departamento: "compliance",
    necesita: [
      { dimension: "sector", imprescindible: true },
      { dimension: "legal_compliance", imprescindible: false },
      { dimension: "restricciones", imprescindible: false },
    ],
    produce: "veredicto_legal",
    herramientas: [],
    consecuencias: ["tiene_efecto_legal"],
    autonomia: "L5_APROBACION_HUMANA",
    nuncaHace: ["dar por buena una afirmación sanitaria o financiera sin respaldo"],
    escalaSi: ["el sector está regulado y la pieza hace una promesa de resultado"],
    rubrica: ["cita qué norma o criterio aplica, no sólo que aplica"],
    kpis: ["afirmaciones prohibidas detectadas", "entregables con descargo correcto"],
    timeoutMs: TIMEOUT,
    reintentos: 0,
    exigeIaReal: false,
  },
  {
    id: "customer-success",
    rol: "Detecta lo que se está atascando antes de que el cliente lo note",
    objetivo: "Que ningún cliente pase semanas esperando sin que nadie lo sepa",
    responsabilidad: "Que el trabajo que hay pueda avanzar.",
    departamento: "customer_success",
    necesita: [],
    produce: "senales",
    herramientas: ["memory.read", "reports.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "contactar al cliente por su cuenta",
      "proponer una ampliación de servicio sin un hecho que la sostenga",
    ],
    escalaSi: ["una señal bloqueante lleva más de siete días abierta"],
    rubrica: ["cada señal trae la evidencia que la sostiene"],
    kpis: ["días hasta el primer entregable", "señales bloqueantes abiertas"],
    timeoutMs: TIMEOUT,
    reintentos: 0,
    exigeIaReal: false,
  },
  {
    id: "operaciones",
    rol: "Vigila que la cola avance y nada se quede varado",
    objetivo: "Cero trabajos olvidados",
    responsabilidad: "El estado de la cola.",
    departamento: "operaciones",
    necesita: [],
    produce: "estado_de_cola",
    herramientas: [],
    consecuencias: [],
    autonomia: "L3_EJECUTAR_REVERSIBLE",
    nuncaHace: ["reencolar un trabajo en dead_letter sin diagnosticar la causa"],
    escalaSi: ["hay trabajos en dead_letter sin revisar"],
    rubrica: ["cada trabajo varado dice desde cuándo y por qué"],
    kpis: ["trabajos en dead_letter", "tiempo medio en cola"],
    timeoutMs: TIMEOUT,
    reintentos: 0,
    exigeIaReal: false,
  },
  {
    id: "reporting",
    rol: "Cuenta al cliente qué se ha hecho y qué ha producido",
    objetivo: "Que el cliente sepa qué está comprando sin tener que preguntarlo",
    responsabilidad: "La claridad del informe. Los números los toma de analítica.",
    departamento: "reporting",
    necesita: [
      { dimension: "objetivos", imprescindible: true },
      { dimension: "resultados", imprescindible: false },
      { dimension: "preferencias", imprescindible: false },
    ],
    produce: "informe",
    herramientas: ["reports.read"],
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: [
      "retocar una cifra para que se vea mejor",
      "omitir un objetivo que no se ha cumplido",
    ],
    escalaSi: ["no hay datos suficientes para informar del periodo"],
    rubrica: [
      "empieza por lo que el cliente quería conseguir, no por lo que hicimos",
      "lo que no se pudo medir aparece como no medido",
    ],
    kpis: ["informes entregados a tiempo", "informes con resultado medido"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },

  // ══ Ventas ═══════════════════════════════════════════════════════════════
  //
  // Estos dos no trabajan para un cliente: trabajan para que NELVYON tenga
  // clientes. Y son los dos únicos agentes del catálogo cuyo trabajo, si sale
  // mal, molesta a alguien que no ha pedido nada — de ahí que sus `nuncaHace`
  // sean más largos que los de nadie.
  {
    id: "investigacion-comercial",
    rol: "Averigua qué le pasa a una empresa antes de que nadie le escriba",
    objetivo:
      "Una razón concreta y comprobable para hablar con ESA empresa, o la conclusión de que no la hay",
    responsabilidad:
      "Que cada afirmación sobre un prospecto se pueda enseñar con su fuente. Una observación sin fuente es suya.",
    departamento: "ventas",
    necesita: [
      { dimension: "icp", imprescindible: true },
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "sector", imprescindible: false },
    ],
    produce: "investigacion_de_prospecto",
    herramientas: ["web.read"],
    consecuencias: [],
    autonomia: "L1_RECOMENDAR",
    nuncaHace: [
      "usar datos personales que no estén publicados por la propia empresa",
      "comprar o consultar bases de datos de contactos",
      "afirmar algo de un prospecto sin poder enseñar de dónde sale",
      "investigar a una empresa que ya pidió la baja",
    ],
    escalaSi: [
      "no encuentra ni una observación concreta: entonces no hay motivo para escribir",
      "la empresa está en un sector con restricciones legales de contacto",
    ],
    rubrica: [
      "cada observación lleva fuente y fecha",
      "la conclusión dice explícitamente si HAY o NO HAY motivo para escribir",
      "no vale ninguna frase que sirviera para otra empresa distinta",
    ],
    kpis: ["prospectos con motivo propio", "prospectos descartados por falta de motivo"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
  {
    id: "redaccion-comercial",
    rol: "Escribe el primer mensaje a una empresa concreta",
    objetivo: "Un mensaje que sólo tenga sentido enviado a ESA empresa",
    responsabilidad: "El tono y el respeto. Un mensaje que molesta es suyo, aunque el motivo fuera bueno.",
    departamento: "ventas",
    necesita: [
      { dimension: "propuesta_de_valor", imprescindible: true },
      { dimension: "brand_voice", imprescindible: false },
    ],
    produce: "borrador_comercial",
    herramientas: [],
    // Redacta. NO envía: el envío no está autorizado y `enviar()` lanza
    // siempre. Declarar aquí `contacta_personas` sería declarar una
    // consecuencia que este agente no puede producir.
    consecuencias: [],
    autonomia: "L2_BORRADOR",
    nuncaHace: [
      "enviar nada",
      "escribir sin que la investigación haya encontrado un motivo",
      "prometer resultados concretos a quien todavía no es cliente",
      "omitir cómo dejar de recibir mensajes",
      "fingir una relación previa que no existe",
      "usar asuntos que engañan para que se abra el mensaje",
    ],
    escalaSi: ["el motivo que le pasan no distingue a esa empresa de cualquier otra"],
    rubrica: [
      "el mensaje nombra algo que sólo le pasa a esa empresa",
      "dice quién escribe y por qué tiene sus datos",
      "la baja está en el cuerpo, no escondida",
      "se entiende en veinte segundos",
    ],
    kpis: ["borradores aprobados por una persona", "respuestas obtenidas", "bajas solicitadas"],
    timeoutMs: TIMEOUT,
    reintentos: 1,
    exigeIaReal: true,
  },
] as const;
