import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    globals: true,
    include: [
      "src/**/*.{test,spec}.?(c|m)[jt]s?(x)",
      "../../backend/os-agents/__tests__/**/*.test.ts",
      "../../backend/os-core/__tests__/**/*.test.ts",
      "../../backend/saas/__tests__/**/*.test.ts",
      "../../backend/saas-reports/__tests__/**/*.test.ts",
      "../../backend/admin/__tests__/**/*.test.ts",
      "../../backend/email/__tests__/**/*.test.ts",
      "../../backend/monitoring/__tests__/**/*.test.ts",
      "../../backend/billing/__tests__/**/*.test.ts",
      "../../backend/db/__tests__/**/*.test.ts",
      "../../backend/queue/__tests__/**/*.test.ts",
      "../../backend/gdpr/__tests__/**/*.test.ts",
      "../../backend/health/__tests__/**/*.test.ts",
      "../../backend/integrations/__tests__/**/*.test.ts",
      "../../backend/integrations/google/__tests__/**/*.test.ts",
      "../../backend/integrations/meta/__tests__/**/*.test.ts",
      "../../backend/logger/__tests__/**/*.test.ts",
      "../../backend/support/__tests__/**/*.test.ts",
      "../../backend/feedback/__tests__/**/*.test.ts",
      "../../backend/changelog/__tests__/**/*.test.ts",
      "../../backend/affiliates/__tests__/**/*.test.ts",
      "../../backend/oauth/__tests__/**/*.test.ts",
      "../../backend/qa/__tests__/flows/**/*.test.ts",
      "../../backend/stripe/__tests__/**/*.test.ts",
      "../../backend/autonomous/__tests__/**/*.test.ts",
    ],
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "@nelvyon/os-agents/constants": path.resolve(__dirname, "../../backend/os-agents/constants.ts"),
      "@nelvyon/os-agents": path.resolve(__dirname, "../../backend/os-agents/index.ts"),
      "@nelvyon/auth/AuthService": path.resolve(__dirname, "../../backend/auth/AuthService.ts"),
      "@nelvyon/auth": path.resolve(__dirname, "../../backend/auth/index.ts"),
      "@nelvyon/billing": path.resolve(__dirname, "../../backend/billing/index.ts"),
      "@nelvyon/saas": path.resolve(__dirname, "../../backend/saas/index.ts"),
      "@nelvyon/saas-reports": path.resolve(__dirname, "../../backend/saas-reports/index.ts"),
      "@nelvyon/admin": path.resolve(__dirname, "../../backend/admin/index.ts"),
      "@nelvyon/email": path.resolve(__dirname, "../../backend/email/index.ts"),
      "@nelvyon/monitoring": path.resolve(__dirname, "../../backend/monitoring/index.ts"),
      "@nelvyon/onboarding": path.resolve(__dirname, "../../backend/onboarding/index.ts"),
      "@nelvyon/usage": path.resolve(__dirname, "../../backend/usage/index.ts"),
      "@nelvyon/errors": path.resolve(__dirname, "../../backend/errors/index.ts"),
      "@nelvyon/logger": path.resolve(__dirname, "../../backend/logger/index.ts"),
      "@nelvyon/gdpr": path.resolve(__dirname, "../../backend/gdpr/index.ts"),
      "@nelvyon/apikeys": path.resolve(__dirname, "../../backend/apikeys/index.ts"),
      // Backend os-agents imports `ws`; Vite resolves from the importing file dir unless aliased.
      ws: path.resolve(__dirname, "node_modules/ws"),
      resend: path.resolve(__dirname, "node_modules/resend"),
      "node-cron": path.resolve(__dirname, "node_modules/node-cron"),
      "@upstash/redis": path.resolve(__dirname, "node_modules/@upstash/redis"),
      "@sentry/nextjs": path.resolve(__dirname, "node_modules/@sentry/nextjs"),
      stripe: path.resolve(__dirname, "node_modules/stripe"),
      pg: path.resolve(__dirname, "../../backend/db/node_modules/pg"),
    },
  },
});
