/**
 * Global sector taxonomy — 120+ sectors for worldwide marketing coverage.
 * Used by template-library resolve + Envato/Aceternity download table generator.
 */

export type GlobalSectorMeta = {
  id: string;
  label_en: string;
  label_es: string;
  vertical: "local" | "ecommerce" | "saas_b2b" | "agency" | "creator" | "industrial";
  region_notes?: string;
};

export const GLOBAL_SECTORS: GlobalSectorMeta[] = [
  // Food & hospitality
  { id: "restaurant", label_en: "Restaurant", label_es: "Restaurante", vertical: "local" },
  { id: "cafe", label_en: "Cafe / Coffee shop", label_es: "Cafetería", vertical: "local" },
  { id: "bakery", label_en: "Bakery", label_es: "Panadería", vertical: "local" },
  { id: "bar_pub", label_en: "Bar / Pub", label_es: "Bar / Pub", vertical: "local" },
  { id: "catering", label_en: "Catering", label_es: "Catering", vertical: "local" },
  { id: "food_truck", label_en: "Food truck", label_es: "Food truck", vertical: "local" },
  { id: "ghost_kitchen", label_en: "Ghost kitchen / Delivery", label_es: "Cocina fantasma", vertical: "local" },
  { id: "fine_dining", label_en: "Fine dining", label_es: "Alta cocina", vertical: "local" },
  { id: "fast_food", label_en: "Fast food", label_es: "Comida rápida", vertical: "local" },
  { id: "pizza", label_en: "Pizzeria", label_es: "Pizzería", vertical: "local" },
  { id: "sushi", label_en: "Sushi / Japanese", label_es: "Sushi / Japonés", vertical: "local" },
  { id: "vegan_restaurant", label_en: "Vegan restaurant", label_es: "Restaurante vegano", vertical: "local" },
  { id: "brewery", label_en: "Brewery", label_es: "Cervecería", vertical: "local" },
  { id: "winery", label_en: "Winery", label_es: "Bodega", vertical: "local" },
  { id: "hotel", label_en: "Hotel", label_es: "Hotel", vertical: "local" },
  { id: "motel", label_en: "Motel", label_es: "Motel", vertical: "local" },
  { id: "hostel", label_en: "Hostel", label_es: "Hostal", vertical: "local" },
  { id: "resort", label_en: "Resort", label_es: "Resort", vertical: "local" },
  { id: "bed_breakfast", label_en: "Bed & breakfast", label_es: "B&B", vertical: "local" },
  { id: "tourism", label_en: "Tourism", label_es: "Turismo", vertical: "local" },
  { id: "travel_agency", label_en: "Travel agency", label_es: "Agencia de viajes", vertical: "local" },
  { id: "tour_operator", label_en: "Tour operator", label_es: "Operador turístico", vertical: "local" },
  { id: "event_venue", label_en: "Event venue", label_es: "Salón de eventos", vertical: "local" },
  // Health
  { id: "dental", label_en: "Dental clinic", label_es: "Clínica dental", vertical: "local" },
  { id: "clinic", label_en: "Medical clinic", label_es: "Clínica médica", vertical: "local" },
  { id: "medical", label_en: "Medical practice", label_es: "Consulta médica", vertical: "local" },
  { id: "hospital", label_en: "Hospital", label_es: "Hospital", vertical: "local" },
  { id: "veterinary", label_en: "Veterinary", label_es: "Veterinaria", vertical: "local" },
  { id: "pharmacy", label_en: "Pharmacy", label_es: "Farmacia", vertical: "local" },
  { id: "optometry", label_en: "Optometry", label_es: "Óptica", vertical: "local" },
  { id: "chiropractic", label_en: "Chiropractic", label_es: "Quiropráctica", vertical: "local" },
  { id: "physiotherapy", label_en: "Physiotherapy", label_es: "Fisioterapia", vertical: "local" },
  { id: "psychology", label_en: "Psychology / Therapy", label_es: "Psicología", vertical: "local" },
  { id: "dermatology", label_en: "Dermatology", label_es: "Dermatología", vertical: "local" },
  { id: "fertility", label_en: "Fertility clinic", label_es: "Clínica fertilidad", vertical: "local" },
  { id: "home_care", label_en: "Home care", label_es: "Cuidados a domicilio", vertical: "local" },
  { id: "senior_care", label_en: "Senior care", label_es: "Residencia mayores", vertical: "local" },
  { id: "spa", label_en: "Spa", label_es: "Spa", vertical: "local" },
  { id: "wellness_center", label_en: "Wellness center", label_es: "Centro wellness", vertical: "local" },
  { id: "yoga_studio", label_en: "Yoga studio", label_es: "Estudio yoga", vertical: "local" },
  { id: "pilates", label_en: "Pilates studio", label_es: "Pilates", vertical: "local" },
  { id: "nutritionist", label_en: "Nutritionist", label_es: "Nutricionista", vertical: "local" },
  // Fitness
  { id: "gym", label_en: "Gym", label_es: "Gimnasio", vertical: "local" },
  { id: "fitness", label_en: "Fitness center", label_es: "Centro fitness", vertical: "local" },
  { id: "crossfit", label_en: "CrossFit box", label_es: "CrossFit", vertical: "local" },
  { id: "martial_arts", label_en: "Martial arts", label_es: "Artes marciales", vertical: "local" },
  { id: "personal_trainer", label_en: "Personal trainer", label_es: "Entrenador personal", vertical: "local" },
  { id: "sports_club", label_en: "Sports club", label_es: "Club deportivo", vertical: "local" },
  { id: "golf", label_en: "Golf club", label_es: "Club de golf", vertical: "local" },
  { id: "tennis", label_en: "Tennis club", label_es: "Tenis / pádel", vertical: "local" },
  { id: "swimming", label_en: "Swimming / Aquatics", label_es: "Natación", vertical: "local" },
  { id: "dance_studio", label_en: "Dance studio", label_es: "Estudio de baile", vertical: "local" },
  // Beauty
  { id: "beauty_salon", label_en: "Beauty salon", label_es: "Salón de belleza", vertical: "local" },
  { id: "hair_salon", label_en: "Hair salon", label_es: "Peluquería", vertical: "local" },
  { id: "nail_salon", label_en: "Nail salon", label_es: "Uñas", vertical: "local" },
  { id: "barbershop", label_en: "Barbershop", label_es: "Barbería", vertical: "local" },
  { id: "cosmetics", label_en: "Cosmetics studio", label_es: "Cosmética", vertical: "local" },
  { id: "med_spa", label_en: "Medical spa", label_es: "Med spa", vertical: "local" },
  // Professional
  { id: "legal", label_en: "Law firm", label_es: "Despacho de abogados", vertical: "local" },
  { id: "accounting", label_en: "Accounting", label_es: "Asesoría fiscal", vertical: "local" },
  { id: "tax", label_en: "Tax services", label_es: "Gestoría", vertical: "local" },
  { id: "insurance", label_en: "Insurance agency", label_es: "Seguros", vertical: "local" },
  { id: "financial_advisor", label_en: "Financial advisor", label_es: "Asesor financiero", vertical: "local" },
  { id: "consulting", label_en: "Business consulting", label_es: "Consultoría", vertical: "local" },
  { id: "hr_recruiting", label_en: "HR / Recruiting", label_es: "RRHH / Selección", vertical: "local" },
  { id: "architecture", label_en: "Architecture", label_es: "Arquitectura", vertical: "local" },
  { id: "engineering", label_en: "Engineering firm", label_es: "Ingeniería", vertical: "local" },
  { id: "real_estate", label_en: "Real estate", label_es: "Inmobiliaria", vertical: "local" },
  { id: "property_management", label_en: "Property management", label_es: "Administración fincas", vertical: "local" },
  { id: "mortgage", label_en: "Mortgage broker", label_es: "Hipotecas", vertical: "local" },
  { id: "notary", label_en: "Notary", label_es: "Notaría", vertical: "local" },
  // Home services
  { id: "plumber", label_en: "Plumber", label_es: "Fontanería", vertical: "local" },
  { id: "electrician", label_en: "Electrician", label_es: "Electricista", vertical: "local" },
  { id: "hvac", label_en: "HVAC", label_es: "Climatización", vertical: "local" },
  { id: "roofing", label_en: "Roofing", label_es: "Tejados", vertical: "local" },
  { id: "cleaning", label_en: "Cleaning services", label_es: "Limpieza", vertical: "local" },
  { id: "landscaping", label_en: "Landscaping", label_es: "Jardinería", vertical: "local" },
  { id: "pest_control", label_en: "Pest control", label_es: "Control plagas", vertical: "local" },
  { id: "moving", label_en: "Moving company", label_es: "Mudanzas", vertical: "local" },
  { id: "locksmith", label_en: "Locksmith", label_es: "Cerrajería", vertical: "local" },
  { id: "solar", label_en: "Solar installer", label_es: "Solar", vertical: "local" },
  { id: "construction", label_en: "Construction", label_es: "Construcción", vertical: "local" },
  { id: "remodeling", label_en: "Remodeling", label_es: "Reformas", vertical: "local" },
  { id: "interior_design", label_en: "Interior design", label_es: "Interiorismo", vertical: "local" },
  // Automotive
  { id: "automotive", label_en: "Automotive dealer", label_es: "Concesionario", vertical: "local" },
  { id: "car_dealer", label_en: "Car dealer", label_es: "Venta coches", vertical: "local" },
  { id: "auto_repair", label_en: "Auto repair", label_es: "Taller mecánico", vertical: "local" },
  { id: "car_wash", label_en: "Car wash", label_es: "Lavado coches", vertical: "local" },
  { id: "car_rental", label_en: "Car rental", label_es: "Alquiler coches", vertical: "local" },
  // Education
  { id: "education", label_en: "Education", label_es: "Educación", vertical: "local" },
  { id: "school", label_en: "School", label_es: "Colegio", vertical: "local" },
  { id: "university", label_en: "University", label_es: "Universidad", vertical: "local" },
  { id: "tutoring", label_en: "Tutoring", label_es: "Clases particulares", vertical: "local" },
  { id: "language_school", label_en: "Language school", label_es: "Academia idiomas", vertical: "local" },
  { id: "driving_school", label_en: "Driving school", label_es: "Autoescuela", vertical: "local" },
  { id: "music_school", label_en: "Music school", label_es: "Escuela música", vertical: "local" },
  { id: "coding_bootcamp", label_en: "Coding bootcamp", label_es: "Bootcamp programación", vertical: "local" },
  // Ecommerce
  { id: "ecommerce_fashion", label_en: "Fashion ecommerce", label_es: "Moda online", vertical: "ecommerce" },
  { id: "ecommerce_electronics", label_en: "Electronics ecommerce", label_es: "Electrónica online", vertical: "ecommerce" },
  { id: "ecommerce_food", label_en: "Food ecommerce", label_es: "Food DTC", vertical: "ecommerce" },
  { id: "ecommerce_beauty", label_en: "Beauty ecommerce", label_es: "Belleza online", vertical: "ecommerce" },
  { id: "ecommerce_home", label_en: "Home goods ecommerce", label_es: "Hogar online", vertical: "ecommerce" },
  { id: "ecommerce_furniture", label_en: "Furniture ecommerce", label_es: "Muebles online", vertical: "ecommerce" },
  { id: "ecommerce_jewelry", label_en: "Jewelry ecommerce", label_es: "Joyería online", vertical: "ecommerce" },
  { id: "ecommerce_sports", label_en: "Sports ecommerce", label_es: "Deporte online", vertical: "ecommerce" },
  { id: "ecommerce_pets", label_en: "Pet products ecommerce", label_es: "Mascotas online", vertical: "ecommerce" },
  { id: "ecommerce_books", label_en: "Books / media ecommerce", label_es: "Libros online", vertical: "ecommerce" },
  { id: "marketplace", label_en: "Marketplace", label_es: "Marketplace", vertical: "ecommerce" },
  { id: "subscription_box", label_en: "Subscription box", label_es: "Caja suscripción", vertical: "ecommerce" },
  // SaaS & tech
  { id: "saas_b2b", label_en: "SaaS B2B", label_es: "SaaS B2B", vertical: "saas_b2b" },
  { id: "saas_b2c", label_en: "SaaS B2C", label_es: "SaaS B2C", vertical: "saas_b2b" },
  { id: "devtools", label_en: "Developer tools", label_es: "Herramientas dev", vertical: "saas_b2b" },
  { id: "cybersecurity", label_en: "Cybersecurity", label_es: "Ciberseguridad", vertical: "saas_b2b" },
  { id: "fintech", label_en: "Fintech", label_es: "Fintech", vertical: "saas_b2b" },
  { id: "healthtech", label_en: "Healthtech", label_es: "Healthtech", vertical: "saas_b2b" },
  { id: "edtech", label_en: "Edtech", label_es: "Edtech", vertical: "saas_b2b" },
  { id: "martech", label_en: "Martech", label_es: "Martech", vertical: "saas_b2b" },
  { id: "ai_startup", label_en: "AI startup", label_es: "Startup IA", vertical: "saas_b2b" },
  { id: "mobile_app", label_en: "Mobile app", label_es: "App móvil", vertical: "saas_b2b" },
  // Agency & creator
  { id: "agency", label_en: "Marketing agency", label_es: "Agencia marketing", vertical: "agency" },
  { id: "marketing_agency", label_en: "Digital marketing agency", label_es: "Agencia digital", vertical: "agency" },
  { id: "seo_agency", label_en: "SEO agency", label_es: "Agencia SEO", vertical: "agency" },
  { id: "creative_agency", label_en: "Creative agency", label_es: "Agencia creativa", vertical: "agency" },
  { id: "freelancer", label_en: "Freelancer", label_es: "Freelance", vertical: "agency" },
  { id: "photographer", label_en: "Photographer", label_es: "Fotógrafo", vertical: "creator" },
  { id: "videographer", label_en: "Videographer", label_es: "Videógrafo", vertical: "creator" },
  { id: "coach", label_en: "Coach", label_es: "Coach", vertical: "creator" },
  { id: "life_coach", label_en: "Life coach", label_es: "Coach de vida", vertical: "creator" },
  { id: "business_coach", label_en: "Business coach", label_es: "Coach empresarial", vertical: "creator" },
  { id: "infoproduct", label_en: "Infoproduct", label_es: "Infoproducto", vertical: "creator" },
  { id: "course", label_en: "Online course", label_es: "Curso online", vertical: "creator" },
  { id: "podcast", label_en: "Podcast", label_es: "Podcast", vertical: "creator" },
  { id: "influencer", label_en: "Influencer", label_es: "Influencer", vertical: "creator" },
  { id: "author", label_en: "Author / writer", label_es: "Autor", vertical: "creator" },
  // Other
  { id: "nonprofit", label_en: "Nonprofit", label_es: "ONG", vertical: "local" },
  { id: "church", label_en: "Church / religious", label_es: "Iglesia", vertical: "local" },
  { id: "wedding", label_en: "Wedding services", label_es: "Bodas", vertical: "local" },
  { id: "funeral", label_en: "Funeral services", label_es: "Funeraria", vertical: "local" },
  { id: "pet_services", label_en: "Pet services", label_es: "Servicios mascotas", vertical: "local" },
  { id: "daycare", label_en: "Daycare / childcare", label_es: "Guardería", vertical: "local" },
  { id: "coworking", label_en: "Coworking", label_es: "Coworking", vertical: "local" },
  { id: "franchise", label_en: "Franchise", label_es: "Franquicia", vertical: "local" },
  { id: "manufacturing", label_en: "Manufacturing", label_es: "Manufactura", vertical: "industrial" },
  { id: "logistics", label_en: "Logistics", label_es: "Logística", vertical: "industrial" },
  { id: "agriculture", label_en: "Agriculture", label_es: "Agricultura", vertical: "industrial" },
  { id: "energy", label_en: "Energy / utilities", label_es: "Energía", vertical: "industrial" },
  { id: "mining", label_en: "Mining", label_es: "Minería", vertical: "industrial" },
  { id: "government", label_en: "Government / public", label_es: "Sector público", vertical: "local" },
];

export const GLOBAL_SECTOR_COUNT = GLOBAL_SECTORS.length;

/** @deprecated Use SAAS_SERVICES from service-layers.ts — legacy seed labels only */
export const NELVYON_MARKETING_SERVICES = [
  "SEO",
  "Ads",
  "Email",
  "Landing",
  "Funnel",
  "Local",
  "Ecommerce",
  "SaaS B2B",
  "Agency",
  "Social",
  "Content",
  "CRO",
  "Brand",
  "Automation",
] as const;

/** Template kinds produced per service (seed or native). */
export const SERVICE_KIND_MAP: Record<string, string[]> = {
  SEO: ["seo_page", "content_page"],
  Ads: ["ad_creative"],
  Email: ["email_sequence", "email"],
  Landing: ["landing"],
  Funnel: ["funnel"],
  Local: ["landing", "seo_page"],
  Ecommerce: ["landing", "email_sequence"],
  "SaaS B2B": ["landing", "funnel"],
  Agency: ["landing", "report_section"],
  Social: ["ad_creative", "content_page"],
  Content: ["content_page", "seo_page"],
  CRO: ["landing", "funnel"],
  Brand: ["landing", "content_page"],
  Automation: ["automation_recipe"],
};
