/**
 * Canonical seed catalog — exact item names from Envato Elements & Aceternity UI Pro.
 */
import { createRequire } from "node:module";

import { getOsCapability, getSaasService } from "./service-layers";
import type { SeedCatalogEntry, SeedProvider } from "./types";

export type { SeedCatalogEntry, SeedProvider };

const require = createRequire(import.meta.url);

function curatedPicker():
  | typeof import("./curated-seed-library")
  | null {
  try {
    return require("./curated-seed-library") as typeof import("./curated-seed-library");
  } catch {
    return null;
  }
}

/** Sector → group for seed matching */
export const SECTOR_GROUPS: Record<string, string> = {
  restaurant: "food_hospitality",
  cafe: "food_hospitality",
  bakery: "food_hospitality",
  bar_pub: "food_hospitality",
  catering: "food_hospitality",
  food_truck: "food_hospitality",
  ghost_kitchen: "food_hospitality",
  fine_dining: "food_hospitality",
  fast_food: "food_hospitality",
  pizza: "food_hospitality",
  sushi: "food_hospitality",
  vegan_restaurant: "food_hospitality",
  brewery: "food_hospitality",
  winery: "food_hospitality",
  hotel: "hospitality_travel",
  motel: "hospitality_travel",
  hostel: "hospitality_travel",
  resort: "hospitality_travel",
  bed_breakfast: "hospitality_travel",
  tourism: "hospitality_travel",
  travel_agency: "hospitality_travel",
  tour_operator: "hospitality_travel",
  event_venue: "hospitality_travel",
  dental: "health_medical",
  clinic: "health_medical",
  medical: "health_medical",
  hospital: "health_medical",
  veterinary: "health_medical",
  pharmacy: "health_medical",
  optometry: "health_medical",
  chiropractic: "health_medical",
  physiotherapy: "health_medical",
  psychology: "health_medical",
  dermatology: "health_medical",
  fertility: "health_medical",
  home_care: "health_medical",
  senior_care: "health_medical",
  spa: "beauty_wellness",
  wellness_center: "beauty_wellness",
  yoga_studio: "fitness_sports",
  pilates: "fitness_sports",
  nutritionist: "beauty_wellness",
  gym: "fitness_sports",
  fitness: "fitness_sports",
  crossfit: "fitness_sports",
  martial_arts: "fitness_sports",
  personal_trainer: "fitness_sports",
  sports_club: "fitness_sports",
  golf: "fitness_sports",
  tennis: "fitness_sports",
  swimming: "fitness_sports",
  dance_studio: "fitness_sports",
  beauty_salon: "beauty_wellness",
  hair_salon: "beauty_wellness",
  nail_salon: "beauty_wellness",
  barbershop: "beauty_wellness",
  cosmetics: "beauty_wellness",
  med_spa: "beauty_wellness",
  legal: "professional",
  accounting: "professional",
  tax: "professional",
  insurance: "professional",
  financial_advisor: "professional",
  consulting: "professional",
  hr_recruiting: "professional",
  architecture: "professional",
  engineering: "professional",
  real_estate: "professional",
  property_management: "professional",
  mortgage: "professional",
  notary: "professional",
  plumber: "home_services",
  electrician: "home_services",
  hvac: "home_services",
  roofing: "home_services",
  cleaning: "home_services",
  landscaping: "home_services",
  pest_control: "home_services",
  moving: "home_services",
  locksmith: "home_services",
  solar: "home_services",
  construction: "home_services",
  remodeling: "home_services",
  interior_design: "home_services",
  automotive: "automotive",
  car_dealer: "automotive",
  auto_repair: "automotive",
  car_wash: "automotive",
  car_rental: "automotive",
  education: "education",
  school: "education",
  university: "education",
  tutoring: "education",
  language_school: "education",
  driving_school: "education",
  music_school: "education",
  coding_bootcamp: "education",
  ecommerce_fashion: "ecommerce",
  ecommerce_electronics: "ecommerce",
  ecommerce_food: "ecommerce",
  ecommerce_beauty: "ecommerce",
  ecommerce_home: "ecommerce",
  ecommerce_furniture: "ecommerce",
  ecommerce_jewelry: "ecommerce",
  ecommerce_sports: "ecommerce",
  ecommerce_pets: "ecommerce",
  ecommerce_books: "ecommerce",
  marketplace: "ecommerce",
  subscription_box: "ecommerce",
  saas_b2b: "saas_tech",
  saas_b2c: "saas_tech",
  devtools: "saas_tech",
  cybersecurity: "saas_tech",
  fintech: "saas_tech",
  healthtech: "saas_tech",
  edtech: "saas_tech",
  martech: "saas_tech",
  ai_startup: "saas_tech",
  mobile_app: "saas_tech",
  agency: "agency_creator",
  marketing_agency: "agency_creator",
  seo_agency: "agency_creator",
  creative_agency: "agency_creator",
  freelancer: "agency_creator",
  photographer: "agency_creator",
  videographer: "agency_creator",
  coach: "agency_creator",
  life_coach: "agency_creator",
  business_coach: "agency_creator",
  infoproduct: "agency_creator",
  course: "agency_creator",
  podcast: "agency_creator",
  influencer: "agency_creator",
  author: "agency_creator",
  nonprofit: "other",
  church: "other",
  wedding: "other",
  funeral: "other",
  pet_services: "other",
  daycare: "other",
  coworking: "other",
  franchise: "other",
  manufacturing: "industrial",
  logistics: "industrial",
  agriculture: "industrial",
  energy: "industrial",
  mining: "industrial",
  government: "other",
};

export const SEED_DOWNLOAD_CATALOG: SeedCatalogEntry[] = [
  // ─── ACETERNITY (exact names from ui.aceternity.com/templates) ───
  {
    provider: "Aceternity",
    item_name: "Simplistic SaaS Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B", "Funnel"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Seed → bloques hero_3d/bento; pack SaaS B2B demo/trial",
  },
  {
    provider: "Aceternity",
    item_name: "AI SaaS Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B", "Funnel"],
    match: { sectors: ["ai_startup", "martech", "devtools"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Multi-page AI SaaS; seed multipágina",
  },
  {
    provider: "Aceternity",
    item_name: "Startup Landing Page Template",
    kinds: ["landing"],
    services: ["Landing", "SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Microinteractions; startup general",
  },
  {
    provider: "Aceternity",
    item_name: "Nodus Agent Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B", "Chatbot"],
    match: { sectors: ["ai_startup", "chatbot"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "AI agents/chatbots landing",
  },
  {
    provider: "Aceternity",
    item_name: "Agenforce Marketing Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Agency", "SaaS B2B"],
    match: { groups: ["agency_creator", "saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Agency + SaaS marketing",
  },
  {
    provider: "Aceternity",
    item_name: "Foxtrot Marketing Template",
    kinds: ["landing"],
    services: ["Landing", "Brand"],
    match: { groups: ["saas_tech", "agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Single-page SaaS marketing (ya en repo _extracted)",
  },
  {
    provider: "Aceternity",
    item_name: "Proactiv Marketing Template",
    kinds: ["landing", "social"],
    services: ["Landing", "Social", "Brand"],
    match: { groups: ["saas_tech", "agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Social media tools SaaS",
  },
  {
    provider: "Aceternity",
    item_name: "Productized Agency Template",
    kinds: ["landing", "funnel"],
    services: ["Agency", "Landing", "SaaS B2B"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Agency packages/pricing; parcial en components/pa",
  },
  {
    provider: "Aceternity",
    item_name: "Agenlabs Agency Template",
    kinds: ["landing"],
    services: ["Agency", "Landing"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Agency corporate",
  },
  {
    provider: "Aceternity",
    item_name: "Schedule Marketing Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { groups: ["health_medical", "beauty_wellness", "professional"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Booking/appointments — clínicas, salones, consultas",
  },
  {
    provider: "Aceternity",
    item_name: "Playful Marketing Template",
    kinds: ["landing"],
    services: ["Landing", "Brand", "Social"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Creator/coach playful brand",
  },
  {
    provider: "Aceternity",
    item_name: "Cryptgen Marketing Template",
    kinds: ["landing"],
    services: ["Landing", "SaaS B2B"],
    match: { sectors: ["fintech", "ai_startup"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Bento + testimonials fintech/crypto style",
  },
  {
    provider: "Aceternity",
    item_name: "Minimal Portfolio Template",
    kinds: ["landing", "content_page"],
    services: ["Landing", "Content", "Agency"],
    match: { sectors: ["photographer", "freelancer", "videographer", "author"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Portfolio creators",
  },
  {
    provider: "Aceternity",
    item_name: "DevPro Portfolio Template",
    kinds: ["landing", "content_page"],
    services: ["Landing", "Content"],
    match: { sectors: ["freelancer", "devtools"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Developer portfolio",
  },
  // ─── ENVATO — Food & hospitality ───
  {
    provider: "EnvatoElements",
    item_name: "Granny - Elegant Restaurant & Cafe HTML Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { groups: ["food_hospitality"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Restaurante/café; menú + reservas",
  },
  {
    provider: "EnvatoElements",
    item_name: "Pizzan - Fast Food and Restaurant HTML Template",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { sectors: ["pizza", "fast_food"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Fast food / pizza",
  },
  {
    provider: "EnvatoElements",
    item_name: "Savory Haven - Restaurant Landing Page",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { groups: ["food_hospitality"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Figma/XD seed; convertir a bloques",
  },
  {
    provider: "EnvatoElements",
    item_name: "Restaurant Email Newsletter Template",
    kinds: ["email_sequence", "email"],
    services: ["Email", "Local"],
    match: { groups: ["food_hospitality"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Newsletter promo menú/eventos",
  },
  {
    provider: "EnvatoElements",
    item_name: "Fast Food Restaurant Email Newsletter Template",
    kinds: ["email"],
    services: ["Email"],
    match: { sectors: ["fast_food", "food_truck", "pizza"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Email promo oferta",
  },
  {
    provider: "EnvatoElements",
    item_name: "Pearl - Hotel & Restaurant Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { groups: ["hospitality_travel"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Hotel + restaurante",
  },
  // ─── ENVATO — Health ───
  {
    provider: "EnvatoElements",
    item_name: "Dentist & Dental Clinic Web Template - Dentia",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { sectors: ["dental"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Clínica dental primera cita",
  },
  {
    provider: "EnvatoElements",
    item_name: "Dentalux",
    kinds: ["landing", "seo_page"],
    services: ["Landing", "Local", "SEO"],
    match: { groups: ["health_medical"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Dental + clínica general",
  },
  {
    provider: "EnvatoElements",
    item_name: "Dotus – Health & Medical HTML5 Template",
    kinds: ["landing", "seo_page"],
    services: ["Landing", "Local", "SEO"],
    match: { groups: ["health_medical"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Hospital, clínica, farmacia",
  },
  {
    provider: "EnvatoElements",
    item_name: "Medical, Spa, Yoga & Fitness Landing Page Template",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { groups: ["beauty_wellness", "fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Spa, yoga, wellness",
  },
  // ─── ENVATO — Fitness ───
  {
    provider: "EnvatoElements",
    item_name: "Gymfito - Tailwind CSS Fitness & Gym HTML Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { groups: ["fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Gym, trainer, clases",
  },
  {
    provider: "EnvatoElements",
    item_name: "GymOn - Gym and Fitness Club HTML Template",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { groups: ["fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Crossfit, yoga club",
  },
  {
    provider: "EnvatoElements",
    item_name: "Fitmas - Gym & Fitness Center HTML Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Funnel", "Local"],
    match: { groups: ["fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "17 inner pages; funnel membership",
  },
  // ─── ENVATO — Legal & professional ───
  {
    provider: "EnvatoElements",
    item_name: "Atorn - Law Firm & Attorney Website HTML Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel"],
    match: { sectors: ["legal"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Despacho abogados consulta",
  },
  {
    provider: "EnvatoElements",
    item_name: "Lawfinity | Law and Attorney HTML Template",
    kinds: ["landing", "seo_page"],
    services: ["Landing", "SEO", "Local"],
    match: { sectors: ["legal", "notary"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "SEO legal practice areas",
  },
  {
    provider: "EnvatoElements",
    item_name: "Lyzo - Law Firm & Attorney HTML Template",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { sectors: ["legal"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Alternativa legal RTL",
  },
  // ─── ENVATO — Real estate & home services ───
  {
    provider: "EnvatoElements",
    item_name: "Grand - Lead Generating HTML Landing Pages",
    kinds: ["landing", "funnel"],
    services: ["Landing", "Local", "Funnel", "CRO"],
    match: { sectors: ["real_estate", "solar", "construction", "mortgage"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Lead gen valoración/presupuesto",
  },
  // ─── ENVATO — Ecommerce ───
  {
    provider: "EnvatoElements",
    item_name: "GoShop - Premium HTML Ecommerce Template",
    kinds: ["landing", "funnel"],
    services: ["Ecommerce", "Landing", "Funnel"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Tienda multipropósito",
  },
  {
    provider: "EnvatoElements",
    item_name: "Comercio - Fashion Shop Ecommerce HTML Template",
    kinds: ["landing"],
    services: ["Ecommerce", "Landing"],
    match: { sectors: ["ecommerce_fashion", "ecommerce_beauty"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Moda DTC",
  },
  {
    provider: "EnvatoElements",
    item_name: "ECOSHOP - Multipurpose eCommerce HTML5 Template",
    kinds: ["landing", "funnel"],
    services: ["Ecommerce", "Landing"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Multicategoría",
  },
  {
    provider: "EnvatoElements",
    item_name: "Olive - Fashion Ecommerce Email Newsletter",
    kinds: ["email_sequence", "email"],
    services: ["Email", "Ecommerce"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Newsletter moda; carrito welcome",
  },
  {
    provider: "EnvatoElements",
    item_name: "Fashino - Responsive Shop Email Templates",
    kinds: ["email_sequence", "email"],
    services: ["Email", "Ecommerce"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "40+ secciones email ecommerce",
  },
  {
    provider: "EnvatoElements",
    item_name: "Evolia Email eCommerce Newsletter",
    kinds: ["email"],
    services: ["Email", "Ecommerce"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Campañas promo",
  },
  {
    provider: "EnvatoElements",
    item_name: "Fashionistas - Responsive Email Template",
    kinds: ["email"],
    services: ["Email"],
    match: { sectors: ["ecommerce_fashion"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Moda seasonal",
  },
  // ─── ENVATO — SaaS ───
  {
    provider: "EnvatoElements",
    item_name: "Softing – Software & SaaS Landing Page Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B", "Funnel"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Bootstrap 5 SaaS; pricing CTA",
  },
  {
    provider: "EnvatoElements",
    item_name: "Anaton - SaaS & AI Startup landing Page",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B", "Funnel"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "35+ páginas; demo funnel",
  },
  {
    provider: "EnvatoElements",
    item_name: "Cloudly – SaaS, Software & App Landing HTML Template",
    kinds: ["landing"],
    services: ["Landing", "SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "App landing 3 homes",
  },
  {
    provider: "EnvatoElements",
    item_name: "Saasten - SaaS & Software HTML Template",
    kinds: ["landing", "funnel"],
    services: ["Landing", "SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "07+ home layouts",
  },
  {
    provider: "EnvatoElements",
    item_name: "WETA - SaaS Landing HTML5 Template",
    kinds: ["landing"],
    services: ["Landing", "SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Trial signup",
  },
  {
    provider: "EnvatoElements",
    item_name: "Boostly – SaaS & Tech Startup HTML Template",
    kinds: ["landing"],
    services: ["Landing", "SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Tech startup",
  },
  // ─── ENVATO — Agency ───
  {
    provider: "EnvatoElements",
    item_name: "Yoso - Digital Marketing Agency HTML Landing Page",
    kinds: ["landing", "funnel"],
    services: ["Agency", "Landing", "Funnel"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "9 layouts leadgen; auditoría gratis",
  },
  {
    provider: "EnvatoElements",
    item_name: "Andeo - Digital Marketing Agency HTML Template",
    kinds: ["landing", "seo_page"],
    services: ["Agency", "SEO", "Landing"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "SEO agency inner pages",
  },
  {
    provider: "EnvatoElements",
    item_name: "Cleo - Agency Landing Page Template",
    kinds: ["landing"],
    services: ["Agency", "Landing"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Agency corporate",
  },
  // ─── ENVATO — Email general ───
  {
    provider: "EnvatoElements",
    item_name: "Fresh Mail - Responsive E-mail Template",
    kinds: ["email_sequence", "email"],
    services: ["Email"],
    match: { groups: ["saas_tech", "agency_creator", "professional"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Multipropósito B2B",
  },
  {
    provider: "EnvatoElements",
    item_name: "Black - Notification Email Templates",
    kinds: ["email"],
    services: ["Email", "Automation"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Transaccional SaaS",
  },
  {
    provider: "EnvatoElements",
    item_name: "Minimal Email Newsletter Template",
    kinds: ["email_sequence"],
    services: ["Email", "Content"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Coach/infoproduct nurture",
  },
  // ─── ENVATO — SEO / Content ───
  {
    provider: "EnvatoElements",
    item_name: "Nature Blog Article Website Template",
    kinds: ["content_page", "seo_page"],
    services: ["SEO", "Content"],
    match: { groups: ["education", "agency_creator", "other"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Blog/article layout SEO",
  },
  // ─── ENVATO — Ads / Social ───
  {
    provider: "EnvatoElements",
    item_name: "Gym Google Adwords HTML5 Banner Ads GWD",
    kinds: ["ad_creative"],
    services: ["Ads", "Social"],
    match: { groups: ["fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Display banners gym",
  },
  {
    provider: "EnvatoElements",
    item_name: "Fashion Email Newsletter Template",
    kinds: ["ad_creative", "social"],
    services: ["Social", "Ads"],
    match: { sectors: ["influencer", "ecommerce_fashion", "coach"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Visual hooks Instagram/email",
  },
  {
    provider: "EnvatoElements",
    item_name: "Workout Youtube Thumbnail Template",
    kinds: ["ad_creative", "content_page"],
    services: ["Social", "Content", "Ads"],
    match: { groups: ["fitness_sports", "agency_creator"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "YouTube/social thumbnails",
  },
  // ─── Fallbacks by vertical (reuse across sectors) ───
  {
    provider: "EnvatoElements",
    item_name: "Kababi - Restaurant HTMLTemplate",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { groups: ["food_hospitality"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Fallback food service",
  },
  {
    provider: "EnvatoElements",
    item_name: "Ensaf - Attorney Lawyer HTML Template",
    kinds: ["landing"],
    services: ["Landing", "Local"],
    match: { groups: ["professional"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Fallback professional services",
  },
  {
    provider: "EnvatoElements",
    item_name: "Maxshop - Multipurpose eCommerce HTML Template",
    kinds: ["landing"],
    services: ["Ecommerce", "Landing"],
    match: { groups: ["ecommerce", "industrial"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Fallback retail/industrial DTC",
  },
  {
    provider: "EnvatoElements",
    item_name: "OSaaS - SaaS & Startup Agency Template",
    kinds: ["landing"],
    services: ["SaaS B2B", "Agency", "Landing"],
    match: { groups: ["saas_tech", "agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Fallback SaaS/agency",
  },
];

/** Fallback when no specific seed matches */
export const SEED_FALLBACKS: Record<string, SeedCatalogEntry> = {
  food_hospitality: {
    provider: "EnvatoElements",
    item_name: "Granny - Elegant Restaurant & Cafe HTML Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["food_hospitality"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  health_medical: {
    provider: "EnvatoElements",
    item_name: "Dotus – Health & Medical HTML5 Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["health_medical"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  fitness_sports: {
    provider: "EnvatoElements",
    item_name: "Gymfito - Tailwind CSS Fitness & Gym HTML Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["fitness_sports"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  professional: {
    provider: "EnvatoElements",
    item_name: "Ensaf - Attorney Lawyer HTML Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["professional"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  home_services: {
    provider: "EnvatoElements",
    item_name: "Grand - Lead Generating HTML Landing Pages",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["home_services"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Lead gen home services",
  },
  ecommerce: {
    provider: "EnvatoElements",
    item_name: "GoShop - Premium HTML Ecommerce Template",
    kinds: ["landing"],
    services: ["Ecommerce"],
    match: { groups: ["ecommerce"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "Group fallback",
  },
  saas_tech: {
    provider: "Aceternity",
    item_name: "Simplistic SaaS Template",
    kinds: ["landing"],
    services: ["SaaS B2B"],
    match: { groups: ["saas_tech"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Group fallback",
  },
  agency_creator: {
    provider: "Aceternity",
    item_name: "Productized Agency Template",
    kinds: ["landing"],
    services: ["Agency"],
    match: { groups: ["agency_creator"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Group fallback",
  },
  hospitality_travel: {
    provider: "EnvatoElements",
    item_name: "Pearl - Hotel & Restaurant Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["hospitality_travel"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  beauty_wellness: {
    provider: "EnvatoElements",
    item_name: "Medical, Spa, Yoga & Fitness Landing Page Template",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["beauty_wellness"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Group fallback",
  },
  automotive: {
    provider: "EnvatoElements",
    item_name: "Grand - Lead Generating HTML Landing Pages",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["automotive"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Auto dealer lead gen",
  },
  education: {
    provider: "EnvatoElements",
    item_name: "Nature Blog Article Website Template",
    kinds: ["content_page"],
    services: ["Content", "SEO"],
    match: { groups: ["education"] },
    pack_ids: "local-business-growth",
    lang: "en",
    notes: "Education content SEO",
  },
  industrial: {
    provider: "EnvatoElements",
    item_name: "Maxshop - Multipurpose eCommerce HTML Template",
    kinds: ["landing"],
    services: ["Ecommerce", "Landing"],
    match: { groups: ["industrial"] },
    pack_ids: "ecommerce-growth",
    lang: "en",
    notes: "B2B industrial catalog",
  },
  other: {
    provider: "EnvatoElements",
    item_name: "Yoso - Digital Marketing Agency HTML Landing Page",
    kinds: ["landing"],
    services: ["Landing"],
    match: { groups: ["other"] },
    pack_ids: "saas-b2b-growth",
    lang: "en",
    notes: "Nonprofit/wedding/etc fallback",
  },
};

export function matchSeed(
  sectorId: string,
  service: string,
  kind: string,
  varietyKey?: string,
): SeedCatalogEntry {
  const curatedMod = curatedPicker();
  const curated = curatedMod?.pickCuratedSeed({ sectorId, service, kind, varietyKey });
  if (curated && curatedMod) return curatedMod.curatedSeedToCatalogEntry(curated);

  const normalizedKind = normalizeSeedKind(kind);
  const group = SECTOR_GROUPS[sectorId] ?? "other";
  const candidates = SEED_DOWNLOAD_CATALOG.filter((s) => {
    if (!s.kinds.includes(normalizedKind) && !s.kinds.includes(kind)) return false;
    if (!s.services.includes(service) && !s.services.includes("Landing")) return false;
    if (s.match.sectors?.includes(sectorId)) return true;
    if (s.match.groups?.includes(group)) return true;
    return false;
  });
  if (candidates.length) return candidates[0]!;
  const fallback = SEED_FALLBACKS[group] ?? SEED_FALLBACKS.other!;
  return { ...fallback, kinds: [normalizedKind], services: [service], notes: `${fallback.notes}; kind=${kind}` };
}

function normalizeSeedKind(kind: string): string {
  const map: Record<string, string> = {
    chatbot_flow: "landing",
    web_page: "landing",
    store_page: "landing",
    workflow_diagram: "automation_recipe",
    analytics_report: "report_section",
    social_post: "ad_creative",
    video_script: "ad_creative",
    creative_graphic: "ad_creative",
    brand_asset: "content_page",
  };
  return map[kind] ?? kind;
}

/** Maps SaaS service / OS capability id → legacy seed catalog service labels */
const SAAS_SERVICE_LEGACY_KEYS: Record<string, string[]> = {
  pack_growth_local: ["Local", "Landing", "Funnel"],
  pack_growth_ecommerce: ["Ecommerce", "Landing", "Ads"],
  pack_growth_saas_b2b: ["SaaS B2B", "Landing", "Funnel"],
  pack_seo_local: ["SEO", "Local"],
  pack_meta_ads: ["Ads", "Ecommerce"],
  pack_email_nurture: ["Email"],
  pack_landing_funnel: ["Landing", "Funnel", "CRO"],
  pack_social_calendar: ["Social", "Content"],
  pack_content_strategy: ["Content", "SEO"],
  pack_cro_audit: ["CRO", "Landing", "Funnel"],
  pack_analytics_insights: ["Analytics"],
  pack_analytics_setup: ["Analytics"],
  pack_brand_voice: ["Brand", "Content"],
  sku_web_corporate: ["Landing", "SEO"],
  sku_landing: ["Landing", "Funnel"],
  sku_ecommerce: ["Ecommerce", "Landing"],
  sku_logo: ["Brand"],
  sku_branding: ["Brand", "Content"],
  sku_chatbot: ["Local", "Landing"],
  sku_seo: ["SEO"],
  sku_google_ads: ["Ads"],
  sku_meta_ads: ["Ads"],
  sku_tiktok_ads: ["Ads", "Social"],
  sku_automation: ["Automation", "Email"],
  marketing_seo_ia: ["SEO"],
  marketing_publicidad_ia: ["Ads"],
  marketing_contenido_ia: ["Content"],
  marketing_email_ia: ["Email"],
  marketing_branding_ia: ["Brand"],
  marketing_social_ia: ["Social"],
  marketing_chatbot_ia: ["Local"],
  marketing_automation_ia: ["Automation"],
  marketing_crm_ia: ["Agency"],
  marketing_landing_pages_ia: ["Landing", "Funnel"],
  marketing_tiendas_online_ia: ["Ecommerce"],
  marketing_diseno_ia: ["Brand"],
  feature_campaigns: ["Ads", "Email"],
  feature_portal: ["Landing"],
};

const OS_CAPABILITY_LEGACY_KEYS: Record<string, string[]> = {
  cap_web_premium: ["Landing", "SEO"],
  cap_ecommerce_premium: ["Ecommerce", "Landing"],
  cap_seo_premium: ["SEO", "Content"],
  cap_ads_premium: ["Ads"],
  cap_branding_premium: ["Brand", "Content"],
  cap_bots_premium: ["Local", "Landing"],
  cap_email_marketing_premium: ["Email"],
  cap_social_media_premium: ["Social", "Content"],
  cap_contenido_copywriting_premium: ["Content", "SEO"],
  cap_landing_premium: ["Landing", "Funnel"],
  cap_funnel_premium: ["Funnel", "Landing"],
  cap_consultoria_automatizacion_premium: ["Automation", "Email"],
  cap_landing_builder: ["Landing"],
  cap_funnel_builder: ["Funnel", "Landing"],
  cap_web_builder: ["Landing"],
  cap_analytics_engine: ["Analytics"],
  cap_workflow_engine: ["Automation"],
  cap_template_factory: ["Landing", "Email"],
  cap_autonomous_landing_pipeline: ["Landing", "SEO"],
  cap_autonomous_seo_pipeline: ["SEO", "Content"],
  cap_autonomous_chatbot_pipeline: ["Local", "Landing"],
  cap_process_templates: ["Automation"],
  cap_cro_lab: ["CRO", "Landing"],
  cap_diseno_grafico_creatividades_premium: ["Brand", "Ads"],
  cap_video_multimedia_premium: ["Ads", "Social"],
  cap_voz_premium: ["Content"],
  cap_reputacion_online_orm_premium: ["Content"],
  cap_influencer_marketing_premium: ["Social", "Ads"],
  cap_integraciones_apis_premium: ["Automation"],
  cap_mantenimiento_web_premium: ["Landing"],
  cap_formacion_capacitacion_digital_premium: ["Content"],
  cap_advisor_empresarial_premium: ["Agency"],
  cap_canales_comunicaciones_premium: ["Email", "Social"],
  cap_personal_digital_premium: ["Content", "Social"],
  "cap_3d_contenido_inmersivo_premium": ["Landing", "Brand"],
  cap_fotografia_producto_premium: ["Ecommerce", "Brand"],
};

export function matchSeedForLayer(
  layer: "saas" | "os",
  sectorId: string,
  serviceId: string,
  kind: string,
  varietyKey?: string,
): SeedCatalogEntry {
  const keys =
    layer === "saas"
      ? SAAS_SERVICE_LEGACY_KEYS[serviceId] ?? ["Landing"]
      : OS_CAPABILITY_LEGACY_KEYS[serviceId] ?? ["Landing"];
  for (const key of keys) {
    const hit = matchSeed(sectorId, key, kind, varietyKey);
    if (hit) return hit;
  }
  return matchSeed(sectorId, "Landing", kind, varietyKey);
}

export function resolveRowLayer(
  layer: "saas" | "os",
  serviceId: string,
): "saas" | "os" | "both" {
  if (layer === "saas") {
    const s = getSaasService(serviceId);
    return s?.dual_os_id ? "both" : "saas";
  }
  const c = getOsCapability(serviceId);
  return c?.dual_saas_id ? "both" : "os";
}
