import type { NelvyonTemplateEntry } from "../types";

export const AD_CREATIVE_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "ads-meta-local-offer-v1",
    name: "Meta · Oferta local (imagen + copy)",
    kind: "ad_creative",
    service: "ads",
    sector: "restaurant",
    verticals: ["local"],
    languages: ["es"],
    tags: ["meta", "local", "offer"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 84, conversion: 86, speed: 90, premium: 82 },
    pack_ids: ["local-business-growth"],
    composition: ["hook:oferta-limitada", "cta:reservar", "format:1080x1080"],
  },
  {
    id: "ads-google-local-v1",
    name: "Google Search · Extensión local",
    kind: "ad_creative",
    service: "ads",
    sector: "dental",
    verticals: ["local"],
    languages: ["es"],
    tags: ["google", "search", "local"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 86, conversion: 85, speed: 95, premium: 83 },
    pack_ids: ["local-business-growth"],
    composition: ["headlines:3", "descriptions:2", "extensions:call"],
  },
  {
    id: "ads-meta-catalog-v1",
    name: "Meta · Catálogo Advantage+",
    kind: "ad_creative",
    service: "ads",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["meta", "catalog", "dpa"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 88, speed: 88, premium: 85 },
    pack_ids: ["ecommerce-growth"],
    composition: ["format:carousel", "copy:ugc-style", "cta:shop-now"],
  },
  {
    id: "ads-meta-retarget-v1",
    name: "Meta · Retargeting visitantes",
    kind: "ad_creative",
    service: "ads",
    sector: "ecommerce_electronics",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["retargeting", "meta"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 85, conversion: 87, speed: 89, premium: 84 },
    pack_ids: ["ecommerce-growth"],
  },
  {
    id: "ads-linkedin-demo-v1",
    name: "LinkedIn · Demo B2B",
    kind: "ad_creative",
    service: "ads",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["linkedin", "b2b", "demo"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 84, speed: 92, premium: 89 },
    pack_ids: ["saas-b2b-growth"],
    composition: ["format:single-image", "copy:pain-roi", "cta:book-demo"],
  },
  {
    id: "ads-coach-story-v1",
    name: "Instagram Story · Coach transformación",
    kind: "ad_creative",
    service: "ads",
    sector: "coach",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["story", "coach", "ugc"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 83, conversion: 86, speed: 91, premium: 80 },
    composition: ["format:1080x1920", "hook:antes-despues"],
  },
];

export const SEO_PAGE_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "seo-local-service-page-v1",
    name: "SEO local · Página servicio + schema",
    kind: "seo_page",
    service: "seo",
    sector: "all",
    verticals: ["local"],
    languages: ["es"],
    tags: ["local-seo", "schema", "service-area"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 80, speed: 88, premium: 84 },
    pack_ids: ["local-business-growth"],
    composition: ["h1:service+city", "faq:accordion", "schema:LocalBusiness"],
  },
  {
    id: "seo-ecom-category-v1",
    name: "SEO ecommerce · Página categoría",
    kind: "seo_page",
    service: "seo",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["category", "catalog", "internal-links"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 86, conversion: 78, speed: 85, premium: 83 },
    pack_ids: ["ecommerce-growth"],
  },
  {
    id: "seo-saas-pillar-v1",
    name: "SEO SaaS · Pillar page",
    kind: "seo_page",
    service: "seo",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["pillar", "cluster", "b2b"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 89, conversion: 75, speed: 86, premium: 88 },
    pack_ids: ["saas-b2b-growth"],
  },
];

export const REPORT_SECTION_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "report-ceo-summary-v1",
    name: "Informe · Resumen ejecutivo CEO",
    kind: "report_section",
    service: "report",
    sector: "all",
    verticals: ["local", "ecommerce", "saas_b2b"],
    languages: ["es", "en"],
    tags: ["ceo", "summary", "pack-report"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 90, conversion: 70, speed: 95, premium: 91 },
    pack_ids: ["local-business-growth", "ecommerce-growth", "saas-b2b-growth"],
  },
  {
    id: "report-seo-local-scorecard-v1",
    name: "Informe · Scorecard SEO local",
    kind: "report_section",
    service: "report",
    sector: "all",
    verticals: ["local"],
    languages: ["es"],
    tags: ["seo", "local", "scorecard"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 72, speed: 94, premium: 87 },
    pack_ids: ["local-business-growth"],
  },
];
