import type { NelvyonTemplateEntry } from "../types";

export const EMAIL_SEQUENCE_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "seq-local-welcome-3",
    name: "Local · Bienvenida 3 emails",
    kind: "email_sequence",
    service: "email",
    sector: "all",
    verticals: ["local"],
    languages: ["es"],
    tags: ["welcome", "local", "onboarding"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 86, conversion: 82, speed: 95, premium: 84 },
    pack_ids: ["local-business-growth"],
    composition: ["email-local-welcome-1", "email-local-welcome-2", "email-local-welcome-3"],
    description: "Día 0 presentación, día 2 valor, día 5 CTA reserva",
  },
  {
    id: "seq-ecom-cart-abandon-3",
    name: "Ecommerce · Carrito abandonado",
    kind: "email_sequence",
    service: "email",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["cart", "recovery", "ecommerce"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 90, speed: 94, premium: 85 },
    pack_ids: ["ecommerce-growth"],
    composition: ["email-cart-1h", "email-cart-24h", "email-cart-72h-discount"],
  },
  {
    id: "seq-saas-b2b-nurture-5",
    name: "SaaS B2B · Nurture post-demo",
    kind: "email_sequence",
    service: "email",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["nurture", "demo", "b2b"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 90, conversion: 86, speed: 93, premium: 89 },
    pack_ids: ["saas-b2b-growth"],
    composition: ["email-b2b-thanks", "email-b2b-case", "email-b2b-roi", "email-b2b-objections", "email-b2b-trial-cta"],
  },
  {
    id: "seq-coach-webinar-followup-4",
    name: "Coach · Post-webinar",
    kind: "email_sequence",
    service: "email",
    sector: "coach",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["webinar", "replay", "offer"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 85, conversion: 88, speed: 94, premium: 82 },
    composition: ["email-webinar-replay", "email-webinar-notes", "email-webinar-offer", "email-webinar-last-call"],
  },
  {
    id: "seq-agency-onboarding-4",
    name: "Agencia · Onboarding cliente",
    kind: "email_sequence",
    service: "agency",
    sector: "agency",
    verticals: ["agency"],
    languages: ["es", "en"],
    tags: ["onboarding", "agency", "kickoff"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 80, speed: 95, premium: 88 },
    composition: ["email-agency-welcome", "email-agency-brief", "email-agency-access", "email-agency-week1"],
  },
  {
    id: "seq-reactivation-winback-3",
    name: "Reactivación · Win-back",
    kind: "email_sequence",
    service: "email",
    sector: "all",
    verticals: ["local", "ecommerce", "saas_b2b"],
    languages: ["es", "en"],
    tags: ["reactivation", "churn", "winback"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 84, conversion: 85, speed: 94, premium: 83 },
    composition: ["email-winback-miss", "email-winback-offer", "email-winback-final"],
  },
];

export const EMAIL_SINGLE_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "email-local-welcome-1",
    name: "Local · Bienvenida día 0",
    kind: "email",
    service: "email",
    sector: "all",
    verticals: ["local"],
    languages: ["es"],
    tags: ["transactional", "welcome"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 85, conversion: 78, speed: 96, premium: 82 },
  },
  {
    id: "email-cart-24h",
    name: "Ecommerce · Carrito 24h",
    kind: "email",
    service: "email",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["cart", "reminder"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 89, speed: 95, premium: 84 },
  },
  {
    id: "email-b2b-trial-cta",
    name: "SaaS · CTA trial",
    kind: "email",
    service: "email",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["trial", "cta"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 86, speed: 95, premium: 87 },
  },
];
