import type { NelvyonTemplateEntry } from "../types";

export const FUNNEL_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "funnel-local-reserva-crm",
    name: "Local · Anuncio → Landing → Reserva → CRM",
    kind: "funnel",
    service: "funnel",
    sector: "restaurant",
    verticals: ["local"],
    languages: ["es"],
    tags: ["local", "reservas", "google-ads"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 86, speed: 85, premium: 84 },
    pack_ids: ["local-business-growth"],
    composition: ["ads-google-local-v1", "landing-restaurant-reservas-v1", "automation-local-lead-crm", "seq-local-welcome-3"],
  },
  {
    id: "funnel-dental-search-cita",
    name: "Dental · Search → Cita → Pipeline",
    kind: "funnel",
    service: "funnel",
    sector: "dental",
    verticals: ["local"],
    languages: ["es"],
    tags: ["dental", "seo", "citas"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 89, conversion: 87, speed: 84, premium: 88 },
    pack_ids: ["local-business-growth"],
    composition: ["landing-dental-cita-v1", "automation-local-lead-crm", "seq-local-welcome-3"],
  },
  {
    id: "funnel-ecom-meta-purchase",
    name: "Ecommerce · Meta → Tienda → Checkout → CRM",
    kind: "funnel",
    service: "funnel",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["meta", "catalog", "purchase"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 88, speed: 82, premium: 86 },
    pack_ids: ["ecommerce-growth"],
    composition: ["ads-meta-catalog-v1", "landing-ecom-fashion-drop-v1", "seq-ecom-cart-abandon-3"],
  },
  {
    id: "funnel-saas-demo-nurture",
    name: "SaaS B2B · Demo → Nurture → Trial",
    kind: "funnel",
    service: "funnel",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["demo", "b2b", "linkedin"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 91, conversion: 85, speed: 86, premium: 90 },
    pack_ids: ["saas-b2b-growth"],
    composition: ["landing-saas-demo-v1", "seq-saas-b2b-nurture-5", "automation-b2b-demo-stage"],
  },
  {
    id: "funnel-coach-webinar-offer",
    name: "Coach · Webinar → Replay → Oferta",
    kind: "funnel",
    service: "funnel",
    sector: "coach",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["webinar", "infoproducto"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 86, conversion: 90, speed: 87, premium: 83 },
    composition: ["landing-coach-webinar-v1", "seq-coach-webinar-followup-4", "automation-webinar-tag"],
  },
  {
    id: "funnel-agency-audit-proposal",
    name: "Agencia · Auditoría → Propuesta → Onboarding",
    kind: "funnel",
    service: "funnel",
    sector: "agency",
    verticals: ["agency"],
    languages: ["es", "en"],
    tags: ["agency", "audit", "proposal"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 88, conversion: 84, speed: 88, premium: 89 },
    composition: ["landing-agency-audit-v1", "seq-agency-onboarding-4", "automation-agency-deal-stage"],
  },
];

export const AUTOMATION_RECIPE_PRESETS: NelvyonTemplateEntry[] = [
  {
    id: "automation-local-lead-crm",
    name: "Local · Formulario → CRM + email bienvenida",
    kind: "automation_recipe",
    service: "automation",
    sector: "all",
    verticals: ["local"],
    languages: ["es"],
    tags: ["form-submit", "crm", "email"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 90, conversion: 88, speed: 92, premium: 85 },
    composition: ["trigger:form_submit", "action:create_contact", "action:send_email:email-local-welcome-1", "action:create_deal"],
    pack_ids: ["local-business-growth"],
  },
  {
    id: "automation-b2b-demo-stage",
    name: "SaaS · Demo solicitada → etapa pipeline + nurture",
    kind: "automation_recipe",
    service: "automation",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["demo", "pipeline", "nurture"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 89, conversion: 86, speed: 91, premium: 88 },
    composition: ["trigger:form_submit", "action:move_deal:demo_requested", "action:enqueue_sequence:seq-saas-b2b-nurture-5"],
    pack_ids: ["saas-b2b-growth"],
  },
  {
    id: "automation-webinar-tag",
    name: "Webinar registro → tag + secuencia replay",
    kind: "automation_recipe",
    service: "automation",
    sector: "coach",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["webinar", "tag", "sequence"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 86, conversion: 87, speed: 93, premium: 82 },
    composition: ["trigger:form_submit", "action:tag:webinar_registered", "action:enqueue_sequence:seq-coach-webinar-followup-4"],
  },
  {
    id: "automation-agency-deal-stage",
    name: "Agencia · Lead audit → deal propuesta",
    kind: "automation_recipe",
    service: "automation",
    sector: "agency",
    verticals: ["agency"],
    languages: ["es"],
    tags: ["agency", "deal", "audit"],
    source: "nelvyon_native",
    nelvyon_owned: true,
    status: "active",
    scores: { quality: 87, conversion: 83, speed: 92, premium: 86 },
    composition: ["trigger:form_submit", "action:create_deal:audit_requested", "action:notify:operator"],
  },
];
