import type { NelvyonTemplateEntry, TemplateService } from "../types";

type LandingPreset = {
  id: string;
  name: string;
  service?: TemplateService;
  sector: NelvyonTemplateEntry["sector"];
  verticals: NelvyonTemplateEntry["verticals"];
  languages: NelvyonTemplateEntry["languages"];
  tags: string[];
  source: NelvyonTemplateEntry["source"];
  scores: NelvyonTemplateEntry["scores"];
  composition_blocks: string[];
  pack_ids?: string[];
  description?: string;
  preview_path?: string;
};

function landing(p: LandingPreset): NelvyonTemplateEntry {
  const { composition_blocks, service, ...rest } = p;
  return {
    ...rest,
    kind: "landing",
    service: service ?? "landing",
    composition: composition_blocks,
    nelvyon_owned: true,
    status: "active",
  };
}

/** First 18 native landing presets — sector × pattern. */
export const LANDING_PRESETS: NelvyonTemplateEntry[] = [
  landing({
    id: "landing-restaurant-reservas-v1",
    name: "Restaurante · Reservas",
    service: "landing",
    sector: "restaurant",
    verticals: ["local"],
    languages: ["es", "en"],
    tags: ["reservas", "menu", "mapa", "mobile-first"],
    source: "nelvyon_native",
    scores: { quality: 88, conversion: 85, speed: 82, premium: 86 },
    composition_blocks: ["hero:split-image", "menu:restaurant", "testimonials:cards-3", "map:local-business", "form:booking", "cta:banner-rounded"],
    pack_ids: ["local-business-growth"],
    description: "Hero + carta + reseñas + mapa + formulario reserva",
  }),
  landing({
    id: "landing-dental-cita-v1",
    name: "Clínica dental · Primera cita",
    service: "landing",
    sector: "dental",
    verticals: ["local"],
    languages: ["es"],
    tags: ["citas", "confianza", "seguro"],
    source: "nelvyon_native",
    scores: { quality: 90, conversion: 88, speed: 84, premium: 89 },
    composition_blocks: ["hero:center-gradient", "features:icon-grid", "team:cards", "faq:accordion", "form:booking", "cta:banner-rounded"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-legal-consulta-v1",
    name: "Despacho · Consulta legal",
    service: "landing",
    sector: "legal",
    verticals: ["local"],
    languages: ["es"],
    tags: ["abogado", "confianza", "lead"],
    source: "nelvyon_native",
    scores: { quality: 87, conversion: 82, speed: 86, premium: 88 },
    composition_blocks: ["hero:split-image", "logos:trust-bar", "testimonials:cards-3", "faq:accordion", "form:lead-capture"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-fitness-trial-v1",
    name: "Gimnasio · Clase de prueba",
    service: "landing",
    sector: "fitness",
    verticals: ["local"],
    languages: ["es", "en"],
    tags: ["gym", "trial", "cta-fuerte"],
    source: "nelvyon_native",
    scores: { quality: 86, conversion: 87, speed: 83, premium: 85 },
    composition_blocks: ["hero:video-bg", "stats:stats-4col", "pricing:three-tier", "form:lead-capture", "cta:banner-rounded"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-beauty-cita-v1",
    name: "Salón belleza · Reserva",
    service: "landing",
    sector: "beauty",
    verticals: ["local"],
    languages: ["es"],
    tags: ["salon", "spa", "reservas"],
    source: "nelvyon_native",
    scores: { quality: 88, conversion: 84, speed: 81, premium: 90 },
    composition_blocks: ["hero:split-image", "gallery:masonry", "testimonials:cards-3", "form:booking", "cta:banner-rounded"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-realestate-valoracion-v1",
    name: "Inmobiliaria · Valoración gratis",
    service: "landing",
    sector: "real_estate",
    verticals: ["local"],
    languages: ["es"],
    tags: ["valoracion", "lead", "propiedades"],
    source: "nelvyon_native",
    scores: { quality: 85, conversion: 86, speed: 84, premium: 87 },
    composition_blocks: ["hero:center-gradient", "features:icon-grid", "form:lead-capture", "testimonials:cards-3", "map:local-business"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-ecom-fashion-drop-v1",
    name: "Moda · Drop / colección",
    service: "landing",
    sector: "ecommerce_fashion",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["moda", "coleccion", "urgencia"],
    source: "nelvyon_native",
    scores: { quality: 89, conversion: 88, speed: 80, premium: 91 },
    composition_blocks: ["hero_3d:aceternity-glow", "product_3d:ecommerce-spotlight", "countdown:offer", "social_proof:stats-4col", "cta:banner-rounded"],
    pack_ids: ["ecommerce-growth"],
  }),
  landing({
    id: "landing-ecom-electronics-launch-v1",
    name: "Electrónica · Lanzamiento producto",
    service: "landing",
    sector: "ecommerce_electronics",
    verticals: ["ecommerce"],
    languages: ["es", "en"],
    tags: ["tech", "specs", "comparativa"],
    source: "nelvyon_native",
    scores: { quality: 88, conversion: 85, speed: 82, premium: 88 },
    composition_blocks: ["hero:split-image", "features:icon-grid", "comparison:before-after", "pricing:three-tier", "faq:accordion"],
    pack_ids: ["ecommerce-growth"],
  }),
  landing({
    id: "landing-ecom-food-subscription-v1",
    name: "Food · Suscripción / caja",
    service: "landing",
    sector: "ecommerce_food",
    verticals: ["ecommerce"],
    languages: ["es"],
    tags: ["food", "subscription", "d2c"],
    source: "nelvyon_native",
    scores: { quality: 87, conversion: 86, speed: 83, premium: 86 },
    composition_blocks: ["hero:center-gradient", "features:icon-grid", "testimonials:cards-3", "pricing:three-tier", "form:lead-capture"],
    pack_ids: ["ecommerce-growth"],
  }),
  landing({
    id: "landing-saas-demo-v1",
    name: "SaaS B2B · Solicitar demo",
    service: "landing",
    sector: "saas_b2b",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["demo", "b2b", "pipeline"],
    source: "nelvyon_native",
    scores: { quality: 91, conversion: 87, speed: 85, premium: 92 },
    composition_blocks: ["hero_3d:aceternity-glow", "logos:trust-bar", "features:icon-grid", "testimonials:cards-3", "pricing:three-tier", "form:lead-capture"],
    pack_ids: ["saas-b2b-growth"],
  }),
  landing({
    id: "landing-saas-trial-v1",
    name: "SaaS · Trial 14 días",
    service: "landing",
    sector: "saas_b2c",
    verticals: ["saas_b2b"],
    languages: ["es", "en"],
    tags: ["trial", "self-serve", "signup"],
    source: "nelvyon_native",
    scores: { quality: 90, conversion: 89, speed: 86, premium: 90 },
    composition_blocks: ["hero:center-gradient", "stats_3d:metrics-row", "pricing:three-tier", "faq:accordion", "cta:banner-rounded"],
    pack_ids: ["saas-b2b-growth"],
  }),
  landing({
    id: "landing-coach-webinar-v1",
    name: "Coach · Registro webinar",
    service: "landing",
    sector: "coach",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["webinar", "infoproducto", "squeeze"],
    source: "nelvyon_native",
    scores: { quality: 86, conversion: 90, speed: 88, premium: 84 },
    composition_blocks: ["hero:split-image", "video:embed", "testimonials:cards-3", "form:lead-capture", "countdown:offer"],
    pack_ids: ["saas-b2b-growth"],
  }),
  landing({
    id: "landing-agency-audit-v1",
    name: "Agencia · Auditoría gratis",
    service: "landing",
    sector: "agency",
    verticals: ["agency"],
    languages: ["es", "en"],
    tags: ["agencia", "lead-magnet", "audit"],
    source: "nelvyon_native",
    scores: { quality: 88, conversion: 85, speed: 87, premium: 89 },
    composition_blocks: ["hero_3d:aceternity-glow", "features:icon-grid", "logos:trust-bar", "form:lead-capture", "cta:banner-rounded"],
    pack_ids: ["saas-b2b-growth"],
  }),
  landing({
    id: "landing-infoproduct-launch-v1",
    name: "Infoproducto · Lanzamiento",
    service: "landing",
    sector: "infoproduct",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["lanzamiento", "curso", "urgencia"],
    source: "nelvyon_native",
    scores: { quality: 85, conversion: 91, speed: 84, premium: 83 },
    composition_blocks: ["hero:video-bg", "comparison:before-after", "pricing:three-tier", "countdown:offer", "faq:accordion"],
  }),
  landing({
    id: "landing-veterinary-cita-v1",
    name: "Veterinaria · Cita",
    service: "landing",
    sector: "veterinary",
    verticals: ["local"],
    languages: ["es"],
    tags: ["mascotas", "citas"],
    source: "nelvyon_native",
    scores: { quality: 86, conversion: 84, speed: 85, premium: 85 },
    composition_blocks: ["hero:split-image", "features:icon-grid", "form:booking", "map:local-business", "faq:accordion"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-solar-quote-v1",
    name: "Solar · Presupuesto",
    service: "landing",
    sector: "solar",
    verticals: ["local"],
    languages: ["es"],
    tags: ["solar", "lead", "calculadora"],
    source: "nelvyon_native",
    scores: { quality: 87, conversion: 88, speed: 83, premium: 86 },
    composition_blocks: ["hero:center-gradient", "stats:stats-4col", "comparison:before-after", "form:lead-capture", "testimonials:cards-3"],
    pack_ids: ["local-business-growth"],
  }),
  landing({
    id: "landing-hotel-booking-v1",
    name: "Hotel · Reserva directa",
    service: "landing",
    sector: "hotel",
    verticals: ["local"],
    languages: ["es", "en", "fr"],
    tags: ["hotel", "turismo", "booking"],
    source: "nelvyon_native",
    scores: { quality: 89, conversion: 86, speed: 81, premium: 92 },
    composition_blocks: ["hero:video-bg", "gallery:masonry", "pricing:three-tier", "form:booking", "map:local-business"],
  }),
  landing({
    id: "landing-course-enroll-v1",
    name: "Curso online · Matrícula",
    service: "landing",
    sector: "course",
    verticals: ["creator"],
    languages: ["es"],
    tags: ["lms", "curso", "matricula"],
    source: "nelvyon_native",
    scores: { quality: 87, conversion: 87, speed: 86, premium: 85 },
    composition_blocks: ["hero:split-image", "features:icon-grid", "testimonials:cards-3", "pricing:three-tier", "faq:accordion"],
  }),
];
