/**
 * Shared PDF label maps for SaaS quotes/invoices.
 *
 * Honest coverage: PARTIAL — label chrome is localized for es/en/fr/de/it/pt;
 * status badges, full legal text, and number/date formatting remain Spanish-leaning
 * defaults unless the caller passes a locale. Do NOT mark email/PDF FULL_VERIFIED.
 */

export type PdfLocale = "es" | "en" | "fr" | "de" | "it" | "pt";

export type InvoicePdfLabels = {
  documentTitle: string;
  date: string;
  dueDate: string;
  paidAt: string;
  description: string;
  quantity: string;
  unitPrice: string;
  total: string;
  subtotal: string;
  tax: (rate: number) => string;
  notes: string;
  generatedBy: (brand: string) => string;
  downloadHint: string;
};

export type QuotePdfLabels = {
  documentTitle: (number: string) => string;
  number: string;
  date: string;
  validUntil: string;
  description: string;
  quantity: string;
  unitPrice: string;
  subtotal: string;
  discount: (pct: number) => string;
  tax: (rate: number) => string;
  total: string;
  generatedBy: (agency: string, sig: string) => string;
};

const INVOICE_LABELS: Record<PdfLocale, InvoicePdfLabels> = {
  es: {
    documentTitle: "FACTURA",
    date: "Fecha",
    dueDate: "Vencimiento",
    paidAt: "Pagada",
    description: "Descripción",
    quantity: "Cant.",
    unitPrice: "Precio unit.",
    total: "Total",
    subtotal: "Subtotal",
    tax: (rate) => `IVA (${rate}%)`,
    notes: "Notas",
    generatedBy: (brand) => `${brand} · Generado por Nelvyon`,
    downloadHint: "Descargar PDF (Ctrl+P → Guardar como PDF)",
  },
  en: {
    documentTitle: "INVOICE",
    date: "Date",
    dueDate: "Due date",
    paidAt: "Paid",
    description: "Description",
    quantity: "Qty",
    unitPrice: "Unit price",
    total: "Total",
    subtotal: "Subtotal",
    tax: (rate) => `Tax (${rate}%)`,
    notes: "Notes",
    generatedBy: (brand) => `${brand} · Generated by Nelvyon`,
    downloadHint: "Download PDF (Ctrl+P → Save as PDF)",
  },
  fr: {
    documentTitle: "FACTURE",
    date: "Date",
    dueDate: "Échéance",
    paidAt: "Payée",
    description: "Description",
    quantity: "Qté",
    unitPrice: "Prix unit.",
    total: "Total",
    subtotal: "Sous-total",
    tax: (rate) => `TVA (${rate}%)`,
    notes: "Notes",
    generatedBy: (brand) => `${brand} · Généré par Nelvyon`,
    downloadHint: "Télécharger le PDF (Ctrl+P → Enregistrer au format PDF)",
  },
  de: {
    documentTitle: "RECHNUNG",
    date: "Datum",
    dueDate: "Fällig am",
    paidAt: "Bezahlt",
    description: "Beschreibung",
    quantity: "Menge",
    unitPrice: "Einzelpreis",
    total: "Gesamt",
    subtotal: "Zwischensumme",
    tax: (rate) => `MwSt. (${rate}%)`,
    notes: "Notizen",
    generatedBy: (brand) => `${brand} · Erstellt von Nelvyon`,
    downloadHint: "PDF herunterladen (Strg+P → Als PDF speichern)",
  },
  it: {
    documentTitle: "FATTURA",
    date: "Data",
    dueDate: "Scadenza",
    paidAt: "Pagata",
    description: "Descrizione",
    quantity: "Qtà",
    unitPrice: "Prezzo unit.",
    total: "Totale",
    subtotal: "Subtotale",
    tax: (rate) => `IVA (${rate}%)`,
    notes: "Note",
    generatedBy: (brand) => `${brand} · Generato da Nelvyon`,
    downloadHint: "Scarica PDF (Ctrl+P → Salva come PDF)",
  },
  pt: {
    documentTitle: "FATURA",
    date: "Data",
    dueDate: "Vencimento",
    paidAt: "Paga",
    description: "Descrição",
    quantity: "Qtd.",
    unitPrice: "Preço unit.",
    total: "Total",
    subtotal: "Subtotal",
    tax: (rate) => `IVA (${rate}%)`,
    notes: "Notas",
    generatedBy: (brand) => `${brand} · Gerado por Nelvyon`,
    downloadHint: "Descarregar PDF (Ctrl+P → Guardar como PDF)",
  },
};

const QUOTE_LABELS: Record<PdfLocale, QuotePdfLabels> = {
  es: {
    documentTitle: (n) => `Presupuesto ${n}`,
    number: "Nº",
    date: "Fecha",
    validUntil: "Válido hasta",
    description: "Descripción",
    quantity: "Cant.",
    unitPrice: "Precio unit.",
    subtotal: "Subtotal",
    discount: (pct) => `Descuento (${pct}%)`,
    tax: (rate) => `IVA (${rate}%)`,
    total: "TOTAL",
    generatedBy: (agency, sig) => `Generado por ${agency} · ref: ${sig}`,
  },
  en: {
    documentTitle: (n) => `Quote ${n}`,
    number: "No.",
    date: "Date",
    validUntil: "Valid until",
    description: "Description",
    quantity: "Qty",
    unitPrice: "Unit price",
    subtotal: "Subtotal",
    discount: (pct) => `Discount (${pct}%)`,
    tax: (rate) => `Tax (${rate}%)`,
    total: "TOTAL",
    generatedBy: (agency, sig) => `Generated by ${agency} · ref: ${sig}`,
  },
  fr: {
    documentTitle: (n) => `Devis ${n}`,
    number: "Nº",
    date: "Date",
    validUntil: "Valable jusqu'au",
    description: "Description",
    quantity: "Qté",
    unitPrice: "Prix unit.",
    subtotal: "Sous-total",
    discount: (pct) => `Remise (${pct}%)`,
    tax: (rate) => `TVA (${rate}%)`,
    total: "TOTAL",
    generatedBy: (agency, sig) => `Généré par ${agency} · réf: ${sig}`,
  },
  de: {
    documentTitle: (n) => `Angebot ${n}`,
    number: "Nr.",
    date: "Datum",
    validUntil: "Gültig bis",
    description: "Beschreibung",
    quantity: "Menge",
    unitPrice: "Einzelpreis",
    subtotal: "Zwischensumme",
    discount: (pct) => `Rabatt (${pct}%)`,
    tax: (rate) => `MwSt. (${rate}%)`,
    total: "GESAMT",
    generatedBy: (agency, sig) => `Erstellt von ${agency} · Ref: ${sig}`,
  },
  it: {
    documentTitle: (n) => `Preventivo ${n}`,
    number: "Nº",
    date: "Data",
    validUntil: "Valido fino al",
    description: "Descrizione",
    quantity: "Qtà",
    unitPrice: "Prezzo unit.",
    subtotal: "Subtotale",
    discount: (pct) => `Sconto (${pct}%)`,
    tax: (rate) => `IVA (${rate}%)`,
    total: "TOTALE",
    generatedBy: (agency, sig) => `Generato da ${agency} · rif: ${sig}`,
  },
  pt: {
    documentTitle: (n) => `Orçamento ${n}`,
    number: "Nº",
    date: "Data",
    validUntil: "Válido até",
    description: "Descrição",
    quantity: "Qtd.",
    unitPrice: "Preço unit.",
    subtotal: "Subtotal",
    discount: (pct) => `Desconto (${pct}%)`,
    tax: (rate) => `IVA (${rate}%)`,
    total: "TOTAL",
    generatedBy: (agency, sig) => `Gerado por ${agency} · ref: ${sig}`,
  },
};

export function resolvePdfLocale(locale?: string | null): PdfLocale {
  if (locale === "en" || locale === "fr" || locale === "de" || locale === "it" || locale === "pt") {
    return locale;
  }
  return "es";
}

export function getInvoicePdfLabels(locale?: string | null): InvoicePdfLabels {
  return INVOICE_LABELS[resolvePdfLocale(locale)];
}

export function getQuotePdfLabels(locale?: string | null): QuotePdfLabels {
  return QUOTE_LABELS[resolvePdfLocale(locale)];
}
