/** Phase E — sector profiles derived from docs/autonomous/sectors/*.md */

import type { AutonomousSector, SectorProfile } from "./types";

export const SECTOR_IDS: AutonomousSector[] = [
  // TOP 10
  "dental",
  "legal",
  "fitness",
  "beauty",
  "restaurant",
  "real_estate",
  "ecommerce",
  "solar",
  "coaching",
  "saas_b2b",
  // +10
  "veterinaria",
  "educacion",
  "turismo",
  "construccion",
  "automocion",
  "logistica",
  "seguros",
  "contabilidad",
  "hosteleria",
  "tecnologia",
];

const DOC_FILES: Record<AutonomousSector, string> = {
  dental: "DENTAL_AGENT.md",
  legal: "LEGAL_AGENT.md",
  fitness: "FITNESS_AGENT.md",
  beauty: "BEAUTY_AGENT.md",
  restaurant: "RESTAURANT_AGENT.md",
  real_estate: "REAL_ESTATE_AGENT.md",
  ecommerce: "ECOMMERCE_AGENT.md",
  solar: "SOLAR_AGENT.md",
  coaching: "COACHING_AGENT.md",
  saas_b2b: "SAAS_B2B_AGENT.md",
  veterinaria: "VETERINARIA_AGENT.md",
  educacion: "EDUCACION_AGENT.md",
  turismo: "TURISMO_AGENT.md",
  construccion: "CONSTRUCCION_AGENT.md",
  automocion: "AUTOMOCION_AGENT.md",
  logistica: "LOGISTICA_AGENT.md",
  seguros: "SEGUROS_AGENT.md",
  contabilidad: "CONTABILIDAD_AGENT.md",
  hosteleria: "HOSTELERIA_AGENT.md",
  tecnologia: "TECNOLOGIA_AGENT.md",
};

const base = (
  id: AutonomousSector,
  label: string,
  autonomy_score: number,
  sensitivity: SectorProfile["sensitivity"],
  regulated: boolean,
  ctx: SectorProfile["promptContext"],
): SectorProfile => ({
  id,
  label,
  doc_path: `docs/autonomous/sectors/${DOC_FILES[id]}`,
  autonomy_score,
  sensitivity,
  regulated,
  requires_legal_review: regulated || sensitivity === "high",
  escalate_operator_on_pass: regulated,
  promptContext: ctx,
});

export const SECTOR_REGISTRY: Record<AutonomousSector, SectorProfile> = {
  dental: base("dental", "Dentistas", 82, "high", true, {
    ideal_client: "Clínica dental 1–3 sedes, ticket medio €150–800, captación por Google/IG",
    primary_pains: [
      "Huecos en agenda y no-shows",
      "Pacientes preguntan precio/tratamiento por WhatsApp sin filtrar",
      "Web antigua sin CTA cita",
      "Poca reseña Google vs competencia",
    ],
    winning_offers: [
      "Primera visita / revisión gratuita",
      "Blanqueamiento pack verano",
      "Ortodoncia invisible consulta sin compromiso",
      "Urgencias dentales mismo día",
    ],
    landing_angle: "PAS: miedo dolor → solución sin dolor → CTA reservar cita única",
    seo_focus: ["dentista + ciudad", "implantes + zona", "ortodoncia invisible", "blanqueamiento dental"],
    google_ads_angle: "Search: tratamientos high-intent + extensión llamada + ubicación",
    meta_ads_angle: "Antes/después (sin claims médicos) + testimonios + lead form cita",
    chatbot_focus: "FAQs tratamientos, horarios, seguros, handoff recepción — sin diagnóstico ni precio exacto",
    automations: ["Recordatorio cita SMS", "Reseña Google post-visita", "Lead nurturing ortodoncia"],
    typical_objections: ["¿Duele?", "¿Cuánto cuesta?", "¿Aceptáis mi seguro?"],
    qa_focus: ["Disclaimer sanitario", "Sin diagnóstico chatbot", "Política privacidad RGPD", "CTA único cita"],
    templates: ["landing-cro-v2-health", "chatbot-dental-v1", "aceternity-clinic"],
    compliance_notes: [
      "No prometer resultados garantizados",
      "Revisión operador obligatoria antes de publicar",
      "Colegio/depósito legal según país",
    ],
  }),

  legal: base("legal", "Abogados", 75, "high", true, {
    ideal_client: "Despacho 2–15 abogados, especialidad clara (laboral, familia, penal, mercantil)",
    primary_pains: [
      "Leads de baja calidad",
      "Web genérica sin especialidad",
      "No diferenciación vs competencia",
      "Miedo cliente a coste inicial",
    ],
    winning_offers: [
      "Consulta inicial 30 min",
      "Guía gratuita del proceso (PDF)",
      "Honorarios transparentes por fase",
      "Videollamada confidencial",
    ],
    landing_angle: "Autoridad + especialidad + prueba social casos (anonimizados) + CTA consulta",
    seo_focus: ["abogado + especialidad + ciudad", "divorcio mutuo acuerdo", "despido improcedente"],
    google_ads_angle: "Search high-intent especialidad + call extension + formulario confidencial",
    meta_ads_angle: "Educación legal (carousel) + lead magnet guía + retargeting visitantes web",
    chatbot_focus: "Calificación caso, área legal, urgencia, captura contacto — sin asesoramiento jurídico",
    automations: ["Email secuencia post-consulta", "Recordatorio documentación", "CRM etapas caso"],
    typical_objections: ["¿Cuánto cuesta?", "¿Ganaré el caso?", "¿Cuánto tarda?"],
    qa_focus: ["Disclaimer no asesoramiento", "Sin promesa resultado", "RGPD datos sensibles", "Bar association rules"],
    templates: ["landing-cro-v4-trust", "chatbot-legal-v1", "proactiv-legal"],
    compliance_notes: [
      "ESCALATE_OPERATOR siempre tras QA",
      "Revisión abogado responsable antes de publicar",
      "No claims de % éxito",
    ],
  }),

  fitness: base("fitness", "Gimnasios", 88, "medium", false, {
    ideal_client: "Gimnasio o box CrossFit 200–2000 socios, zona urbana, ticket €30–80/mes",
    primary_pains: [
      "Baja conversión visita prueba",
      "Churn alto primeros 90 días",
      "Competencia low-cost",
      "Horarios punta saturados",
    ],
    winning_offers: [
      "Prueba gratuita 7 días",
      "Pack transformación 12 semanas",
      "Clase abierta fin de semana",
      "Sin permanencia primer mes",
    ],
    landing_angle: "Transformación + comunidad + prueba sin riesgo + urgencia plazas limitadas",
    seo_focus: ["gimnasio + barrio", "crossfit + ciudad", "clases dirigidas", "entrenador personal"],
    google_ads_angle: "Search gimnasio cerca + promo prueba + extensiones ubicación",
    meta_ads_angle: "Video entrenamientos + UGC miembros + lead form prueba",
    chatbot_focus: "Horarios, precios orientativos, clases, tour instalaciones",
    automations: ["Onboarding socio email", "Recordatorio clase reservada", "Win-back churn"],
    typical_objections: ["¿Hay permanencia?", "¿Está lleno a mi hora?", "¿Incluye nutrición?"],
    qa_focus: ["CTA prueba claro", "Precios visibles o rango", "Fotos reales instalaciones"],
    templates: ["landing-cro-v1-energy", "chatbot-fitness-v1", "foxtrot-gym"],
    compliance_notes: ["Evitar claims pérdida peso garantizada"],
  }),

  beauty: base("beauty", "Clínicas estéticas", 78, "high", true, {
    ideal_client: "Clínica estética médica o centro belleza premium, ticket €80–500",
    primary_pains: [
      "Confianza y miedo a resultados artificiales",
      "Comparación precios con low-cost",
      "Leads IG sin cualificar",
      "Poca diferenciación médico vs esteticista",
    ],
    winning_offers: [
      "Valoración gratuita",
      "Pack novia / evento",
      "Primera sesión láser promoción",
      "Financiación sin intereses",
    ],
    landing_angle: "Confianza médica + antes/después moderado + testimonios + CTA valoración",
    seo_focus: ["clínica estética + ciudad", "botox + zona", "depilación láser"],
    google_ads_angle: "Search tratamientos + ubicación + llamada",
    meta_ads_angle: "Reels resultados + stories promoción + DM automation",
    chatbot_focus: "Tratamientos, contraindicaciones generales, cita valoración — sin diagnóstico",
    automations: ["Recordatorio cita", "Post-tratamiento cuidados", "Reseña Google"],
    typical_objections: ["¿Es seguro?", "¿Cuántas sesiones?", "¿Duele?"],
    qa_focus: ["Disclaimer médico", "Sin antes/después engañoso", "RGPD imágenes"],
    templates: ["landing-cro-v2-health", "chatbot-beauty-v1"],
    compliance_notes: ["Revisión operador + médico responsable", "AEMPS/claims según tratamiento"],
  }),

  restaurant: base("restaurant", "Restaurantes", 90, "low", false, {
    ideal_client: "Restaurante independiente o cadena 1–5 locales, ticket €25–60, reservas online",
    primary_pains: [
      "Mesas vacías entre semana",
      "Dependencia delivery apps",
      "Poca lista email propia",
      "Reseñas negativas sin respuesta",
    ],
    winning_offers: [
      "Menú degustación temporada",
      "Happy hour martes-jueves",
      "Reserva directa -10% vs apps",
      "Evento privado grupos",
    ],
    landing_angle: "Experiencia sensorial + carta destacada + reserva directa + ubicación",
    seo_focus: ["restaurante + tipo cocina + ciudad", "menú del día", "reservar mesa"],
    google_ads_angle: "Search marca + cocina + local + extensiones ubicación",
    meta_ads_angle: "Fotos platos + stories eventos + reserva IG",
    chatbot_focus: "Horarios, reservas, alérgenos generales, eventos privados",
    automations: ["Confirmación reserva WhatsApp", "Email cumpleaños", "Push menú semanal"],
    typical_objections: ["¿Hay parking?", "¿Menú niños?", "¿Grupos grandes?"],
    qa_focus: ["Menú legible mobile", "Botón reserva above fold", "Mapa y horarios"],
    templates: ["landing-cro-v3-local", "chatbot-restaurant-v1"],
    compliance_notes: ["Alérgenos según normativa local"],
  }),

  real_estate: base("real_estate", "Inmobiliarias", 85, "medium", false, {
    ideal_client: "Agencia 3–20 agentes, foco residencial o inversión, zona definida",
    primary_pains: [
      "Leads portalgenéricos baja calidad",
      "Poca captación vendedores (mandatos)",
      "Web con stock desactualizado",
      "Seguimiento manual leads",
    ],
    winning_offers: [
      "Valoración gratuita vivienda",
      "Tour virtual 360°",
      "Pack vendedor (foto + staging + anuncio)",
      "Guía comprador primera vivienda",
    ],
    landing_angle: "Valoración gratis mandato + propiedades destacadas + prueba social ventas",
    seo_focus: ["inmobiliaria + barrio", "pisos en venta + zona", "valorar piso"],
    google_ads_angle: "Search valoración + comprar piso + remarketing listados",
    meta_ads_angle: "Carrusel propiedades + video tour + lead form valoración",
    chatbot_focus: "Cualificación comprador/vendedor, presupuesto, zona, visita",
    automations: ["Alertas nuevas propiedades", "Secuencia post-visita", "CRM etapas deal"],
    typical_objections: ["¿Cuánto tarda en vender?", "¿Cuál es vuestra comisión?", "¿Exclusiva?"],
    qa_focus: ["Referencias catastrales no inventadas", "CTA valoración/visita", "Filtros búsqueda"],
    templates: ["landing-cro-v5-listings", "chatbot-realestate-v1"],
    compliance_notes: ["Ley vivienda / publicidad precio según país"],
  }),

  ecommerce: base("ecommerce", "Ecommerce", 86, "medium", false, {
    ideal_client: "Tienda online D2C €10k–500k/mes, catálogo <500 SKU, Shopify/Woo",
    primary_pains: [
      "Abandono carrito alto",
      "CAC Meta subiendo",
      "Poca repetición compra",
      "SEO producto débil",
    ],
    winning_offers: [
      "Envío gratis umbral",
      "Pack ahorro 3x2",
      "Primera compra -15%",
      "Suscripción replenishment",
    ],
    landing_angle: "Beneficio producto hero + prueba social + urgencia stock + CTA compra",
    seo_focus: ["categoría + producto", "comprar + keyword", "guías comparativa"],
    google_ads_angle: "Shopping + PMax + remarketing carrito",
    meta_ads_angle: "UGC unboxing + DPA catálogo + oferta limitada",
    chatbot_focus: "Estado pedido, envíos, devoluciones, tallas — sin inventar stock",
    automations: ["Abandono carrito email/SMS", "Post-compra review", "Win-back 90d"],
    typical_objections: ["¿Cuándo llega?", "¿Devolución gratis?", "¿Es original?"],
    qa_focus: ["Política devoluciones visible", "Checkout mobile", "Schema product"],
    templates: ["landing-cro-v6-product", "chatbot-ecom-v1", "store-aceternity"],
    compliance_notes: ["Precios con IVA", "Cookies y RGPD checkout"],
  }),

  solar: base("solar", "Energía solar", 87, "medium", true, {
    ideal_client: "Instalador solar residencial/comercial, 5–50 empleados, ticket €5k–25k",
    primary_pains: [
      "Leads curiosos sin tejado viable",
      "Desconfianza subsidios/ROI",
      "Ciclo venta largo",
      "Competencia precio por kW",
    ],
    winning_offers: [
      "Estudio gratuito consumo",
      "Calculadora ahorro (orientativa)",
      "Instalación llave en mano",
      "Financiación 0% inicial",
    ],
    landing_angle: "Ahorro factura + sostenibilidad + estudio gratis + prueba social instalaciones",
    seo_focus: ["placas solares + ciudad", "autoconsumo", "instalador solar + provincia"],
    google_ads_angle: "Search placas solares + estudio gratis + formulario largo cualificado",
    meta_ads_angle: "Video instalación + testimonio ahorro + lead form",
    chatbot_focus: "Cualificación tejado/consumo, zona, tipo vivienda — sin prometer subsidio exacto",
    automations: ["Secuencia educativa autoconsumo", "Recordatorio visita técnica", "CRM pipeline solar"],
    typical_objections: ["¿Cuánto ahorro?", "¿Subvención?", "¿Cuánto tarda amortizar?"],
    qa_focus: ["Disclaimer ROI orientativo", "Sin prometer ayudas específicas sin fecha", "CTA estudio"],
    templates: ["landing-cro-v1-energy", "chatbot-solar-v1"],
    compliance_notes: ["Revisión operador si claims ahorro %", "Normativa sector eléctrico"],
  }),

  coaching: base("coaching", "Coaches", 89, "low", false, {
    ideal_client: "Coach negocios/vida online, facturación €5k–50k/mes, programa flagship",
    primary_pains: [
      "Dependencia referrals",
      "Web personal brand débil",
      "No nutrición leads webinar",
      "Objeción precio programa",
    ],
    winning_offers: [
      "Sesión descubrimiento gratuita",
      "Masterclass lead magnet",
      "Programa 90 días transformación",
      "Comunidad / membership",
    ],
    landing_angle: "Historia transformación + framework propio + testimonios + CTA llamada",
    seo_focus: ["coach + nicho", "mentor empresas", "programa liderazgo"],
    google_ads_angle: "Search coach nicho + remarketing contenido",
    meta_ads_angle: "Video valor + webinar registro + retargeting",
    chatbot_focus: "Calificación fit, objetivos, agenda llamada",
    automations: ["Secuencia post-webinar", "Recordatorio llamada", "Onboarding programa"],
    typical_objections: ["¿Funciona para mí?", "¿Cuánto tiempo?", "¿Precio?"],
    qa_focus: ["Testimonios con disclaimer resultados individuales", "CTA llamada único"],
    templates: ["landing-cro-v4-trust", "chatbot-coaching-v1", "productized-agency"],
    compliance_notes: ["No ingresos garantizados"],
  }),

  saas_b2b: base("saas_b2b", "SaaS/B2B", 91, "low", false, {
    ideal_client: "SaaS B2B SMB €20k–2M ARR, ciclo venta 2–8 semanas, demo-led",
    primary_pains: [
      "Tráfico sin ICP fit",
      "Demo no cualificada",
      "Mensaje feature vs outcome",
      "Churn onboarding",
    ],
    winning_offers: [
      "Trial 14 días",
      "Demo personalizada",
      "ROI calculator",
      "Piloto 30 días enterprise",
    ],
    landing_angle: "Outcome + ICP específico + logos + CTA demo/trial único",
    seo_focus: ["software + problema", "alternativa + competidor", "integración + herramienta"],
    google_ads_angle: "Search high-intent problema + competitor + remarketing",
    meta_ads_angle: "Carousel features→benefits + lead form demo + retargeting",
    chatbot_focus: "ICP calificación, use case, integraciones, agenda demo",
    automations: ["PLG onboarding email", "PQL alert ventas", "Nurture caso de uso"],
    typical_objections: ["¿Integra con X?", "¿Precio por usuario?", "¿Seguridad SOC2?"],
    qa_focus: ["CTA demo claro", "Comparativa honesta", "Security page link"],
    templates: ["landing-cro-v6-saas", "chatbot-saas-v1", "simplistic-saas"],
    compliance_notes: ["Claims SOC2 solo si certificado"],
  }),
  veterinaria: base("veterinaria", "Clínicas veterinarias", 84, "medium", false, {
    ideal_client: "Clínica veterinaria 1–3 veterinarios, ticket €60–300, zona urbana/residencial",
    primary_pains: ["Huecos en agenda", "Urgencias no planificadas", "Competencia grandes cadenas", "Poca fidelización"],
    winning_offers: ["Primera revisión cachorros/gatitos gratis", "Plan de salud anual", "Urgencias 24h", "Pack vacunación completo"],
    landing_angle: "Confianza + amor por los animales + cita rápida + prueba social testimonios",
    seo_focus: ["veterinario + ciudad", "clínica veterinaria + barrio", "urgencias veterinarias"],
    google_ads_angle: "Search urgencias vet + vacunación + cita online",
    meta_ads_angle: "Fotos animales + pack salud + lead form cita",
    chatbot_focus: "Síntomas generales, urgencias, citas, precios orientativos — sin diagnóstico",
    automations: ["Recordatorio vacunación anual", "Cumpleaños mascota", "Post-consulta cuidados"],
    typical_objections: ["¿Cuánto cuesta?", "¿Atienden urgencias?", "¿Tienen especialista?"],
    qa_focus: ["Disclaimer sin diagnóstico", "CTA cita claro", "Horarios urgencias visibles"],
    templates: ["landing-cro-v2-health", "chatbot-vet-v1"],
    compliance_notes: ["Sin diagnóstico online", "Colegio veterinarios según CCAA"],
  }),

  educacion: base("educacion", "Academias y centros educativos", 87, "low", false, {
    ideal_client: "Academia idiomas/oposiciones/formación, 50–500 alumnos, ticket €80–400/mes",
    primary_pains: ["Estacionalidad alta en septiembre", "Competencia online", "Retención alumnos", "Poca visibilidad local"],
    winning_offers: ["Clase de prueba gratuita", "Beca primeros 3 alumnos", "Garantía superación o devolvemos", "Pack familia"],
    landing_angle: "Resultado concreto + metodología diferenciadora + testimonios éxito + CTA prueba",
    seo_focus: ["academia + idioma/materia + ciudad", "clases particulares + zona", "preparar oposiciones"],
    google_ads_angle: "Search matriculación + prueba gratis + extensiones ubicación",
    meta_ads_angle: "Testimonios alumnos + resultados (notas/certificados) + lead form prueba",
    chatbot_focus: "Horarios, precios, niveles, prueba gratuita — sin comprometer plaza sin pago",
    automations: ["Secuencia onboarding alumno", "Recordatorio examen", "Renovación matrícula"],
    typical_objections: ["¿Qué nivel necesito?", "¿Hay grupo online?", "¿Cuánto tarda?"],
    qa_focus: ["CTA prueba gratuita claro", "Niveles y precios visibles", "Testimonios reales"],
    templates: ["landing-cro-v4-trust", "chatbot-edu-v1"],
    compliance_notes: ["Garantías por escrito si se ofrecen", "LOPD datos menores"],
  }),

  turismo: base("turismo", "Turismo y alojamiento", 85, "low", false, {
    ideal_client: "Hotel boutique / apartamentos turísticos 5–50 habitaciones, ticket €80–300/noche",
    primary_pains: ["Dependencia OTAs (Booking/Airbnb)", "Poca reserva directa", "Estacionalidad", "Reviews negativas"],
    winning_offers: ["Reserva directa -10% + desayuno", "Pack romántico / aventura", "Late checkout gratis", "Guía destino exclusiva"],
    landing_angle: "Experiencia única + reserva directa sin comisión + fotos aspiracionales + urgencia disponibilidad",
    seo_focus: ["hotel + ciudad/zona", "apartamentos turísticos + destino", "alojamiento + tipo viaje"],
    google_ads_angle: "Search reserva hotel + destino + remarketing visitantes abandonados",
    meta_ads_angle: "Video experiencias + fotos habitaciones + oferta temporada + remarketing",
    chatbot_focus: "Disponibilidad, precios, servicios, parking, desayuno — sin reservar sin pago",
    automations: ["Confirmación reserva + pre-checkin", "Post-estancia review", "Oferta repeat guest"],
    typical_objections: ["¿Más barato en Booking?", "¿Hay parking?", "¿Se puede anular?"],
    qa_focus: ["Política cancelación visible", "Fotos reales", "CTA reserva directa"],
    templates: ["landing-cro-v3-local", "chatbot-hotel-v1"],
    compliance_notes: ["Impuestos turísticos según municipio", "Registro viajeros según normativa"],
  }),

  construccion: base("construccion", "Construcción y reformas", 83, "medium", false, {
    ideal_client: "Empresa reformas / constructora local, ticket €5k–100k, zona ciudad",
    primary_pains: ["Leads con presupuesto irreal", "Comparación precio sin calidad", "Obra parada = coste", "Poca confianza online"],
    winning_offers: ["Presupuesto sin compromiso en 48h", "Visita técnica gratuita", "Garantía obra 2 años", "Financiación obra"],
    landing_angle: "Confianza portfolio + prueba social antes/después + proceso claro + CTA presupuesto",
    seo_focus: ["reformas + ciudad", "empresa construcción + zona", "reformar cocina/baño + ciudad"],
    google_ads_angle: "Search reformas + presupuesto + zona + extensión llamada",
    meta_ads_angle: "Antes/después proyectos + video obra + lead form presupuesto",
    chatbot_focus: "Tipo de obra, superficie, zona, captura datos para visita — sin presupuesto exacto sin visita",
    automations: ["Secuencia post-presupuesto", "Recordatorio aceptación", "Post-obra testimonios"],
    typical_objections: ["¿Cuánto cuesta?", "¿Cuánto tarda?", "¿Tenéis referencias?"],
    qa_focus: ["Portfolio real", "CTA presupuesto único", "Licencias/seguros visibles"],
    templates: ["landing-cro-v5-listings", "chatbot-const-v1"],
    compliance_notes: ["Licencias de obra según municipio", "Seguro RC obligatorio"],
  }),

  automocion: base("automocion", "Automoción", 86, "medium", false, {
    ideal_client: "Concesionario o taller mecánico, ticket €200–30k, zona definida",
    primary_pains: ["Leads online de baja calidad", "Comparación de precio puro", "Ciclo decisión largo", "Poca fidelización post-venta"],
    winning_offers: ["Tasación gratuita tu vehículo", "Revisión pre-ITV gratis", "Financiación 0% 12 meses", "Garantía extendida"],
    landing_angle: "Confianza local + stock real + oferta financiación + CTA test drive / cita taller",
    seo_focus: ["concesionario + marca + ciudad", "taller mecánico + zona", "comprar coche usado + ciudad"],
    google_ads_angle: "Search marca + modelo + concesionario + ubicación",
    meta_ads_angle: "Video stock + oferta financiación + lead form test drive",
    chatbot_focus: "Stock disponible, financiación, cita taller, tasación — sin precio definitivo sin peritaje",
    automations: ["Seguimiento test drive", "Recordatorio ITV/revisión", "Oferta aniversario compra"],
    typical_objections: ["¿Cuánto me dais por el mío?", "¿Hay más barato?", "¿Cómo es la financiación?"],
    qa_focus: ["Stock real (no inventado)", "Precios con impuestos", "CTA test drive o cita"],
    templates: ["landing-cro-v6-product", "chatbot-auto-v1"],
    compliance_notes: ["Precios con IVA según normativa", "Km reales en usados"],
  }),

  logistica: base("logistica", "Logística y transporte", 82, "medium", false, {
    ideal_client: "Empresa transporte/mensajería local o nacional, ticket €500–50k/mes B2B",
    primary_pains: ["Competencia precio por palé/kg", "Incidencias y reclamaciones", "Captación B2B lenta", "Sin diferenciación de servicio"],
    winning_offers: ["Cotización en 2h", "Prueba sin compromiso 1 envío", "SLA entrega garantizado", "Tracking en tiempo real"],
    landing_angle: "Fiabilidad + SLA claro + prueba social clientes B2B + CTA cotización rápida",
    seo_focus: ["empresa transporte + ciudad", "servicio mensajería B2B", "logística e-commerce"],
    google_ads_angle: "Search transporte + zona + cotización + extensión llamada directa",
    meta_ads_angle: "Infografía tiempos entrega + testimonios empresas + lead form cotización",
    chatbot_focus: "Tipo envío, peso, destino, plazo, captura datos — sin precio sin peso/dimensiones",
    automations: ["Seguimiento cotización no aceptada", "Alerta cliente incidencia", "Renovación contrato anual"],
    typical_objections: ["¿Cuánto por palé?", "¿Qué pasa si se pierde?", "¿Hay seguro?"],
    qa_focus: ["SLA específico", "Seguro transporte visible", "CTA cotización"],
    templates: ["landing-cro-v4-trust", "chatbot-logistics-v1"],
    compliance_notes: ["CMR / documentación transporte", "Seguros obligatorios"],
  }),

  seguros: base("seguros", "Seguros y corredurías", 79, "high", true, {
    ideal_client: "Correduría 1–20 agentes, seguros multirramo, captación digital incipiente",
    primary_pains: ["Comparadores precio puro", "Lead frío sin educación producto", "Retención al vencimiento", "Diferenciación vs banco-seguros"],
    winning_offers: ["Comparativa gratuita sin compromiso", "Consultoría riesgos empresa", "Descuento multiproducto", "Asistente 24h siniestros"],
    landing_angle: "Confianza + asesoramiento personalizado + comparativa honesta + CTA comparar gratis",
    seo_focus: ["correduría seguros + ciudad", "seguro + ramo + barato", "comparar seguros empresas"],
    google_ads_angle: "Search seguro + tipo + ciudad + comparativa + extensión llamada",
    meta_ads_angle: "Educación ramos (carousel) + lead form comparativa + retargeting",
    chatbot_focus: "Tipo seguro, cobertura, vehículo/propiedad, presupuesto — sin compromiso precio sin datos",
    automations: ["Seguimiento presupuesto no aceptado", "Aviso vencimiento póliza", "Felicitación renovación"],
    typical_objections: ["¿Cuánto cuesta?", "¿Qué cubre exactamente?", "¿Por qué no directo?"],
    qa_focus: ["Disclaimer sin asesoramiento vinculante", "DGS registro visible", "CTA comparativa"],
    templates: ["landing-cro-v4-trust", "chatbot-insurance-v1"],
    compliance_notes: ["DGS registro mediadores", "RGPD datos financieros", "ESCALATE_OPERATOR siempre"],
  }),

  contabilidad: base("contabilidad", "Asesorías y gestoría", 83, "medium", true, {
    ideal_client: "Asesoría fiscal-laboral 1–10 asesores, PYMEs cliente, zona geográfica definida",
    primary_pains: ["Captación depende de referidos", "Competencia precios low-cost online", "Retención en épocas bajas", "Digitalización cliente"],
    winning_offers: ["Primera consulta fiscal gratuita", "Pack autónomo completo €X/mes", "Revisión renta gratuita", "Alta empresa en 24h"],
    landing_angle: "Tranquilidad fiscal + precio claro + tecnología + CTA consulta gratuita",
    seo_focus: ["asesoría fiscal + ciudad", "gestoría pymes + zona", "declaración renta + ciudad"],
    google_ads_angle: "Search asesoría + tipo servicio + ciudad + época fiscal",
    meta_ads_angle: "Contenido fiscal educativo + lead magnet guía + lead form consulta",
    chatbot_focus: "Tipo cliente (autónomo/empresa), necesidades, captura contacto — sin asesoramiento vinculante",
    automations: ["Recordatorio declaraciones trimestrales", "Aviso campaña renta", "Onboarding cliente nuevo"],
    typical_objections: ["¿Cuánto cobráis?", "¿Qué incluye?", "¿Online o presencial?"],
    qa_focus: ["Sin asesoramiento fiscal vinculante", "REGA/colegio visible", "CTA consulta"],
    templates: ["landing-cro-v4-trust", "chatbot-asesor-v1"],
    compliance_notes: ["Sin asesoramiento fiscal concreto sin contrato", "REGA inscripción"],
  }),

  hosteleria: base("hosteleria", "Hoteles y hostelería", 86, "low", false, {
    ideal_client: "Hotel 3–5 estrellas 20–200 habitaciones, mix leisure/business, ciudad o resort",
    primary_pains: ["RevPAR bajo en temporada baja", "Dependencia OTAs", "F&B infrautilizado", "MICE no captado online"],
    winning_offers: ["Tarifa directa exclusiva", "Pack spa + habitación", "Reuniones con catering", "Early check-in gratis"],
    landing_angle: "Experiencia + exclusividad reserva directa + congresos/eventos + CTA reserva o RFP",
    seo_focus: ["hotel + ciudad + tipo", "reuniones y eventos + ciudad", "spa hotel + destino"],
    google_ads_angle: "Search hotel + ciudad + tipo + remarketing abandon",
    meta_ads_angle: "Video instalaciones + packs especiales + lead MICE form",
    chatbot_focus: "Disponibilidad, tarifas, eventos, servicios F&B — sin reservar sin motor",
    automations: ["Pre-arrival upsell", "Post-stay review NPS", "Oferta MICE post-visita"],
    typical_objections: ["¿Más barato en Booking?", "¿Hay salas para reuniones?", "¿Incluye parking?"],
    qa_focus: ["Paridad tarifaria con OTAs", "CTA reserva directa con ventaja", "Mapa ubicación"],
    templates: ["landing-cro-v3-local", "chatbot-hotel-v1"],
    compliance_notes: ["Impuestos estancia según municipio", "Normativa MICE según recinto"],
  }),

  tecnologia: base("tecnologia", "Servicios tecnológicos", 90, "low", false, {
    ideal_client: "Agencia desarrollo / IT services / consultora tech, ticket €3k–200k proyecto/retainer",
    primary_pains: ["Ciclo venta largo", "Comparación precio por hora", "Diferenciación vs offshoring", "Propuesta técnica vs negocio"],
    winning_offers: ["Auditoría técnica gratuita", "MVP en 4 semanas", "Retainer flexible mensual", "Garantía código + soporte 90d"],
    landing_angle: "Outcome de negocio (no tecnología) + portfolio + proceso ágil + CTA auditoría/call",
    seo_focus: ["agencia desarrollo + stack", "empresa IT + ciudad", "consultora tecnológica + sector"],
    google_ads_angle: "Search stack + desarrollo + ciudad + remarketing contenido técnico",
    meta_ads_angle: "Casos de éxito (negocio) + video proceso + lead form auditoría",
    chatbot_focus: "Stack, tipo proyecto, plazo, presupuesto orientativo — sin propuesta sin discovery",
    automations: ["Secuencia post-auditoría", "Nurture técnico mensual", "Alert PM milestone"],
    typical_objections: ["¿Por qué no India?", "¿Cuánto cuesta por hora?", "¿Tenéis experiencia en X?"],
    qa_focus: ["Portfolio real (demos o capturas)", "Stack honest", "CTA auditoría o call"],
    templates: ["landing-cro-v6-saas", "chatbot-tech-v1"],
    compliance_notes: ["NDA en propuesta técnica si datos sensibles", "GDPR en apps que manejan datos"],
  }),
};

export function getSectorProfile(sector: AutonomousSector): SectorProfile {
  return SECTOR_REGISTRY[sector];
}
