-- Roles del lado web. PARA CERTIFICACION — no aplicar en produccion.
--
-- DE DONDE SALEN LOS PRIVILEGIOS
-- -------------------------------
-- Del USO REAL medido en el codigo de runtime, no del catalogo. Conceder por
-- catalogo seria conceder lo que ya hay, que es exactamente lo que se quiere
-- reducir. Una tabla que el runtime no toca, no aparece aqui: son 225 de 710,
-- casi un tercio de la superficie, que estos roles simplemente no ven.
--
-- POR QUE LA REDUCCION DE TABLAS ES LO SECUNDARIO
-- ------------------------------------------------
-- Se intento repartir las tablas entre «runtime de peticiones» y «crons» por la
-- ruta del fichero. No funciona, y conviene decir por que en vez de presentar un
-- reparto que no separa nada: el SQL no vive en las rutas, vive en los servicios
-- de dominio, y los crons llaman A LOS MISMOS SERVICIOS. Cualquier corte por
-- fichero da practicamente el mismo conjunto para los dos.
--
-- La ganancia de seguridad de este cambio NO es table-level. Es que
-- `nelvyon_web_app` deja de saltarse RLS: hoy `postgres` es superusuario y las
-- 1.763 politicas no le aplican; con este rol pasan a decidir fila a fila. La
-- reduccion de 710 a 485 tablas es real pero es la parte pequeña.
--
-- LOS DOS ROLES
-- -------------
--   nelvyon_web_app    trafico normal.  NOBYPASSRLS -> las politicas deciden.
--   nelvyon_web_jobs   crons y plano platform. Necesita trabajar entre
--                      inquilinos, asi que SI lleva BYPASSRLS — y por tanto su
--                      aislamiento depende del `WHERE` explicito de cada
--                      consulta, exactamente el mismo contrato que
--                      `nelvyon_jobs` en el lado Python. Se escribe aqui para
--                      que nadie lo confunda con «otro rol seguro».
--
-- Ninguno de los dos es superusuario, ninguno crea objetos, ninguno hereda de
-- otro rol, y ninguno recibe TRUNCATE, REFERENCES ni TRIGGER.
--
-- QUE IMPIDE QUE UNA PETICION USE EL ROL PRIVILEGIADO
-- ----------------------------------------------------
-- No es una convencion: `DbClient` lee `DATABASE_URL` y NUNCA
-- `NELVYON_WEB_JOBS_DATABASE_URL`. Una ruta normal no tiene forma de alcanzar
-- esa conexion, y hay una prueba que lo comprueba
-- (`test_el_runtime_de_peticiones_no_alcanza_la_conexion_privilegiada`).

-- nelvyon_web_app: trafico normal de peticiones; las politicas RLS DECIDEN
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nelvyon_web_app') THEN
    CREATE ROLE nelvyon_web_app LOGIN PASSWORD 'cambiar_en_el_cutover'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  ELSE
    ALTER ROLE nelvyon_web_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END $$;
GRANT USAGE ON SCHEMA public TO nelvyon_web_app;
REVOKE CREATE ON SCHEMA public FROM nelvyon_web_app;   -- el runtime no crea objetos

-- nelvyon_web_jobs: crons y plano platform; aisla por WHERE explicito, no por RLS
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nelvyon_web_jobs') THEN
    CREATE ROLE nelvyon_web_jobs LOGIN PASSWORD 'cambiar_en_el_cutover'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
  ELSE
    ALTER ROLE nelvyon_web_jobs NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
  END IF;
END $$;
GRANT USAGE ON SCHEMA public TO nelvyon_web_jobs;
REVOKE CREATE ON SCHEMA public FROM nelvyon_web_jobs;   -- el runtime no crea objetos

-- ── Privilegios por tabla: 485 tablas, medidas del codigo ──
-- nelvyon_web_app
GRANT SELECT ON public._migrations TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.ab_experiments TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ab_tests TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.ab_variants TO nelvyon_web_app;
GRANT INSERT ON public.admin_metrics_cache TO nelvyon_web_app;
GRANT INSERT ON public.ads_results TO nelvyon_web_app;
GRANT INSERT ON public.affiliate_clicks TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.affiliate_conversions TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.affiliate_profiles TO nelvyon_web_app;
GRANT INSERT ON public.agenciasmarketing_results TO nelvyon_web_app;
GRANT INSERT ON public.agencycert_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.agent_feedback TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.agent_outcomes TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.agent_quality_scores TO nelvyon_web_app;
GRANT INSERT ON public.animacion_results TO nelvyon_web_app;
GRANT INSERT ON public.antigeneric_results TO nelvyon_web_app;
GRANT SELECT ON public.api_key_usage_daily TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.api_keys TO nelvyon_web_app;
GRANT INSERT ON public.apollo_results TO nelvyon_web_app;
GRANT INSERT ON public.appbuilderwhitelabel_results TO nelvyon_web_app;
GRANT INSERT ON public.arquitectura_results TO nelvyon_web_app;
GRANT INSERT ON public.artenft_results TO nelvyon_web_app;
GRANT INSERT ON public.attribution_reports TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.attribution_touchpoints TO nelvyon_web_app;
GRANT INSERT ON public.audiovisual_results TO nelvyon_web_app;
GRANT INSERT ON public.audit_log TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.audit_logs TO nelvyon_web_app;
GRANT INSERT ON public.autoprocesos_results TO nelvyon_web_app;
GRANT INSERT ON public.b2b_results TO nelvyon_web_app;
GRANT INSERT ON public.backupdisasterrecovery_results TO nelvyon_web_app;
GRANT INSERT ON public.badges_results TO nelvyon_web_app;
GRANT INSERT ON public.billing_results TO nelvyon_web_app;
GRANT INSERT ON public.bingads_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.booking_availability TO nelvyon_web_app;
GRANT INSERT ON public.bookingcalendario_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.bookings TO nelvyon_web_app;
GRANT INSERT ON public.branding_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.calendar_events TO nelvyon_web_app;
GRANT INSERT ON public.cdp_results TO nelvyon_web_app;
GRANT SELECT ON public.changelog_entries TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.chatbot_configs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.chatbot_conversations TO nelvyon_web_app;
GRANT INSERT ON public.chatwidget_results TO nelvyon_web_app;
GRANT INSERT ON public.churn_results TO nelvyon_web_app;
GRANT INSERT ON public.ciberseguridad_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.client_briefings TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.client_profiles TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.cold_email_campaigns TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.cold_email_prospects TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.communities TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.community_posts TO nelvyon_web_app;
GRANT INSERT ON public.community_results TO nelvyon_web_app;
GRANT INSERT ON public.comparator_results TO nelvyon_web_app;
GRANT INSERT ON public.competitive_rt_results TO nelvyon_web_app;
GRANT INSERT ON public.compliance_results TO nelvyon_web_app;
GRANT INSERT ON public.consultoria_results TO nelvyon_web_app;
GRANT INSERT ON public.contabilidad_results TO nelvyon_web_app;
GRANT INSERT ON public.contactenrichmentmasivo_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.contacts TO nelvyon_web_app;
GRANT INSERT ON public.contentscore_results TO nelvyon_web_app;
GRANT INSERT ON public.copywriting_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.countdown_timers TO nelvyon_web_app;
GRANT INSERT ON public.creative_assets TO nelvyon_web_app;
GRANT INSERT ON public.creative_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.crm_activities TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.crm_contacts TO nelvyon_web_app;
GRANT SELECT ON public.crm_deals TO nelvyon_web_app;
GRANT INSERT ON public.crypto_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.custom_object_records TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.custom_objects TO nelvyon_web_app;
GRANT INSERT ON public.customerjourney_results TO nelvyon_web_app;
GRANT INSERT ON public.customersuccess_results TO nelvyon_web_app;
GRANT INSERT ON public.databaseimport_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.deals TO nelvyon_web_app;
GRANT INSERT ON public.demo_results TO nelvyon_web_app;
GRANT INSERT ON public.deporte_results TO nelvyon_web_app;
GRANT INSERT ON public.dialer_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.digital_contracts TO nelvyon_web_app;
GRANT INSERT ON public.disenoweb_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.documents TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.dragdrop_workflows TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.dunning_log TO nelvyon_web_app;
GRANT SELECT, UPDATE ON public.early_adopter_config TO nelvyon_web_app;
GRANT INSERT ON public.ecommerce_results TO nelvyon_web_app;
GRANT INSERT ON public.ecommerceconv_results TO nelvyon_web_app;
GRANT INSERT ON public.email_marketing_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.email_queue TO nelvyon_web_app;
GRANT INSERT ON public.energia_results TO nelvyon_web_app;
GRANT INSERT ON public.enterprisequalitycalibration_results TO nelvyon_web_app;
GRANT INSERT ON public.erp_audit_events TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.erp_domain_snapshots TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.erp_inventory_products TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.erp_manufacturing_orders TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.erp_purchase_orders TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.erp_suppliers TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.erp_warehouses TO nelvyon_web_app;
GRANT INSERT ON public.estetica_results TO nelvyon_web_app;
GRANT INSERT ON public.eventos_results TO nelvyon_web_app;
GRANT INSERT ON public.experiencemanagement_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.feedback_items TO nelvyon_web_app;
GRANT INSERT ON public.fintech_results TO nelvyon_web_app;
GRANT INSERT ON public.firstparty_results TO nelvyon_web_app;
GRANT INSERT ON public.fiscalbilling_results TO nelvyon_web_app;
GRANT INSERT ON public.formulariosencuestas_results TO nelvyon_web_app;
GRANT INSERT ON public.fotografia_results TO nelvyon_web_app;
GRANT INSERT ON public.franquicias_results TO nelvyon_web_app;
GRANT INSERT ON public.funnelmultipaso_results TO nelvyon_web_app;
GRANT INSERT ON public.gaming_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.gbp_reviews TO nelvyon_web_app;
GRANT INSERT ON public.gcalzoom_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.generated_logos TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.geo_ai_checks TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.geo_ai_scores TO nelvyon_web_app;
GRANT INSERT ON public.geoengine_results TO nelvyon_web_app;
GRANT INSERT ON public.gobierno_results TO nelvyon_web_app;
GRANT INSERT ON public.growthhacking_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.heatmap_alerts TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.heatmap_events TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.heatmap_sessions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.heatmap_sites TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.helpdesk_tickets TO nelvyon_web_app;
GRANT INSERT ON public.helpdeskomnichannel_results TO nelvyon_web_app;
GRANT INSERT ON public.hipaacompliance_results TO nelvyon_web_app;
GRANT INSERT ON public.hospitality_results TO nelvyon_web_app;
GRANT INSERT ON public.hrtech_results TO nelvyon_web_app;
GRANT INSERT ON public.iapredictiva_results TO nelvyon_web_app;
GRANT INSERT ON public.imagenes_results TO nelvyon_web_app;
GRANT SELECT ON public.incidents TO nelvyon_web_app;
GRANT INSERT ON public.influencer_results TO nelvyon_web_app;
GRANT INSERT ON public.influencers_results TO nelvyon_web_app;
GRANT INSERT ON public.inmobiliariacomercial_results TO nelvyon_web_app;
GRANT INSERT ON public.integracionesnativas_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_ga4 TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_google_ads TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_linkedin_ads TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_meta_ads TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_search_console TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_semrush TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_shopify TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_telegram TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_tiktok_ads TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_twilio TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.integration_whatsapp TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.intent_actions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.intent_signals TO nelvyon_web_app;
GRANT INSERT ON public.investigador_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.invoices TO nelvyon_web_app;
GRANT INSERT ON public.klaviyo_results TO nelvyon_web_app;
GRANT INSERT ON public.knowledgebaseai_results TO nelvyon_web_app;
GRANT SELECT ON public.landing_analytics TO nelvyon_web_app;
GRANT SELECT ON public.landing_pages TO nelvyon_web_app;
GRANT INSERT ON public.landing_results TO nelvyon_web_app;
GRANT INSERT ON public.leadenrich_results TO nelvyon_web_app;
GRANT INSERT ON public.leaderboard_results TO nelvyon_web_app;
GRANT INSERT ON public.local_ai_ingest_jobs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.local_ai_memory TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.local_ai_rag_chunks TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.local_ai_rag_documents TO nelvyon_web_app;
GRANT INSERT ON public.manufactura_results TO nelvyon_web_app;
GRANT INSERT ON public.marca_results TO nelvyon_web_app;
GRANT INSERT ON public.marketing_leads TO nelvyon_web_app;
GRANT INSERT ON public.marketplace_results TO nelvyon_web_app;
GRANT INSERT ON public.membershipportalwhitelabel_results TO nelvyon_web_app;
GRANT INSERT ON public.membresiacursos_results TO nelvyon_web_app;
GRANT INSERT ON public.mfa_results TO nelvyon_web_app;
GRANT INSERT ON public.mobile_results TO nelvyon_web_app;
GRANT INSERT ON public.multicurrency_results TO nelvyon_web_app;
GRANT INSERT ON public.multiidiomaautomatico_results TO nelvyon_web_app;
GRANT INSERT ON public.multimodal_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_campaigns TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_clients TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_pack_runs TO nelvyon_web_app;
GRANT SELECT ON public.nelvyon_projects TO nelvyon_web_app;
GRANT SELECT ON public.nelvyon_rag_chunks TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_users TO nelvyon_web_app;
GRANT INSERT ON public.neuromarketing_results TO nelvyon_web_app;
GRANT INSERT ON public.newsletter_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.nps_responses TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.oauth_connections TO nelvyon_web_app;
GRANT SELECT, UPDATE ON public.oauth_tokens TO nelvyon_web_app;
GRANT INSERT ON public.observability_results TO nelvyon_web_app;
GRANT INSERT ON public.okrmanagement_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.onboarding TO nelvyon_web_app;
GRANT INSERT ON public.onboarding_results TO nelvyon_web_app;
GRANT INSERT ON public.optimizador_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_agent_audit_events TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_agent_data_cache TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.os_assets TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_brief_diff_runs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_clients TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_competitor_gap_runs TO nelvyon_web_app;
GRANT INSERT ON public.os_cron_logs TO nelvyon_web_app;
GRANT INSERT, UPDATE ON public.os_deliverable_approval_tokens TO nelvyon_web_app;
GRANT INSERT ON public.os_deliverable_reviews TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_deliverables TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_delivery_certificates TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_envato_seed_registry TO nelvyon_web_app;
GRANT INSERT ON public.os_health_reports TO nelvyon_web_app;
GRANT SELECT, UPDATE ON public.os_job_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_jobs TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_learning_run_log TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_pack_certifications TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_pack_gate_runs TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_portal_invites TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_portal_users TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_projects TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_qa_audit_runs TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_qa_review_queue TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.os_recurring_run_log TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_reports TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_retainer_cycles TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_sector_certifications TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_sector_readiness TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_sector_shield_audits TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_seed_weights TO nelvyon_web_app;
GRANT SELECT ON public.os_service_catalog TO nelvyon_web_app;
GRANT SELECT ON public.os_service_contracts TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_template_dna_scores TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.os_truth_guard_audits TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.os_upsell_suggestions TO nelvyon_web_app;
GRANT INSERT ON public.outboundb2b_results TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.partner_client_billing TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.partner_rebilling_ledger TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.partner_stripe_accounts TO nelvyon_web_app;
GRANT INSERT ON public.partnership_results TO nelvyon_web_app;
GRANT INSERT ON public.payment_results TO nelvyon_web_app;
GRANT INSERT ON public.perfpredictor_results TO nelvyon_web_app;
GRANT INSERT ON public.personalizacionmasiva_results TO nelvyon_web_app;
GRANT INSERT ON public.pinterestads_results TO nelvyon_web_app;
GRANT SELECT ON public.pipeline_deals TO nelvyon_web_app;
GRANT INSERT ON public.podcast_results TO nelvyon_web_app;
GRANT INSERT ON public.podcasts_results TO nelvyon_web_app;
GRANT INSERT ON public.prestashop_results TO nelvyon_web_app;
GRANT INSERT ON public.pricingdinamico_results TO nelvyon_web_app;
GRANT INSERT ON public.productanalytics_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products TO nelvyon_web_app;
GRANT INSERT ON public.proteccionip_results TO nelvyon_web_app;
GRANT INSERT ON public.publicapi_results TO nelvyon_web_app;
GRANT INSERT ON public.push_results TO nelvyon_web_app;
GRANT INSERT ON public.pwa_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.qr_codes TO nelvyon_web_app;
GRANT INSERT ON public.qrcodegenerator_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.quality_scores TO nelvyon_web_app;
GRANT INSERT ON public.ratelimit_results TO nelvyon_web_app;
GRANT INSERT ON public.realestate_results TO nelvyon_web_app;
GRANT INSERT ON public.realtime_results TO nelvyon_web_app;
GRANT INSERT ON public.referral_results TO nelvyon_web_app;
GRANT INSERT ON public.reporting_results TO nelvyon_web_app;
GRANT INSERT ON public.restaurantes_results TO nelvyon_web_app;
GRANT INSERT ON public.retail_results TO nelvyon_web_app;
GRANT INSERT ON public.revenueintelligence_results TO nelvyon_web_app;
GRANT INSERT ON public.reviews_results TO nelvyon_web_app;
GRANT SELECT ON public.roadmap_items TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.roi_conversions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.roi_events TO nelvyon_web_app;
GRANT INSERT, UPDATE ON public.roi_loops TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.roi_prediction_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.roi_predictions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_activation_checklist TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_activity_log TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_ads_campaign_links TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_ads_connections TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_ads_metrics_cache TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_ads_optimizer_rules TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_commissions TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_links TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_programs TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_agent_runs TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_api_keys TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_api_usage TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_appointments TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_approval_channel_settings TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_autopilot_settings TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_benchmark_snapshots TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_campania_recipients TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_campanias TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_ceo_brief_runs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_ceo_brief_settings TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_chat_messages TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_client_profiles TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_compliance_vault TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_connect_rebilling TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_contact_activities TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_contacts TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_contracts TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_conversation_messages TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_conversations TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_crm_sync_state TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_crm_territories TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_custom_roles TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_data_playbook_steps TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_data_playbooks TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_deals TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_deliverability_snapshots TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_deliverable_links TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_deliverable_revenue TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_dunning_events TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_exchange_rates TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_form_submissions TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_forms TO nelvyon_web_app;
GRANT INSERT ON public.saas_funnel_events TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_funnel_step_variants TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_funnel_steps TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_funnels TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_gdpr_requests TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_geo_visibility_runs TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_helpdesk_macros TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_helpdesk_messages TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_helpdesk_tickets TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_hubspot_sync_state TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_inbox_agent_settings TO nelvyon_web_app;
GRANT INSERT, UPDATE ON public.saas_inbox_agent_suggestions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_inbox_routing TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_inbox_sla_policies TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_integration_connections TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_invoices TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_kb_articles TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_kb_categories TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_lead_attribution TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_lead_scores TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lead_scoring_rules TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_lms_certificates TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_courses TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_lms_enrollments TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_lessons TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_modules TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_lms_progress TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_loyalty_balances TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_loyalty_programs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_loyalty_transactions TO nelvyon_web_app;
GRANT SELECT, UPDATE ON public.saas_marketplace_apps TO nelvyon_web_app;
GRANT INSERT ON public.saas_mcp_tool_audit TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_member_custom_roles TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_membership_access TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_membership_members TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_membership_plans TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_notifications TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_pack_entitlements TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_pack_launches TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_partner_referrals TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_partner_retail_prices TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_partners TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_playbook_actions TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_playbooks TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_private_ai_approvals TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_private_ai_audit TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_private_ai_settings TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_profile_changelog TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_projects_erp TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_prospecting_lists TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_prospecting_prospects TO nelvyon_web_app;
GRANT INSERT, UPDATE ON public.saas_prospecting_searches TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_pwa_installs TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_pwa_push_queue TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_pwa_push_subscriptions TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_quote_items TO nelvyon_web_app;
GRANT INSERT ON public.saas_quote_sequences TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_quotes TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_recurring_deliverables TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_reports TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_sandbox_tenants TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_seo_tracked_keywords TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_sequence_enrollments TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sequence_steps TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sequences TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_service_results TO nelvyon_web_app;
GRANT INSERT ON public.saas_shared_memory_audit TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_shared_memory_entries TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_sms_log TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_social_accounts TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_social_posts TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_social_proof_drafts TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sso_configs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_sso_identities TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_stage_probabilities TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_stripe_meter_items TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_subcuenta_meter_daily TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_subcuentas TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_tenant_installed_apps TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_tenant_ip_allowlist TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_tenant_memory_chunks TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_tenant_memory_settings TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_tenants TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_twilio_a2p_registrations TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_twilio_rebilling_ledger TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_usage_meter_daily TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_user_mfa TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_utm_clicks TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_utm_links TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_voice_commands TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_wa_catalog_products TO nelvyon_web_app;
GRANT SELECT ON public.saas_wa_settings TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_wa_templates TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_web_page_versions TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_web_pages TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_webhook_failures TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_whitelabel_configs TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.saas_workflow_recipes TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.saas_workflow_runs TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.saas_workflow_versions TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_workflows TO nelvyon_web_app;
GRANT INSERT ON public.saasb2b_results TO nelvyon_web_app;
GRANT INSERT ON public.salesintelligence_results TO nelvyon_web_app;
GRANT INSERT ON public.scaling_results TO nelvyon_web_app;
GRANT INSERT ON public.seguridadcodigo_results TO nelvyon_web_app;
GRANT INSERT ON public.seguros_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.sentiment_alerts TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.sentiment_mentions TO nelvyon_web_app;
GRANT INSERT ON public.seo_results TO nelvyon_web_app;
GRANT INSERT ON public.sessionreplay_results TO nelvyon_web_app;
GRANT INSERT ON public.sla_results TO nelvyon_web_app;
GRANT INSERT ON public.slack_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.snippets TO nelvyon_web_app;
GRANT INSERT ON public.social_results TO nelvyon_web_app;
GRANT INSERT ON public.social_share_results TO nelvyon_web_app;
GRANT INSERT ON public.sociallisteningbrand_results TO nelvyon_web_app;
GRANT INSERT ON public.socialvideo_results TO nelvyon_web_app;
GRANT INSERT ON public.sports_results TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT ON public.status_checks TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.store_order_items TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.store_orders TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.store_settings TO nelvyon_web_app;
GRANT INSERT, UPDATE ON public.stripe_webhook_events TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.subscriptions TO nelvyon_web_app;
GRANT INSERT ON public.superiorabtesting_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorattribution_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorchurn_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorcompetitive_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorcontentai_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorcrm_results TO nelvyon_web_app;
GRANT INSERT ON public.superioremail_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorinfluencer_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorlandingpage_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorleadenrichment_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorperformance_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorreporting_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorreviews_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorseo_results TO nelvyon_web_app;
GRANT INSERT ON public.superiorsocialmedia_results TO nelvyon_web_app;
GRANT SELECT ON public.support_templates TO nelvyon_web_app;
GRANT INSERT, SELECT, UPDATE ON public.support_tickets TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.survey_responses TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.surveys TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.team_members TO nelvyon_web_app;
GRANT INSERT ON public.technicalseoaudit_results TO nelvyon_web_app;
GRANT INSERT ON public.telecomunicaciones_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.telegram_messages TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.template_outcomes TO nelvyon_web_app;
GRANT INSERT ON public.testimonials_results TO nelvyon_web_app;
GRANT INSERT ON public.timezone_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.transcriptions TO nelvyon_web_app;
GRANT INSERT ON public.transporte_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.twilio_messages TO nelvyon_web_app;
GRANT INSERT ON public.uiux_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.uptime_checks TO nelvyon_web_app;
GRANT SELECT ON public.uptime_incidents TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.usage_events TO nelvyon_web_app;
GRANT SELECT ON public.usage_limits TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.video_enhancements TO nelvyon_web_app;
GRANT INSERT ON public.videomarketing_results TO nelvyon_web_app;
GRANT INSERT ON public.voiceagent_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev10_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev2_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev3_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev4_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev5_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev6_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev7_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev8_results TO nelvyon_web_app;
GRANT INSERT ON public.voicev9_results TO nelvyon_web_app;
GRANT INSERT ON public.waitlist TO nelvyon_web_app;
GRANT INSERT ON public.web3d_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.webhook_deliveries TO nelvyon_web_app;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.webhooks TO nelvyon_web_app;
GRANT INSERT ON public.webinar_results TO nelvyon_web_app;
GRANT INSERT ON public.webs3d_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.whatsapp_messages TO nelvyon_web_app;
GRANT INSERT ON public.widget_results TO nelvyon_web_app;
GRANT INSERT ON public.woocommerce_results TO nelvyon_web_app;
GRANT INSERT ON public.workflow_results TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.workspace_members TO nelvyon_web_app;
GRANT INSERT, SELECT ON public.workspaces TO nelvyon_web_app;
GRANT INSERT ON public.youtubeads_results TO nelvyon_web_app;
GRANT INSERT ON public.youtubers_results TO nelvyon_web_app;
GRANT INSERT ON public.zapier_results TO nelvyon_web_app;

-- nelvyon_web_jobs
GRANT SELECT ON public._migrations TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.ab_experiments TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ab_tests TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.ab_variants TO nelvyon_web_jobs;
GRANT INSERT ON public.admin_metrics_cache TO nelvyon_web_jobs;
GRANT INSERT ON public.ads_results TO nelvyon_web_jobs;
GRANT INSERT ON public.affiliate_clicks TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.affiliate_conversions TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.affiliate_profiles TO nelvyon_web_jobs;
GRANT INSERT ON public.agenciasmarketing_results TO nelvyon_web_jobs;
GRANT INSERT ON public.agencycert_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.agent_feedback TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.agent_outcomes TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.agent_quality_scores TO nelvyon_web_jobs;
GRANT INSERT ON public.animacion_results TO nelvyon_web_jobs;
GRANT INSERT ON public.antigeneric_results TO nelvyon_web_jobs;
GRANT SELECT ON public.api_key_usage_daily TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.api_keys TO nelvyon_web_jobs;
GRANT INSERT ON public.apollo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.appbuilderwhitelabel_results TO nelvyon_web_jobs;
GRANT INSERT ON public.arquitectura_results TO nelvyon_web_jobs;
GRANT INSERT ON public.artenft_results TO nelvyon_web_jobs;
GRANT INSERT ON public.attribution_reports TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.attribution_touchpoints TO nelvyon_web_jobs;
GRANT INSERT ON public.audiovisual_results TO nelvyon_web_jobs;
GRANT INSERT ON public.audit_log TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.audit_logs TO nelvyon_web_jobs;
GRANT INSERT ON public.autoprocesos_results TO nelvyon_web_jobs;
GRANT INSERT ON public.b2b_results TO nelvyon_web_jobs;
GRANT INSERT ON public.backupdisasterrecovery_results TO nelvyon_web_jobs;
GRANT INSERT ON public.badges_results TO nelvyon_web_jobs;
GRANT INSERT ON public.billing_results TO nelvyon_web_jobs;
GRANT INSERT ON public.bingads_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.booking_availability TO nelvyon_web_jobs;
GRANT INSERT ON public.bookingcalendario_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.bookings TO nelvyon_web_jobs;
GRANT INSERT ON public.branding_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.calendar_events TO nelvyon_web_jobs;
GRANT INSERT ON public.cdp_results TO nelvyon_web_jobs;
GRANT SELECT ON public.changelog_entries TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.chatbot_configs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.chatbot_conversations TO nelvyon_web_jobs;
GRANT INSERT ON public.chatwidget_results TO nelvyon_web_jobs;
GRANT INSERT ON public.churn_results TO nelvyon_web_jobs;
GRANT INSERT ON public.ciberseguridad_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.client_briefings TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.client_profiles TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.cold_email_campaigns TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.cold_email_prospects TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.communities TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.community_posts TO nelvyon_web_jobs;
GRANT INSERT ON public.community_results TO nelvyon_web_jobs;
GRANT INSERT ON public.comparator_results TO nelvyon_web_jobs;
GRANT INSERT ON public.competitive_rt_results TO nelvyon_web_jobs;
GRANT INSERT ON public.compliance_results TO nelvyon_web_jobs;
GRANT INSERT ON public.consultoria_results TO nelvyon_web_jobs;
GRANT INSERT ON public.contabilidad_results TO nelvyon_web_jobs;
GRANT INSERT ON public.contactenrichmentmasivo_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.contacts TO nelvyon_web_jobs;
GRANT INSERT ON public.contentscore_results TO nelvyon_web_jobs;
GRANT INSERT ON public.copywriting_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.countdown_timers TO nelvyon_web_jobs;
GRANT INSERT ON public.creative_assets TO nelvyon_web_jobs;
GRANT INSERT ON public.creative_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.crm_activities TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.crm_contacts TO nelvyon_web_jobs;
GRANT SELECT ON public.crm_deals TO nelvyon_web_jobs;
GRANT INSERT ON public.crypto_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.custom_object_records TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.custom_objects TO nelvyon_web_jobs;
GRANT INSERT ON public.customerjourney_results TO nelvyon_web_jobs;
GRANT INSERT ON public.customersuccess_results TO nelvyon_web_jobs;
GRANT INSERT ON public.databaseimport_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.deals TO nelvyon_web_jobs;
GRANT INSERT ON public.demo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.deporte_results TO nelvyon_web_jobs;
GRANT INSERT ON public.dialer_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.digital_contracts TO nelvyon_web_jobs;
GRANT INSERT ON public.disenoweb_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.documents TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.dragdrop_workflows TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.dunning_log TO nelvyon_web_jobs;
GRANT SELECT, UPDATE ON public.early_adopter_config TO nelvyon_web_jobs;
GRANT INSERT ON public.ecommerce_results TO nelvyon_web_jobs;
GRANT INSERT ON public.ecommerceconv_results TO nelvyon_web_jobs;
GRANT INSERT ON public.email_marketing_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.email_queue TO nelvyon_web_jobs;
GRANT INSERT ON public.energia_results TO nelvyon_web_jobs;
GRANT INSERT ON public.enterprisequalitycalibration_results TO nelvyon_web_jobs;
GRANT INSERT ON public.erp_audit_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.erp_domain_snapshots TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.erp_inventory_products TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.erp_manufacturing_orders TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.erp_purchase_orders TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.erp_suppliers TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.erp_warehouses TO nelvyon_web_jobs;
GRANT INSERT ON public.estetica_results TO nelvyon_web_jobs;
GRANT INSERT ON public.eventos_results TO nelvyon_web_jobs;
GRANT INSERT ON public.experiencemanagement_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.feedback_items TO nelvyon_web_jobs;
GRANT INSERT ON public.fintech_results TO nelvyon_web_jobs;
GRANT INSERT ON public.firstparty_results TO nelvyon_web_jobs;
GRANT INSERT ON public.fiscalbilling_results TO nelvyon_web_jobs;
GRANT INSERT ON public.formulariosencuestas_results TO nelvyon_web_jobs;
GRANT INSERT ON public.fotografia_results TO nelvyon_web_jobs;
GRANT INSERT ON public.franquicias_results TO nelvyon_web_jobs;
GRANT INSERT ON public.funnelmultipaso_results TO nelvyon_web_jobs;
GRANT INSERT ON public.gaming_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.gbp_reviews TO nelvyon_web_jobs;
GRANT INSERT ON public.gcalzoom_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.generated_logos TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.geo_ai_checks TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.geo_ai_scores TO nelvyon_web_jobs;
GRANT INSERT ON public.geoengine_results TO nelvyon_web_jobs;
GRANT INSERT ON public.gobierno_results TO nelvyon_web_jobs;
GRANT INSERT ON public.growthhacking_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.heatmap_alerts TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.heatmap_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.heatmap_sessions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.heatmap_sites TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.helpdesk_tickets TO nelvyon_web_jobs;
GRANT INSERT ON public.helpdeskomnichannel_results TO nelvyon_web_jobs;
GRANT INSERT ON public.hipaacompliance_results TO nelvyon_web_jobs;
GRANT INSERT ON public.hospitality_results TO nelvyon_web_jobs;
GRANT INSERT ON public.hrtech_results TO nelvyon_web_jobs;
GRANT INSERT ON public.iapredictiva_results TO nelvyon_web_jobs;
GRANT INSERT ON public.imagenes_results TO nelvyon_web_jobs;
GRANT SELECT ON public.incidents TO nelvyon_web_jobs;
GRANT INSERT ON public.influencer_results TO nelvyon_web_jobs;
GRANT INSERT ON public.influencers_results TO nelvyon_web_jobs;
GRANT INSERT ON public.inmobiliariacomercial_results TO nelvyon_web_jobs;
GRANT INSERT ON public.integracionesnativas_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_ga4 TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_google_ads TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_linkedin_ads TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_meta_ads TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_search_console TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_semrush TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_shopify TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_telegram TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_tiktok_ads TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_twilio TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.integration_whatsapp TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.intent_actions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.intent_signals TO nelvyon_web_jobs;
GRANT INSERT ON public.investigador_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.invoices TO nelvyon_web_jobs;
GRANT INSERT ON public.klaviyo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.knowledgebaseai_results TO nelvyon_web_jobs;
GRANT SELECT ON public.landing_analytics TO nelvyon_web_jobs;
GRANT SELECT ON public.landing_pages TO nelvyon_web_jobs;
GRANT INSERT ON public.landing_results TO nelvyon_web_jobs;
GRANT INSERT ON public.leadenrich_results TO nelvyon_web_jobs;
GRANT INSERT ON public.leaderboard_results TO nelvyon_web_jobs;
GRANT INSERT ON public.local_ai_ingest_jobs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.local_ai_memory TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.local_ai_rag_chunks TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.local_ai_rag_documents TO nelvyon_web_jobs;
GRANT INSERT ON public.manufactura_results TO nelvyon_web_jobs;
GRANT INSERT ON public.marca_results TO nelvyon_web_jobs;
GRANT INSERT ON public.marketing_leads TO nelvyon_web_jobs;
GRANT INSERT ON public.marketplace_results TO nelvyon_web_jobs;
GRANT INSERT ON public.membershipportalwhitelabel_results TO nelvyon_web_jobs;
GRANT INSERT ON public.membresiacursos_results TO nelvyon_web_jobs;
GRANT INSERT ON public.mfa_results TO nelvyon_web_jobs;
GRANT INSERT ON public.mobile_results TO nelvyon_web_jobs;
GRANT INSERT ON public.multicurrency_results TO nelvyon_web_jobs;
GRANT INSERT ON public.multiidiomaautomatico_results TO nelvyon_web_jobs;
GRANT INSERT ON public.multimodal_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_campaigns TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_clients TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_pack_runs TO nelvyon_web_jobs;
GRANT SELECT ON public.nelvyon_projects TO nelvyon_web_jobs;
GRANT SELECT ON public.nelvyon_rag_chunks TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.nelvyon_users TO nelvyon_web_jobs;
GRANT INSERT ON public.neuromarketing_results TO nelvyon_web_jobs;
GRANT INSERT ON public.newsletter_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.nps_responses TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.oauth_connections TO nelvyon_web_jobs;
GRANT SELECT, UPDATE ON public.oauth_tokens TO nelvyon_web_jobs;
GRANT INSERT ON public.observability_results TO nelvyon_web_jobs;
GRANT INSERT ON public.okrmanagement_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.onboarding TO nelvyon_web_jobs;
GRANT INSERT ON public.onboarding_results TO nelvyon_web_jobs;
GRANT INSERT ON public.optimizador_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_agent_audit_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_agent_data_cache TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.os_assets TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_brief_diff_runs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_clients TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_competitor_gap_runs TO nelvyon_web_jobs;
GRANT INSERT ON public.os_cron_logs TO nelvyon_web_jobs;
GRANT INSERT, UPDATE ON public.os_deliverable_approval_tokens TO nelvyon_web_jobs;
GRANT INSERT ON public.os_deliverable_reviews TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_deliverables TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_delivery_certificates TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_envato_seed_registry TO nelvyon_web_jobs;
GRANT INSERT ON public.os_health_reports TO nelvyon_web_jobs;
GRANT SELECT, UPDATE ON public.os_job_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_jobs TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_learning_run_log TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_pack_certifications TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_pack_gate_runs TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_portal_invites TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_portal_users TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_projects TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_qa_audit_runs TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_qa_review_queue TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.os_recurring_run_log TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_reports TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_retainer_cycles TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_sector_certifications TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_sector_readiness TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_sector_shield_audits TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_seed_weights TO nelvyon_web_jobs;
GRANT SELECT ON public.os_service_catalog TO nelvyon_web_jobs;
GRANT SELECT ON public.os_service_contracts TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_template_dna_scores TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.os_truth_guard_audits TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.os_upsell_suggestions TO nelvyon_web_jobs;
GRANT INSERT ON public.outboundb2b_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.partner_client_billing TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.partner_rebilling_ledger TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.partner_stripe_accounts TO nelvyon_web_jobs;
GRANT INSERT ON public.partnership_results TO nelvyon_web_jobs;
GRANT INSERT ON public.payment_results TO nelvyon_web_jobs;
GRANT INSERT ON public.perfpredictor_results TO nelvyon_web_jobs;
GRANT INSERT ON public.personalizacionmasiva_results TO nelvyon_web_jobs;
GRANT INSERT ON public.pinterestads_results TO nelvyon_web_jobs;
GRANT SELECT ON public.pipeline_deals TO nelvyon_web_jobs;
GRANT INSERT ON public.podcast_results TO nelvyon_web_jobs;
GRANT INSERT ON public.podcasts_results TO nelvyon_web_jobs;
GRANT INSERT ON public.prestashop_results TO nelvyon_web_jobs;
GRANT INSERT ON public.pricingdinamico_results TO nelvyon_web_jobs;
GRANT INSERT ON public.productanalytics_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products TO nelvyon_web_jobs;
GRANT INSERT ON public.proteccionip_results TO nelvyon_web_jobs;
GRANT INSERT ON public.publicapi_results TO nelvyon_web_jobs;
GRANT INSERT ON public.push_results TO nelvyon_web_jobs;
GRANT INSERT ON public.pwa_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.qr_codes TO nelvyon_web_jobs;
GRANT INSERT ON public.qrcodegenerator_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.quality_scores TO nelvyon_web_jobs;
GRANT INSERT ON public.ratelimit_results TO nelvyon_web_jobs;
GRANT INSERT ON public.realestate_results TO nelvyon_web_jobs;
GRANT INSERT ON public.realtime_results TO nelvyon_web_jobs;
GRANT INSERT ON public.referral_results TO nelvyon_web_jobs;
GRANT INSERT ON public.reporting_results TO nelvyon_web_jobs;
GRANT INSERT ON public.restaurantes_results TO nelvyon_web_jobs;
GRANT INSERT ON public.retail_results TO nelvyon_web_jobs;
GRANT INSERT ON public.revenueintelligence_results TO nelvyon_web_jobs;
GRANT INSERT ON public.reviews_results TO nelvyon_web_jobs;
GRANT SELECT ON public.roadmap_items TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.roi_conversions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.roi_events TO nelvyon_web_jobs;
GRANT INSERT, UPDATE ON public.roi_loops TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.roi_prediction_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.roi_predictions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_activation_checklist TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_activity_log TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_ads_campaign_links TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_ads_connections TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_ads_metrics_cache TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_ads_optimizer_rules TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_commissions TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_links TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_affiliate_programs TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_agent_runs TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_api_keys TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_api_usage TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_appointments TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_approval_channel_settings TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_autopilot_settings TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_benchmark_snapshots TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_campania_recipients TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_campanias TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_ceo_brief_runs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_ceo_brief_settings TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_chat_messages TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_client_profiles TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_compliance_vault TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_connect_rebilling TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_contact_activities TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_contacts TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_contracts TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_conversation_messages TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_conversations TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_crm_sync_state TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_crm_territories TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_custom_roles TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_data_playbook_steps TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_data_playbooks TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_deals TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_deliverability_snapshots TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_deliverable_links TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_deliverable_revenue TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_dunning_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_exchange_rates TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_form_submissions TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_forms TO nelvyon_web_jobs;
GRANT INSERT ON public.saas_funnel_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_funnel_step_variants TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_funnel_steps TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_funnels TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_gdpr_requests TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_geo_visibility_runs TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_helpdesk_macros TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_helpdesk_messages TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_helpdesk_tickets TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_hubspot_sync_state TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_inbox_agent_settings TO nelvyon_web_jobs;
GRANT INSERT, UPDATE ON public.saas_inbox_agent_suggestions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_inbox_routing TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_inbox_sla_policies TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_integration_connections TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_invoices TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_kb_articles TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_kb_categories TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_lead_attribution TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_lead_scores TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lead_scoring_rules TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_lms_certificates TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_courses TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_lms_enrollments TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_lessons TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_lms_modules TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_lms_progress TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_loyalty_balances TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_loyalty_programs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_loyalty_transactions TO nelvyon_web_jobs;
GRANT SELECT, UPDATE ON public.saas_marketplace_apps TO nelvyon_web_jobs;
GRANT INSERT ON public.saas_mcp_tool_audit TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_member_custom_roles TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_membership_access TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_membership_members TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_membership_plans TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_notifications TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_pack_entitlements TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_pack_launches TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_partner_referrals TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_partner_retail_prices TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_partners TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_playbook_actions TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_playbooks TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_private_ai_approvals TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_private_ai_audit TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_private_ai_settings TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_profile_changelog TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_projects_erp TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_prospecting_lists TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_prospecting_prospects TO nelvyon_web_jobs;
GRANT INSERT, UPDATE ON public.saas_prospecting_searches TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_pwa_installs TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_pwa_push_queue TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_pwa_push_subscriptions TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_quote_items TO nelvyon_web_jobs;
GRANT INSERT ON public.saas_quote_sequences TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_quotes TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_recurring_deliverables TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_reports TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_sandbox_tenants TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_seo_tracked_keywords TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_sequence_enrollments TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sequence_steps TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sequences TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_service_results TO nelvyon_web_jobs;
GRANT INSERT ON public.saas_shared_memory_audit TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_shared_memory_entries TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_sms_log TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_social_accounts TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_social_posts TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_social_proof_drafts TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_sso_configs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_sso_identities TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_stage_probabilities TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_stripe_meter_items TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_subcuenta_meter_daily TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_subcuentas TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_tenant_installed_apps TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_tenant_ip_allowlist TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_tenant_memory_chunks TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_tenant_memory_settings TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_tenants TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_twilio_a2p_registrations TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_twilio_rebilling_ledger TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_usage_meter_daily TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_user_mfa TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_utm_clicks TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_utm_links TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_voice_commands TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_wa_catalog_products TO nelvyon_web_jobs;
GRANT SELECT ON public.saas_wa_settings TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_wa_templates TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_web_page_versions TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_web_pages TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_webhook_failures TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_whitelabel_configs TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.saas_workflow_recipes TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.saas_workflow_runs TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.saas_workflow_versions TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saas_workflows TO nelvyon_web_jobs;
GRANT INSERT ON public.saasb2b_results TO nelvyon_web_jobs;
GRANT INSERT ON public.salesintelligence_results TO nelvyon_web_jobs;
GRANT INSERT ON public.scaling_results TO nelvyon_web_jobs;
GRANT INSERT ON public.seguridadcodigo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.seguros_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.sentiment_alerts TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.sentiment_mentions TO nelvyon_web_jobs;
GRANT INSERT ON public.seo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.sessionreplay_results TO nelvyon_web_jobs;
GRANT INSERT ON public.sla_results TO nelvyon_web_jobs;
GRANT INSERT ON public.slack_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.snippets TO nelvyon_web_jobs;
GRANT INSERT ON public.social_results TO nelvyon_web_jobs;
GRANT INSERT ON public.social_share_results TO nelvyon_web_jobs;
GRANT INSERT ON public.sociallisteningbrand_results TO nelvyon_web_jobs;
GRANT INSERT ON public.socialvideo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.sports_results TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT ON public.status_checks TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.store_order_items TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.store_orders TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.store_settings TO nelvyon_web_jobs;
GRANT INSERT, UPDATE ON public.stripe_webhook_events TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.subscriptions TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorabtesting_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorattribution_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorchurn_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorcompetitive_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorcontentai_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorcrm_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superioremail_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorinfluencer_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorlandingpage_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorleadenrichment_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorperformance_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorreporting_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorreviews_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorseo_results TO nelvyon_web_jobs;
GRANT INSERT ON public.superiorsocialmedia_results TO nelvyon_web_jobs;
GRANT SELECT ON public.support_templates TO nelvyon_web_jobs;
GRANT INSERT, SELECT, UPDATE ON public.support_tickets TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.survey_responses TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.surveys TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.team_members TO nelvyon_web_jobs;
GRANT INSERT ON public.technicalseoaudit_results TO nelvyon_web_jobs;
GRANT INSERT ON public.telecomunicaciones_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.telegram_messages TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.template_outcomes TO nelvyon_web_jobs;
GRANT INSERT ON public.testimonials_results TO nelvyon_web_jobs;
GRANT INSERT ON public.timezone_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.transcriptions TO nelvyon_web_jobs;
GRANT INSERT ON public.transporte_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.twilio_messages TO nelvyon_web_jobs;
GRANT INSERT ON public.uiux_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.uptime_checks TO nelvyon_web_jobs;
GRANT SELECT ON public.uptime_incidents TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.usage_events TO nelvyon_web_jobs;
GRANT SELECT ON public.usage_limits TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.video_enhancements TO nelvyon_web_jobs;
GRANT INSERT ON public.videomarketing_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voiceagent_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev10_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev2_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev3_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev4_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev5_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev6_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev7_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev8_results TO nelvyon_web_jobs;
GRANT INSERT ON public.voicev9_results TO nelvyon_web_jobs;
GRANT INSERT ON public.waitlist TO nelvyon_web_jobs;
GRANT INSERT ON public.web3d_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.webhook_deliveries TO nelvyon_web_jobs;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.webhooks TO nelvyon_web_jobs;
GRANT INSERT ON public.webinar_results TO nelvyon_web_jobs;
GRANT INSERT ON public.webs3d_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.whatsapp_messages TO nelvyon_web_jobs;
GRANT INSERT ON public.widget_results TO nelvyon_web_jobs;
GRANT INSERT ON public.woocommerce_results TO nelvyon_web_jobs;
GRANT INSERT ON public.workflow_results TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.workspace_members TO nelvyon_web_jobs;
GRANT INSERT, SELECT ON public.workspaces TO nelvyon_web_jobs;
GRANT INSERT ON public.youtubeads_results TO nelvyon_web_jobs;
GRANT INSERT ON public.youtubers_results TO nelvyon_web_jobs;
GRANT INSERT ON public.zapier_results TO nelvyon_web_jobs;

-- ── USAGE sobre el esquema `auth` — IMPRESCINDIBLE ──
--
-- Lo encontro la certificacion de las familias SaaS, no la lectura del catalogo:
-- 12 pruebas fallaron con `permission denied for schema auth`.
--
-- `nelvyon_jwt_user_id()` y `nelvyon_jwt_sub_text()` NO son SECURITY DEFINER, asi
-- que se ejecutan como quien llama y necesitan alcanzar `auth.uid()`. Son la base
-- de la familia de politica mas usada: 804 politicas sobre 201 tablas.
--
-- Sin este GRANT, el cutover no habria degradado nada: habria REVENTADO en el
-- momento en que la primera peticion tocara cualquiera de esas 201 tablas.
--
-- Precedente comprobado en produccion: `nelvyon_app` —el rol del lado Python, que
-- lleva meses funcionando con RLS efectiva— SI tiene este privilegio.
-- `nelvyon_jobs` no lo tiene y no le hace falta, porque salta RLS.
GRANT USAGE ON SCHEMA auth TO nelvyon_web_app;

-- Secuencias: necesarias para los INSERT con id serial. Solo USAGE.
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO nelvyon_web_app, nelvyon_web_jobs;

-- Comprobacion, para que el propio fichero se desmienta si algo cambia:
DO $$
DECLARE sobra int;
BEGIN
  SELECT count(*) INTO sobra FROM pg_roles
   WHERE rolname IN ('nelvyon_web_app','nelvyon_web_jobs')
     AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication);
  IF sobra > 0 THEN
    RAISE EXCEPTION 'un rol del web quedo con privilegios administrativos';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='nelvyon_web_app' AND rolbypassrls) THEN
    RAISE EXCEPTION 'nelvyon_web_app salta RLS: no serviria de nada';
  END IF;
END $$;