"""auto update

Revision ID: 066fdc1027a5
Revises: c44f6a34edf8
Create Date: 2026-04-08 01:18:47.578713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066fdc1027a5'
down_revision: Union[str, Sequence[str], None] = 'c44f6a34edf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nelvyon_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('codename', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('long_description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('gradient', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uptime', sa.String(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_today', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('functionality_level', sa.String(), nullable=True),
    sa.Column('functionality_note', sa.String(), nullable=True),
    sa.Column('capabilities', sa.String(), nullable=True),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('recent_tasks', sa.String(), nullable=True),
    sa.Column('logs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_agents_id'), 'nelvyon_agents', ['id'], unique=False)
    op.create_table('nelvyon_bot_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('channels', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_bot_templates_id'), 'nelvyon_bot_templates', ['id'], unique=False)
    op.create_table('nelvyon_quality_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('has_backend', sa.Boolean(), nullable=True),
    sa.Column('has_ai', sa.Boolean(), nullable=True),
    sa.Column('has_crud', sa.Boolean(), nullable=True),
    sa.Column('has_real_data', sa.Boolean(), nullable=True),
    sa.Column('uptime', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('real_features', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_quality_metrics_id'), 'nelvyon_quality_metrics', ['id'], unique=False)
    op.create_table('nelvyon_user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_new_clients', sa.Boolean(), nullable=True),
    sa.Column('notification_qa_complete', sa.Boolean(), nullable=True),
    sa.Column('notification_deploys', sa.Boolean(), nullable=True),
    sa.Column('notification_errors', sa.Boolean(), nullable=True),
    sa.Column('notification_weekly_email', sa.Boolean(), nullable=True),
    sa.Column('theme_id', sa.String(), nullable=True),
    sa.Column('custom_theme_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_user_settings_id'), 'nelvyon_user_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nelvyon_user_settings_id'), table_name='nelvyon_user_settings')
    op.drop_table('nelvyon_user_settings')
    op.drop_index(op.f('ix_nelvyon_quality_metrics_id'), table_name='nelvyon_quality_metrics')
    op.drop_table('nelvyon_quality_metrics')
    op.drop_index(op.f('ix_nelvyon_bot_templates_id'), table_name='nelvyon_bot_templates')
    op.drop_table('nelvyon_bot_templates')
    op.drop_index(op.f('ix_nelvyon_agents_id'), table_name='nelvyon_agents')
    op.drop_table('nelvyon_agents')
    # ### end Alembic commands ###