"""auto update

Revision ID: 167d5ba38b88
Revises: ca96d9b1123f
Create Date: 2026-04-11 03:17:59.300396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167d5ba38b88'
down_revision: Union[str, Sequence[str], None] = 'ca96d9b1123f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.add_column('automation_jobs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_automation_jobs_workspace_id'), 'automation_jobs', ['workspace_id'], unique=False)
    op.add_column('automation_webhooks', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_automation_webhooks_workspace_id'), 'automation_webhooks', ['workspace_id'], unique=False)
    op.add_column('blog_posts', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_posts_workspace_id'), 'blog_posts', ['workspace_id'], unique=False)
    op.add_column('calendar_events', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.add_column('connector_configs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_connector_configs_workspace_id'), 'connector_configs', ['workspace_id'], unique=False)
    op.add_column('email_queue', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_email_queue_workspace_id'), 'email_queue', ['workspace_id'], unique=False)
    op.add_column('form_items', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_form_items_workspace_id'), 'form_items', ['workspace_id'], unique=False)
    op.add_column('funnel_items', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_funnel_items_workspace_id'), 'funnel_items', ['workspace_id'], unique=False)
    op.add_column('helpdesk_tickets', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_helpdesk_tickets_workspace_id'), 'helpdesk_tickets', ['workspace_id'], unique=False)
    op.add_column('messages', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.add_column('nelvyon_agents', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_agents_workspace_id'), 'nelvyon_agents', ['workspace_id'], unique=False)
    op.add_column('nelvyon_assets', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_assets_workspace_id'), 'nelvyon_assets', ['workspace_id'], unique=False)
    op.add_column('nelvyon_bot_templates', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_bot_templates_workspace_id'), 'nelvyon_bot_templates', ['workspace_id'], unique=False)
    op.add_column('nelvyon_campaigns', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_campaigns_workspace_id'), 'nelvyon_campaigns', ['workspace_id'], unique=False)
    op.add_column('nelvyon_clients', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_clients_workspace_id'), 'nelvyon_clients', ['workspace_id'], unique=False)
    op.add_column('nelvyon_outputs', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_outputs_workspace_id'), 'nelvyon_outputs', ['workspace_id'], unique=False)
    op.add_column('nelvyon_products', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_products_workspace_id'), 'nelvyon_products', ['workspace_id'], unique=False)
    op.add_column('nelvyon_projects', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_projects_workspace_id'), 'nelvyon_projects', ['workspace_id'], unique=False)
    op.add_column('nelvyon_quality_metrics', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_quality_metrics_workspace_id'), 'nelvyon_quality_metrics', ['workspace_id'], unique=False)
    op.add_column('nelvyon_user_settings', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nelvyon_user_settings_workspace_id'), 'nelvyon_user_settings', ['workspace_id'], unique=False)
    op.add_column('partner_records', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_partner_records_workspace_id'), 'partner_records', ['workspace_id'], unique=False)
    op.add_column('pipeline_deals', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pipeline_deals_workspace_id'), 'pipeline_deals', ['workspace_id'], unique=False)
    op.add_column('presentation_history', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_presentation_history_workspace_id'), 'presentation_history', ['workspace_id'], unique=False)
    op.add_column('report_items', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_report_items_workspace_id'), 'report_items', ['workspace_id'], unique=False)
    op.add_column('revenue_records', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_revenue_records_workspace_id'), 'revenue_records', ['workspace_id'], unique=False)
    op.add_column('sales_records', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_records_workspace_id'), 'sales_records', ['workspace_id'], unique=False)
    op.add_column('segment_results', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_segment_results_workspace_id'), 'segment_results', ['workspace_id'], unique=False)
    op.add_column('website_items', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_website_items_workspace_id'), 'website_items', ['workspace_id'], unique=False)
    op.add_column('workflow_executions', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workflow_executions_workspace_id'), 'workflow_executions', ['workspace_id'], unique=False)
    op.add_column('workflow_rules', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workflow_rules_workspace_id'), 'workflow_rules', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_rules_workspace_id'), table_name='workflow_rules')
    op.drop_column('workflow_rules', 'workspace_id')
    op.drop_index(op.f('ix_workflow_executions_workspace_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'workspace_id')
    op.drop_index(op.f('ix_website_items_workspace_id'), table_name='website_items')
    op.drop_column('website_items', 'workspace_id')
    op.drop_index(op.f('ix_segment_results_workspace_id'), table_name='segment_results')
    op.drop_column('segment_results', 'workspace_id')
    op.drop_index(op.f('ix_sales_records_workspace_id'), table_name='sales_records')
    op.drop_column('sales_records', 'workspace_id')
    op.drop_index(op.f('ix_revenue_records_workspace_id'), table_name='revenue_records')
    op.drop_column('revenue_records', 'workspace_id')
    op.drop_index(op.f('ix_report_items_workspace_id'), table_name='report_items')
    op.drop_column('report_items', 'workspace_id')
    op.drop_index(op.f('ix_presentation_history_workspace_id'), table_name='presentation_history')
    op.drop_column('presentation_history', 'workspace_id')
    op.drop_index(op.f('ix_pipeline_deals_workspace_id'), table_name='pipeline_deals')
    op.drop_column('pipeline_deals', 'workspace_id')
    op.drop_index(op.f('ix_partner_records_workspace_id'), table_name='partner_records')
    op.drop_column('partner_records', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_user_settings_workspace_id'), table_name='nelvyon_user_settings')
    op.drop_column('nelvyon_user_settings', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_quality_metrics_workspace_id'), table_name='nelvyon_quality_metrics')
    op.drop_column('nelvyon_quality_metrics', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_projects_workspace_id'), table_name='nelvyon_projects')
    op.drop_column('nelvyon_projects', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_products_workspace_id'), table_name='nelvyon_products')
    op.drop_column('nelvyon_products', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_outputs_workspace_id'), table_name='nelvyon_outputs')
    op.drop_column('nelvyon_outputs', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_clients_workspace_id'), table_name='nelvyon_clients')
    op.drop_column('nelvyon_clients', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_campaigns_workspace_id'), table_name='nelvyon_campaigns')
    op.drop_column('nelvyon_campaigns', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_bot_templates_workspace_id'), table_name='nelvyon_bot_templates')
    op.drop_column('nelvyon_bot_templates', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_assets_workspace_id'), table_name='nelvyon_assets')
    op.drop_column('nelvyon_assets', 'workspace_id')
    op.drop_index(op.f('ix_nelvyon_agents_workspace_id'), table_name='nelvyon_agents')
    op.drop_column('nelvyon_agents', 'workspace_id')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_column('messages', 'workspace_id')
    op.drop_index(op.f('ix_helpdesk_tickets_workspace_id'), table_name='helpdesk_tickets')
    op.drop_column('helpdesk_tickets', 'workspace_id')
    op.drop_index(op.f('ix_funnel_items_workspace_id'), table_name='funnel_items')
    op.drop_column('funnel_items', 'workspace_id')
    op.drop_index(op.f('ix_form_items_workspace_id'), table_name='form_items')
    op.drop_column('form_items', 'workspace_id')
    op.drop_index(op.f('ix_email_queue_workspace_id'), table_name='email_queue')
    op.drop_column('email_queue', 'workspace_id')
    op.drop_index(op.f('ix_connector_configs_workspace_id'), table_name='connector_configs')
    op.drop_column('connector_configs', 'workspace_id')
    op.drop_index(op.f('ix_calendar_events_workspace_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'workspace_id')
    op.drop_index(op.f('ix_blog_posts_workspace_id'), table_name='blog_posts')
    op.drop_column('blog_posts', 'workspace_id')
    op.drop_index(op.f('ix_automation_webhooks_workspace_id'), table_name='automation_webhooks')
    op.drop_column('automation_webhooks', 'workspace_id')
    op.drop_index(op.f('ix_automation_jobs_workspace_id'), table_name='automation_jobs')
    op.drop_column('automation_jobs', 'workspace_id')
    op.drop_column('activities', 'deal_id')
    # ### end Alembic commands ###