"""auto update

Revision ID: 1cb46e6f3ce9
Revises: c87f78600fe0
Create Date: 2026-03-31 10:53:14.660847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb46e6f3ce9'
down_revision: Union[str, Sequence[str], None] = 'c87f78600fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nelvyon_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_assets_id'), 'nelvyon_assets', ['id'], unique=False)
    op.create_table('nelvyon_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('campaign_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('variants_count', sa.Integer(), nullable=True),
    sa.Column('budget_suggested', sa.Float(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('qa_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_campaigns_id'), 'nelvyon_campaigns', ['id'], unique=False)
    op.create_table('nelvyon_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('ideal_customer', sa.String(), nullable=True),
    sa.Column('value_proposition', sa.String(), nullable=True),
    sa.Column('differentiator', sa.String(), nullable=True),
    sa.Column('services', sa.String(), nullable=True),
    sa.Column('objectives', sa.String(), nullable=True),
    sa.Column('brand_tone', sa.String(), nullable=True),
    sa.Column('visual_style', sa.String(), nullable=True),
    sa.Column('brand_colors', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('competition', sa.String(), nullable=True),
    sa.Column('testimonials', sa.String(), nullable=True),
    sa.Column('case_studies', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_clients_id'), 'nelvyon_clients', ['id'], unique=False)
    op.create_table('nelvyon_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('qa_score', sa.Integer(), nullable=True),
    sa.Column('qa_status', sa.String(), nullable=True),
    sa.Column('qa_feedback', sa.String(), nullable=True),
    sa.Column('qa_attempts', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_outputs_id'), 'nelvyon_outputs', ['id'], unique=False)
    op.create_table('nelvyon_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('specs', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('images', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_products_id'), 'nelvyon_products', ['id'], unique=False)
    op.create_table('nelvyon_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('brief', sa.String(), nullable=True),
    sa.Column('deliverables', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nelvyon_projects_id'), 'nelvyon_projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nelvyon_projects_id'), table_name='nelvyon_projects')
    op.drop_table('nelvyon_projects')
    op.drop_index(op.f('ix_nelvyon_products_id'), table_name='nelvyon_products')
    op.drop_table('nelvyon_products')
    op.drop_index(op.f('ix_nelvyon_outputs_id'), table_name='nelvyon_outputs')
    op.drop_table('nelvyon_outputs')
    op.drop_index(op.f('ix_nelvyon_clients_id'), table_name='nelvyon_clients')
    op.drop_table('nelvyon_clients')
    op.drop_index(op.f('ix_nelvyon_campaigns_id'), table_name='nelvyon_campaigns')
    op.drop_table('nelvyon_campaigns')
    op.drop_index(op.f('ix_nelvyon_assets_id'), table_name='nelvyon_assets')
    op.drop_table('nelvyon_assets')
    # ### end Alembic commands ###