"""auto update

Revision ID: 4dd1c8135da3
Revises: 27ce7b2abcd0
Create Date: 2026-04-03 04:44:01.893391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dd1c8135da3'
down_revision: Union[str, Sequence[str], None] = '27ce7b2abcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nelvyon_clients', 'status')
    op.drop_column('nelvyon_clients', 'contact_phone')
    op.drop_column('nelvyon_clients', 'contact_email')
    op.drop_column('nelvyon_clients', 'notes')
    op.drop_column('nelvyon_clients', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nelvyon_clients', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('nelvyon_clients', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nelvyon_clients', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nelvyon_clients', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('nelvyon_clients', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###