"""auto update

Revision ID: 61e446a63479
Revises: 203b42ccb7e9
Create Date: 2026-04-11 04:18:43.571464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e446a63479'
down_revision: Union[str, Sequence[str], None] = '203b42ccb7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signature_data', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('audit_trail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.add_column('deals', sa.Column('pipeline', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('days_in_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'days_in_stage')
    op.drop_column('deals', 'tags')
    op.drop_column('deals', 'assigned_to')
    op.drop_column('deals', 'pipeline')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###