"""auto update

Revision ID: b1c12602735a
Revises: 066fdc1027a5
Create Date: 2026-04-08 03:36:31.006619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c12602735a'
down_revision: Union[str, Sequence[str], None] = '066fdc1027a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_metrics_id'), 'platform_metrics', ['id'], unique=False)
    op.create_table('presentation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pres_type', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_sector', sa.String(), nullable=True),
    sa.Column('slides_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('slides_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_history_id'), 'presentation_history', ['id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_records_id'), 'revenue_records', ['id'], unique=False)
    op.create_table('segment_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('segments_count', sa.Integer(), nullable=True),
    sa.Column('top_segment', sa.String(), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.Column('contacts_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_results_id'), 'segment_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segment_results_id'), table_name='segment_results')
    op.drop_table('segment_results')
    op.drop_index(op.f('ix_revenue_records_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_presentation_history_id'), table_name='presentation_history')
    op.drop_table('presentation_history')
    op.drop_index(op.f('ix_platform_metrics_id'), table_name='platform_metrics')
    op.drop_table('platform_metrics')
    # ### end Alembic commands ###