"""auto update

Revision ID: c44f6a34edf8
Revises: 00ab1043eadc
Create Date: 2026-04-07 06:25:00.474173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44f6a34edf8'
down_revision: Union[str, Sequence[str], None] = '00ab1043eadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('featured_image', sa.String(), nullable=True),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('seo_description', sa.String(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('connector_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('connector_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_configs_id'), 'connector_configs', ['id'], unique=False)
    op.create_table('form_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fields_count', sa.Integer(), nullable=True),
    sa.Column('responses_count', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_time_seconds', sa.Integer(), nullable=True),
    sa.Column('fields_json', sa.String(), nullable=True),
    sa.Column('ai_optimized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_items_id'), 'form_items', ['id'], unique=False)
    op.create_table('funnel_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('funnel_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stages_count', sa.Integer(), nullable=True),
    sa.Column('stages_json', sa.String(), nullable=True),
    sa.Column('visitors', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_items_id'), 'funnel_items', ['id'], unique=False)
    op.create_table('helpdesk_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('first_response_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helpdesk_tickets_id'), 'helpdesk_tickets', ['id'], unique=False)
    op.create_table('partner_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('referrals_count', sa.Integer(), nullable=True),
    sa.Column('conversions_count', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('commission_earned', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_records_id'), 'partner_records', ['id'], unique=False)
    op.create_table('pipeline_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('days_in_stage', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_deals_id'), 'pipeline_deals', ['id'], unique=False)
    op.create_table('report_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_json', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_items_id'), 'report_items', ['id'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_records_id'), 'sales_records', ['id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('website_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_items_id'), 'website_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_items_id'), table_name='website_items')
    op.drop_table('website_items')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_sales_records_id'), table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index(op.f('ix_report_items_id'), table_name='report_items')
    op.drop_table('report_items')
    op.drop_index(op.f('ix_pipeline_deals_id'), table_name='pipeline_deals')
    op.drop_table('pipeline_deals')
    op.drop_index(op.f('ix_partner_records_id'), table_name='partner_records')
    op.drop_table('partner_records')
    op.drop_index(op.f('ix_helpdesk_tickets_id'), table_name='helpdesk_tickets')
    op.drop_table('helpdesk_tickets')
    op.drop_index(op.f('ix_funnel_items_id'), table_name='funnel_items')
    op.drop_table('funnel_items')
    op.drop_index(op.f('ix_form_items_id'), table_name='form_items')
    op.drop_table('form_items')
    op.drop_index(op.f('ix_connector_configs_id'), table_name='connector_configs')
    op.drop_table('connector_configs')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###