export type ErrorCode =
  | "RATE_LIMIT_EXCEEDED"
  | "UNAUTHORIZED"
  | "PLAN_REQUIRED"
  | "AGENT_NOT_FOUND"
  | "AGENT_FAILED"
  | "INVALID_INPUT"
  | "SERVICE_UNAVAILABLE"
  | "PAYMENT_REQUIRED"
  | "UNKNOWN_ERROR";
