-- 577 — los dos roles del lado web, listos para el cutover. NO hace el cutover.
--
-- QUE HACE Y QUE NO
-- =================
-- CREA los roles y les concede EXACTAMENTE los privilegios medidos del uso real
-- del codigo (485 tablas de 710; las otras 225 el runtime web no las toca).
--
-- NO cambia ninguna credencial, NO toca `DATABASE_URL` y NO mueve trafico. Los
-- dos roles nacen **NOLOGIN**: existen, tienen sus permisos, y no pueden
-- conectarse. Aplicar esta migracion no cambia el comportamiento de nada.
--
-- POR QUE NOLOGIN Y NO UNA CONTRASENA
-- ------------------------------------
-- Una migracion del arbol no puede llevar una contrasena de produccion escrita:
-- quedaria en el repositorio, en el historial y en los registros del despliegue.
-- `backend/db/certificacion/roles_web.sql` si lleva una —'cambiar_en_el_cutover'—
-- porque es un fichero de certificacion local que nunca se aplica fuera de aqui.
--
-- Asi que el acto de dar acceso queda separado del acto de definir permisos, que
-- es como debe estar: los permisos son codigo revisable, la credencial no.
--
-- EL UNICO PASO MANUAL QUE QUEDA DESPUES DE ESTO
-- ----------------------------------------------
--     ALTER ROLE nelvyon_web_app  WITH LOGIN PASSWORD '<secreto>';
--     ALTER ROLE nelvyon_web_jobs WITH LOGIN PASSWORD '<otro secreto>';
--     DATABASE_URL                  -> nelvyon_web_app
--     NELVYON_WEB_JOBS_DATABASE_URL -> nelvyon_web_jobs
--
-- Y la vuelta atras es devolver `DATABASE_URL` al rol anterior. Nada de lo que
-- hace esta migracion hay que deshacer para revertir.
--
-- POR QUE LOS DOS ROLES Y NO UNO
-- -------------------------------
--   nelvyon_web_app    trafico normal.  NOBYPASSRLS -> las politicas DECIDEN.
--   nelvyon_web_jobs   crons, webhooks y los planos platform/admin. Trabajan
--                      entre inquilinos de verdad, asi que SI lleva BYPASSRLS —
--                      y por tanto su aislamiento depende del `WHERE` explicito
--                      de cada consulta, el mismo contrato que `nelvyon_jobs` en
--                      el lado Python. Se escribe asi para que nadie lo confunda
--                      con «otro rol seguro».
--
-- Son 60 rutas las que necesitan la segunda, inventariadas una a una con su
-- motivo en `test_las_rutas_web_fijan_el_inquilino.py`. Sin ella, el cutover no
-- las romperia con un error: les devolveria CERO FILAS.
--
-- POR QUE TOLERA TABLAS AUSENTES
-- -------------------------------
-- La lista salio del uso real del codigo, no del catalogo. Una base de destino
-- puede ir por detras de la cadena de migraciones y no tener todavia alguna de
-- las 485. Conceder sobre una tabla inexistente aborta la migracion entera y
-- deja los roles a medio permisar, que es peor que saltarsela: un rol con
-- permisos incompletos falla en produccion, de noche y por partes.
--
-- Lo que NO se tolera es el silencio: al final se cuentan las omitidas y se
-- avisa con su numero.
--
-- IDEMPOTENTE. Se puede aplicar dos veces sin efecto distinto.

-- ── Los dos roles ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nelvyon_web_app') THEN
    CREATE ROLE nelvyon_web_app NOLOGIN
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  ELSE
    -- No toca LOGIN ni la contrasena: si el cutover ya se hizo, no lo deshace.
    ALTER ROLE nelvyon_web_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nelvyon_web_jobs') THEN
    CREATE ROLE nelvyon_web_jobs NOLOGIN
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
  ELSE
    ALTER ROLE nelvyon_web_jobs NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO nelvyon_web_app, nelvyon_web_jobs;
REVOKE CREATE ON SCHEMA public FROM nelvyon_web_app, nelvyon_web_jobs;

-- USAGE sobre el esquema `auth` — IMPRESCINDIBLE para nelvyon_web_app.
--
-- Lo encontro la certificacion de las familias SaaS, no la lectura del catalogo:
-- 12 pruebas fallaron con `permission denied for schema auth`.
--
-- `nelvyon_jwt_user_id()` y `nelvyon_jwt_sub_text()` NO son SECURITY DEFINER, asi
-- que se ejecutan como quien llama y necesitan alcanzar `auth.uid()`. Son la base
-- de la familia de politica mas usada: 804 politicas sobre 201 tablas.
--
-- Sin este GRANT el cutover no habria degradado nada: habria REVENTADO en cuanto
-- la primera peticion tocara cualquiera de esas 201 tablas.
--
-- `nelvyon_web_jobs` no lo necesita porque salta RLS, igual que `nelvyon_jobs`.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA auth TO nelvyon_web_app';
  END IF;
END $$;

-- Secuencias: necesarias para los INSERT con id serial. Solo USAGE.
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO nelvyon_web_app, nelvyon_web_jobs;

-- ── Privilegios por tabla ──
DO $$
DECLARE
  f record;
  omitidas int := 0;
  aplicadas int := 0;
BEGIN
  FOR f IN SELECT * FROM (VALUES
    ('_migrations','SELECT','nelvyon_web_app'),
    ('ab_experiments','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('ab_tests','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('ab_variants','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('admin_metrics_cache','INSERT','nelvyon_web_app'),
    ('ads_results','INSERT','nelvyon_web_app'),
    ('affiliate_clicks','INSERT','nelvyon_web_app'),
    ('affiliate_conversions','INSERT, SELECT','nelvyon_web_app'),
    ('affiliate_profiles','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('agenciasmarketing_results','INSERT','nelvyon_web_app'),
    ('agencycert_results','INSERT','nelvyon_web_app'),
    ('agent_feedback','INSERT, SELECT','nelvyon_web_app'),
    ('agent_outcomes','INSERT, SELECT','nelvyon_web_app'),
    ('agent_quality_scores','INSERT, SELECT','nelvyon_web_app'),
    ('animacion_results','INSERT','nelvyon_web_app'),
    ('antigeneric_results','INSERT','nelvyon_web_app'),
    ('api_key_usage_daily','SELECT','nelvyon_web_app'),
    ('api_keys','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('apollo_results','INSERT','nelvyon_web_app'),
    ('appbuilderwhitelabel_results','INSERT','nelvyon_web_app'),
    ('arquitectura_results','INSERT','nelvyon_web_app'),
    ('artenft_results','INSERT','nelvyon_web_app'),
    ('attribution_reports','INSERT','nelvyon_web_app'),
    ('attribution_touchpoints','INSERT, SELECT','nelvyon_web_app'),
    ('audiovisual_results','INSERT','nelvyon_web_app'),
    ('audit_log','INSERT','nelvyon_web_app'),
    ('audit_logs','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('autoprocesos_results','INSERT','nelvyon_web_app'),
    ('b2b_results','INSERT','nelvyon_web_app'),
    ('backupdisasterrecovery_results','INSERT','nelvyon_web_app'),
    ('badges_results','INSERT','nelvyon_web_app'),
    ('billing_results','INSERT','nelvyon_web_app'),
    ('bingads_results','INSERT','nelvyon_web_app'),
    ('booking_availability','INSERT, SELECT','nelvyon_web_app'),
    ('bookingcalendario_results','INSERT','nelvyon_web_app'),
    ('bookings','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('branding_results','INSERT','nelvyon_web_app'),
    ('calendar_events','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('cdp_results','INSERT','nelvyon_web_app'),
    ('changelog_entries','SELECT','nelvyon_web_app'),
    ('chatbot_configs','INSERT, SELECT','nelvyon_web_app'),
    ('chatbot_conversations','INSERT, SELECT','nelvyon_web_app'),
    ('chatwidget_results','INSERT','nelvyon_web_app'),
    ('churn_results','INSERT','nelvyon_web_app'),
    ('ciberseguridad_results','INSERT','nelvyon_web_app'),
    ('client_briefings','INSERT, SELECT','nelvyon_web_app'),
    ('client_profiles','INSERT, SELECT','nelvyon_web_app'),
    ('cold_email_campaigns','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('cold_email_prospects','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('communities','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('community_posts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('community_results','INSERT','nelvyon_web_app'),
    ('comparator_results','INSERT','nelvyon_web_app'),
    ('competitive_rt_results','INSERT','nelvyon_web_app'),
    ('compliance_results','INSERT','nelvyon_web_app'),
    ('consultoria_results','INSERT','nelvyon_web_app'),
    ('contabilidad_results','INSERT','nelvyon_web_app'),
    ('contactenrichmentmasivo_results','INSERT','nelvyon_web_app'),
    ('contacts','INSERT, SELECT','nelvyon_web_app'),
    ('contentscore_results','INSERT','nelvyon_web_app'),
    ('copywriting_results','INSERT','nelvyon_web_app'),
    ('countdown_timers','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('creative_assets','INSERT','nelvyon_web_app'),
    ('creative_results','INSERT','nelvyon_web_app'),
    ('crm_activities','INSERT, SELECT','nelvyon_web_app'),
    ('crm_contacts','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('crm_deals','SELECT','nelvyon_web_app'),
    ('crypto_results','INSERT','nelvyon_web_app'),
    ('custom_object_records','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('custom_objects','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('customerjourney_results','INSERT','nelvyon_web_app'),
    ('customersuccess_results','INSERT','nelvyon_web_app'),
    ('databaseimport_results','INSERT','nelvyon_web_app'),
    ('deals','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('demo_results','INSERT','nelvyon_web_app'),
    ('deporte_results','INSERT','nelvyon_web_app'),
    ('dialer_results','INSERT','nelvyon_web_app'),
    ('digital_contracts','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('disenoweb_results','INSERT','nelvyon_web_app'),
    ('documents','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('dragdrop_workflows','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('dunning_log','INSERT, SELECT','nelvyon_web_app'),
    ('early_adopter_config','SELECT, UPDATE','nelvyon_web_app'),
    ('ecommerce_results','INSERT','nelvyon_web_app'),
    ('ecommerceconv_results','INSERT','nelvyon_web_app'),
    ('email_marketing_results','INSERT','nelvyon_web_app'),
    ('email_queue','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('energia_results','INSERT','nelvyon_web_app'),
    ('enterprisequalitycalibration_results','INSERT','nelvyon_web_app'),
    ('erp_audit_events','INSERT','nelvyon_web_app'),
    ('erp_domain_snapshots','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('erp_inventory_products','INSERT, SELECT','nelvyon_web_app'),
    ('erp_manufacturing_orders','INSERT, SELECT','nelvyon_web_app'),
    ('erp_purchase_orders','INSERT, SELECT','nelvyon_web_app'),
    ('erp_suppliers','INSERT, SELECT','nelvyon_web_app'),
    ('erp_warehouses','INSERT, SELECT','nelvyon_web_app'),
    ('estetica_results','INSERT','nelvyon_web_app'),
    ('eventos_results','INSERT','nelvyon_web_app'),
    ('experiencemanagement_results','INSERT','nelvyon_web_app'),
    ('feedback_items','INSERT, SELECT','nelvyon_web_app'),
    ('fintech_results','INSERT','nelvyon_web_app'),
    ('firstparty_results','INSERT','nelvyon_web_app'),
    ('fiscalbilling_results','INSERT','nelvyon_web_app'),
    ('formulariosencuestas_results','INSERT','nelvyon_web_app'),
    ('fotografia_results','INSERT','nelvyon_web_app'),
    ('franquicias_results','INSERT','nelvyon_web_app'),
    ('funnelmultipaso_results','INSERT','nelvyon_web_app'),
    ('gaming_results','INSERT','nelvyon_web_app'),
    ('gbp_reviews','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('gcalzoom_results','INSERT','nelvyon_web_app'),
    ('generated_logos','INSERT, SELECT','nelvyon_web_app'),
    ('geo_ai_checks','INSERT, SELECT','nelvyon_web_app'),
    ('geo_ai_scores','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('geoengine_results','INSERT','nelvyon_web_app'),
    ('gobierno_results','INSERT','nelvyon_web_app'),
    ('growthhacking_results','INSERT','nelvyon_web_app'),
    ('heatmap_alerts','INSERT, SELECT','nelvyon_web_app'),
    ('heatmap_events','INSERT, SELECT','nelvyon_web_app'),
    ('heatmap_sessions','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('heatmap_sites','INSERT, SELECT','nelvyon_web_app'),
    ('helpdesk_tickets','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('helpdeskomnichannel_results','INSERT','nelvyon_web_app'),
    ('hipaacompliance_results','INSERT','nelvyon_web_app'),
    ('hospitality_results','INSERT','nelvyon_web_app'),
    ('hrtech_results','INSERT','nelvyon_web_app'),
    ('iapredictiva_results','INSERT','nelvyon_web_app'),
    ('imagenes_results','INSERT','nelvyon_web_app'),
    ('incidents','SELECT','nelvyon_web_app'),
    ('influencer_results','INSERT','nelvyon_web_app'),
    ('influencers_results','INSERT','nelvyon_web_app'),
    ('inmobiliariacomercial_results','INSERT','nelvyon_web_app'),
    ('integracionesnativas_results','INSERT','nelvyon_web_app'),
    ('integration_ga4','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_google_ads','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_linkedin_ads','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_meta_ads','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_search_console','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_semrush','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_shopify','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_telegram','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_tiktok_ads','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_twilio','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('integration_whatsapp','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('intent_actions','INSERT, SELECT','nelvyon_web_app'),
    ('intent_signals','INSERT, SELECT','nelvyon_web_app'),
    ('investigador_results','INSERT','nelvyon_web_app'),
    ('invoices','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('klaviyo_results','INSERT','nelvyon_web_app'),
    ('knowledgebaseai_results','INSERT','nelvyon_web_app'),
    ('landing_analytics','SELECT','nelvyon_web_app'),
    ('landing_pages','SELECT','nelvyon_web_app'),
    ('landing_results','INSERT','nelvyon_web_app'),
    ('leadenrich_results','INSERT','nelvyon_web_app'),
    ('leaderboard_results','INSERT','nelvyon_web_app'),
    ('local_ai_ingest_jobs','INSERT','nelvyon_web_app'),
    ('local_ai_memory','INSERT, SELECT','nelvyon_web_app'),
    ('local_ai_rag_chunks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('local_ai_rag_documents','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('manufactura_results','INSERT','nelvyon_web_app'),
    ('marca_results','INSERT','nelvyon_web_app'),
    ('marketing_leads','INSERT','nelvyon_web_app'),
    ('marketplace_results','INSERT','nelvyon_web_app'),
    ('membershipportalwhitelabel_results','INSERT','nelvyon_web_app'),
    ('membresiacursos_results','INSERT','nelvyon_web_app'),
    ('mfa_results','INSERT','nelvyon_web_app'),
    ('mobile_results','INSERT','nelvyon_web_app'),
    ('multicurrency_results','INSERT','nelvyon_web_app'),
    ('multiidiomaautomatico_results','INSERT','nelvyon_web_app'),
    ('multimodal_results','INSERT','nelvyon_web_app'),
    ('nelvyon_campaigns','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('nelvyon_clients','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('nelvyon_pack_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('nelvyon_projects','SELECT','nelvyon_web_app'),
    ('nelvyon_rag_chunks','SELECT','nelvyon_web_app'),
    ('nelvyon_users','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('neuromarketing_results','INSERT','nelvyon_web_app'),
    ('newsletter_results','INSERT','nelvyon_web_app'),
    ('nps_responses','INSERT, SELECT','nelvyon_web_app'),
    ('oauth_connections','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('oauth_tokens','SELECT, UPDATE','nelvyon_web_app'),
    ('observability_results','INSERT','nelvyon_web_app'),
    ('okrmanagement_results','INSERT','nelvyon_web_app'),
    ('onboarding','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('onboarding_results','INSERT','nelvyon_web_app'),
    ('optimizador_results','INSERT','nelvyon_web_app'),
    ('os_agent_audit_events','INSERT, SELECT','nelvyon_web_app'),
    ('os_agent_data_cache','INSERT, SELECT','nelvyon_web_app'),
    ('os_assets','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('os_brief_diff_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_clients','INSERT, SELECT','nelvyon_web_app'),
    ('os_competitor_gap_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_cron_logs','INSERT','nelvyon_web_app'),
    ('os_deliverable_approval_tokens','INSERT, UPDATE','nelvyon_web_app'),
    ('os_deliverable_reviews','INSERT','nelvyon_web_app'),
    ('os_deliverables','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_delivery_certificates','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_envato_seed_registry','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_health_reports','INSERT','nelvyon_web_app'),
    ('os_job_results','SELECT, UPDATE','nelvyon_web_app'),
    ('os_jobs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_learning_run_log','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_pack_certifications','INSERT, SELECT','nelvyon_web_app'),
    ('os_pack_gate_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_portal_invites','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_portal_users','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_projects','INSERT, SELECT','nelvyon_web_app'),
    ('os_qa_audit_runs','INSERT, SELECT','nelvyon_web_app'),
    ('os_qa_review_queue','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_recurring_run_log','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('os_reports','INSERT, SELECT','nelvyon_web_app'),
    ('os_retainer_cycles','INSERT, SELECT','nelvyon_web_app'),
    ('os_sector_certifications','INSERT, SELECT','nelvyon_web_app'),
    ('os_sector_readiness','INSERT, SELECT','nelvyon_web_app'),
    ('os_sector_shield_audits','INSERT, SELECT','nelvyon_web_app'),
    ('os_seed_weights','INSERT, SELECT','nelvyon_web_app'),
    ('os_service_catalog','SELECT','nelvyon_web_app'),
    ('os_service_contracts','SELECT','nelvyon_web_app'),
    ('os_template_dna_scores','INSERT, SELECT','nelvyon_web_app'),
    ('os_truth_guard_audits','INSERT, SELECT','nelvyon_web_app'),
    ('os_upsell_suggestions','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('outboundb2b_results','INSERT','nelvyon_web_app'),
    ('partner_client_billing','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('partner_rebilling_ledger','INSERT, SELECT','nelvyon_web_app'),
    ('partner_stripe_accounts','INSERT, SELECT','nelvyon_web_app'),
    ('partnership_results','INSERT','nelvyon_web_app'),
    ('payment_results','INSERT','nelvyon_web_app'),
    ('perfpredictor_results','INSERT','nelvyon_web_app'),
    ('personalizacionmasiva_results','INSERT','nelvyon_web_app'),
    ('pinterestads_results','INSERT','nelvyon_web_app'),
    ('pipeline_deals','SELECT','nelvyon_web_app'),
    ('podcast_results','INSERT','nelvyon_web_app'),
    ('podcasts_results','INSERT','nelvyon_web_app'),
    ('prestashop_results','INSERT','nelvyon_web_app'),
    ('pricingdinamico_results','INSERT','nelvyon_web_app'),
    ('productanalytics_results','INSERT','nelvyon_web_app'),
    ('products','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('proteccionip_results','INSERT','nelvyon_web_app'),
    ('publicapi_results','INSERT','nelvyon_web_app'),
    ('push_results','INSERT','nelvyon_web_app'),
    ('pwa_results','INSERT','nelvyon_web_app'),
    ('qr_codes','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('qrcodegenerator_results','INSERT','nelvyon_web_app'),
    ('quality_scores','INSERT, SELECT','nelvyon_web_app'),
    ('ratelimit_results','INSERT','nelvyon_web_app'),
    ('realestate_results','INSERT','nelvyon_web_app'),
    ('realtime_results','INSERT','nelvyon_web_app'),
    ('referral_results','INSERT','nelvyon_web_app'),
    ('reporting_results','INSERT','nelvyon_web_app'),
    ('restaurantes_results','INSERT','nelvyon_web_app'),
    ('retail_results','INSERT','nelvyon_web_app'),
    ('revenueintelligence_results','INSERT','nelvyon_web_app'),
    ('reviews_results','INSERT','nelvyon_web_app'),
    ('roadmap_items','SELECT','nelvyon_web_app'),
    ('roi_conversions','INSERT, SELECT','nelvyon_web_app'),
    ('roi_events','INSERT, SELECT','nelvyon_web_app'),
    ('roi_loops','INSERT, UPDATE','nelvyon_web_app'),
    ('roi_prediction_results','INSERT, SELECT','nelvyon_web_app'),
    ('roi_predictions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_activation_checklist','INSERT, SELECT','nelvyon_web_app'),
    ('saas_activity_log','INSERT, SELECT','nelvyon_web_app'),
    ('saas_ads_campaign_links','INSERT, SELECT','nelvyon_web_app'),
    ('saas_ads_connections','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_ads_metrics_cache','INSERT, SELECT','nelvyon_web_app'),
    ('saas_ads_optimizer_rules','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_affiliate_commissions','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_affiliate_links','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_affiliate_programs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_agent_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_api_keys','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_api_usage','INSERT, SELECT','nelvyon_web_app'),
    ('saas_appointments','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_approval_channel_settings','INSERT, SELECT','nelvyon_web_app'),
    ('saas_autopilot_settings','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_benchmark_snapshots','INSERT, SELECT','nelvyon_web_app'),
    ('saas_campania_recipients','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_campanias','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_ceo_brief_runs','INSERT, SELECT','nelvyon_web_app'),
    ('saas_ceo_brief_settings','INSERT, SELECT','nelvyon_web_app'),
    ('saas_chat_messages','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_client_profiles','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_compliance_vault','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_connect_rebilling','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_contact_activities','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_contacts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_contracts','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_conversation_messages','INSERT, SELECT','nelvyon_web_app'),
    ('saas_conversations','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_crm_sync_state','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_crm_territories','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_custom_roles','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_data_playbook_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_data_playbooks','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_deals','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_deliverability_snapshots','INSERT, SELECT','nelvyon_web_app'),
    ('saas_deliverable_links','INSERT, SELECT','nelvyon_web_app'),
    ('saas_deliverable_revenue','INSERT, SELECT','nelvyon_web_app'),
    ('saas_dunning_events','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_exchange_rates','INSERT, SELECT','nelvyon_web_app'),
    ('saas_form_submissions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_forms','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_funnel_events','INSERT','nelvyon_web_app'),
    ('saas_funnel_step_variants','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_funnel_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_funnels','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_gdpr_requests','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_geo_visibility_runs','INSERT, SELECT','nelvyon_web_app'),
    ('saas_helpdesk_macros','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_helpdesk_messages','INSERT, SELECT','nelvyon_web_app'),
    ('saas_helpdesk_tickets','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_hubspot_sync_state','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_inbox_agent_settings','INSERT, SELECT','nelvyon_web_app'),
    ('saas_inbox_agent_suggestions','INSERT, UPDATE','nelvyon_web_app'),
    ('saas_inbox_routing','INSERT, SELECT','nelvyon_web_app'),
    ('saas_inbox_sla_policies','INSERT, SELECT','nelvyon_web_app'),
    ('saas_integration_connections','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_invoices','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_kb_articles','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_kb_categories','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_lead_attribution','INSERT, SELECT','nelvyon_web_app'),
    ('saas_lead_scores','INSERT, SELECT','nelvyon_web_app'),
    ('saas_lead_scoring_rules','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_certificates','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_courses','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_enrollments','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_lessons','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_modules','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_lms_progress','INSERT, SELECT','nelvyon_web_app'),
    ('saas_loyalty_balances','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_loyalty_programs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_loyalty_transactions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_marketplace_apps','SELECT, UPDATE','nelvyon_web_app'),
    ('saas_mcp_tool_audit','INSERT','nelvyon_web_app'),
    ('saas_member_custom_roles','INSERT, SELECT','nelvyon_web_app'),
    ('saas_membership_access','INSERT, SELECT','nelvyon_web_app'),
    ('saas_membership_members','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_membership_plans','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_notifications','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_pack_entitlements','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_pack_launches','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_partner_referrals','INSERT, SELECT','nelvyon_web_app'),
    ('saas_partner_retail_prices','INSERT, SELECT','nelvyon_web_app'),
    ('saas_partners','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_playbook_actions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_playbooks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_private_ai_approvals','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_private_ai_audit','INSERT, SELECT','nelvyon_web_app'),
    ('saas_private_ai_settings','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_profile_changelog','INSERT, SELECT','nelvyon_web_app'),
    ('saas_projects_erp','INSERT, SELECT','nelvyon_web_app'),
    ('saas_prospecting_lists','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_prospecting_prospects','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_prospecting_searches','INSERT, UPDATE','nelvyon_web_app'),
    ('saas_pwa_installs','INSERT, SELECT','nelvyon_web_app'),
    ('saas_pwa_push_queue','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_pwa_push_subscriptions','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_quote_items','INSERT, SELECT','nelvyon_web_app'),
    ('saas_quote_sequences','INSERT','nelvyon_web_app'),
    ('saas_quotes','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_recurring_deliverables','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_reports','INSERT, SELECT','nelvyon_web_app'),
    ('saas_sandbox_tenants','INSERT, SELECT','nelvyon_web_app'),
    ('saas_seo_tracked_keywords','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_sequence_enrollments','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_sequence_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_sequences','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_service_results','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_shared_memory_audit','INSERT','nelvyon_web_app'),
    ('saas_shared_memory_entries','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_sms_log','INSERT, SELECT','nelvyon_web_app'),
    ('saas_social_accounts','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_social_posts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_social_proof_drafts','INSERT, SELECT','nelvyon_web_app'),
    ('saas_sso_configs','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_sso_identities','INSERT, SELECT','nelvyon_web_app'),
    ('saas_stage_probabilities','INSERT, SELECT','nelvyon_web_app'),
    ('saas_stripe_meter_items','INSERT, SELECT','nelvyon_web_app'),
    ('saas_subcuenta_meter_daily','INSERT, SELECT','nelvyon_web_app'),
    ('saas_subcuentas','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_tenant_installed_apps','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_tenant_ip_allowlist','INSERT, SELECT','nelvyon_web_app'),
    ('saas_tenant_memory_chunks','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_tenant_memory_settings','INSERT, SELECT','nelvyon_web_app'),
    ('saas_tenants','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_twilio_a2p_registrations','INSERT, SELECT','nelvyon_web_app'),
    ('saas_twilio_rebilling_ledger','INSERT, SELECT','nelvyon_web_app'),
    ('saas_usage_meter_daily','INSERT, SELECT','nelvyon_web_app'),
    ('saas_user_mfa','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_utm_clicks','INSERT, SELECT','nelvyon_web_app'),
    ('saas_utm_links','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_voice_commands','INSERT, SELECT','nelvyon_web_app'),
    ('saas_wa_catalog_products','INSERT, SELECT','nelvyon_web_app'),
    ('saas_wa_settings','SELECT','nelvyon_web_app'),
    ('saas_wa_templates','INSERT, SELECT','nelvyon_web_app'),
    ('saas_web_page_versions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_web_pages','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_webhook_failures','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_whitelabel_configs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_workflow_recipes','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('saas_workflow_runs','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saas_workflow_versions','INSERT, SELECT','nelvyon_web_app'),
    ('saas_workflows','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('saasb2b_results','INSERT','nelvyon_web_app'),
    ('salesintelligence_results','INSERT','nelvyon_web_app'),
    ('scaling_results','INSERT','nelvyon_web_app'),
    ('seguridadcodigo_results','INSERT','nelvyon_web_app'),
    ('seguros_results','INSERT','nelvyon_web_app'),
    ('sentiment_alerts','INSERT, SELECT','nelvyon_web_app'),
    ('sentiment_mentions','INSERT, SELECT','nelvyon_web_app'),
    ('seo_results','INSERT','nelvyon_web_app'),
    ('sessionreplay_results','INSERT','nelvyon_web_app'),
    ('sla_results','INSERT','nelvyon_web_app'),
    ('slack_results','INSERT','nelvyon_web_app'),
    ('snippets','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('social_results','INSERT','nelvyon_web_app'),
    ('social_share_results','INSERT','nelvyon_web_app'),
    ('sociallisteningbrand_results','INSERT','nelvyon_web_app'),
    ('socialvideo_results','INSERT','nelvyon_web_app'),
    ('sports_results','INSERT','nelvyon_web_app'),
    ('status_checks','DELETE, INSERT, SELECT','nelvyon_web_app'),
    ('store_order_items','INSERT, SELECT','nelvyon_web_app'),
    ('store_orders','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('store_settings','INSERT, SELECT','nelvyon_web_app'),
    ('stripe_webhook_events','INSERT, UPDATE','nelvyon_web_app'),
    ('subscriptions','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('superiorabtesting_results','INSERT','nelvyon_web_app'),
    ('superiorattribution_results','INSERT','nelvyon_web_app'),
    ('superiorchurn_results','INSERT','nelvyon_web_app'),
    ('superiorcompetitive_results','INSERT','nelvyon_web_app'),
    ('superiorcontentai_results','INSERT','nelvyon_web_app'),
    ('superiorcrm_results','INSERT','nelvyon_web_app'),
    ('superioremail_results','INSERT','nelvyon_web_app'),
    ('superiorinfluencer_results','INSERT','nelvyon_web_app'),
    ('superiorlandingpage_results','INSERT','nelvyon_web_app'),
    ('superiorleadenrichment_results','INSERT','nelvyon_web_app'),
    ('superiorperformance_results','INSERT','nelvyon_web_app'),
    ('superiorreporting_results','INSERT','nelvyon_web_app'),
    ('superiorreviews_results','INSERT','nelvyon_web_app'),
    ('superiorseo_results','INSERT','nelvyon_web_app'),
    ('superiorsocialmedia_results','INSERT','nelvyon_web_app'),
    ('support_templates','SELECT','nelvyon_web_app'),
    ('support_tickets','INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('survey_responses','INSERT, SELECT','nelvyon_web_app'),
    ('surveys','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('team_members','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('technicalseoaudit_results','INSERT','nelvyon_web_app'),
    ('telecomunicaciones_results','INSERT','nelvyon_web_app'),
    ('telegram_messages','INSERT, SELECT','nelvyon_web_app'),
    ('template_outcomes','INSERT, SELECT','nelvyon_web_app'),
    ('testimonials_results','INSERT','nelvyon_web_app'),
    ('timezone_results','INSERT','nelvyon_web_app'),
    ('transcriptions','INSERT, SELECT','nelvyon_web_app'),
    ('transporte_results','INSERT','nelvyon_web_app'),
    ('twilio_messages','INSERT, SELECT','nelvyon_web_app'),
    ('uiux_results','INSERT','nelvyon_web_app'),
    ('uptime_checks','INSERT, SELECT','nelvyon_web_app'),
    ('uptime_incidents','SELECT','nelvyon_web_app'),
    ('usage_events','INSERT, SELECT','nelvyon_web_app'),
    ('usage_limits','SELECT','nelvyon_web_app'),
    ('user_roles','SELECT','nelvyon_web_app'),
    ('video_enhancements','INSERT, SELECT','nelvyon_web_app'),
    ('videomarketing_results','INSERT','nelvyon_web_app'),
    ('voiceagent_results','INSERT','nelvyon_web_app'),
    ('voicev10_results','INSERT','nelvyon_web_app'),
    ('voicev2_results','INSERT','nelvyon_web_app'),
    ('voicev3_results','INSERT','nelvyon_web_app'),
    ('voicev4_results','INSERT','nelvyon_web_app'),
    ('voicev5_results','INSERT','nelvyon_web_app'),
    ('voicev6_results','INSERT','nelvyon_web_app'),
    ('voicev7_results','INSERT','nelvyon_web_app'),
    ('voicev8_results','INSERT','nelvyon_web_app'),
    ('voicev9_results','INSERT','nelvyon_web_app'),
    ('waitlist','INSERT','nelvyon_web_app'),
    ('web3d_results','INSERT','nelvyon_web_app'),
    ('webhook_deliveries','INSERT, SELECT','nelvyon_web_app'),
    ('webhooks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_app'),
    ('webinar_results','INSERT','nelvyon_web_app'),
    ('webs3d_results','INSERT','nelvyon_web_app'),
    ('whatsapp_messages','INSERT, SELECT','nelvyon_web_app'),
    ('widget_results','INSERT','nelvyon_web_app'),
    ('woocommerce_results','INSERT','nelvyon_web_app'),
    ('workflow_results','INSERT','nelvyon_web_app'),
    ('workspace_members','INSERT, SELECT','nelvyon_web_app'),
    ('workspaces','INSERT, SELECT','nelvyon_web_app'),
    ('youtubeads_results','INSERT','nelvyon_web_app'),
    ('youtubers_results','INSERT','nelvyon_web_app'),
    ('zapier_results','INSERT','nelvyon_web_app'),
    ('_migrations','SELECT','nelvyon_web_jobs'),
    ('ab_experiments','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('ab_tests','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('ab_variants','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('admin_metrics_cache','INSERT','nelvyon_web_jobs'),
    ('ads_results','INSERT','nelvyon_web_jobs'),
    ('affiliate_clicks','INSERT','nelvyon_web_jobs'),
    ('affiliate_conversions','INSERT, SELECT','nelvyon_web_jobs'),
    ('affiliate_profiles','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('agenciasmarketing_results','INSERT','nelvyon_web_jobs'),
    ('agencycert_results','INSERT','nelvyon_web_jobs'),
    ('agent_feedback','INSERT, SELECT','nelvyon_web_jobs'),
    ('agent_outcomes','INSERT, SELECT','nelvyon_web_jobs'),
    ('agent_quality_scores','INSERT, SELECT','nelvyon_web_jobs'),
    ('animacion_results','INSERT','nelvyon_web_jobs'),
    ('antigeneric_results','INSERT','nelvyon_web_jobs'),
    ('api_key_usage_daily','SELECT','nelvyon_web_jobs'),
    ('api_keys','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('apollo_results','INSERT','nelvyon_web_jobs'),
    ('appbuilderwhitelabel_results','INSERT','nelvyon_web_jobs'),
    ('arquitectura_results','INSERT','nelvyon_web_jobs'),
    ('artenft_results','INSERT','nelvyon_web_jobs'),
    ('attribution_reports','INSERT','nelvyon_web_jobs'),
    ('attribution_touchpoints','INSERT, SELECT','nelvyon_web_jobs'),
    ('audiovisual_results','INSERT','nelvyon_web_jobs'),
    ('audit_log','INSERT','nelvyon_web_jobs'),
    ('audit_logs','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('autoprocesos_results','INSERT','nelvyon_web_jobs'),
    ('b2b_results','INSERT','nelvyon_web_jobs'),
    ('backupdisasterrecovery_results','INSERT','nelvyon_web_jobs'),
    ('badges_results','INSERT','nelvyon_web_jobs'),
    ('billing_results','INSERT','nelvyon_web_jobs'),
    ('bingads_results','INSERT','nelvyon_web_jobs'),
    ('booking_availability','INSERT, SELECT','nelvyon_web_jobs'),
    ('bookingcalendario_results','INSERT','nelvyon_web_jobs'),
    ('bookings','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('branding_results','INSERT','nelvyon_web_jobs'),
    ('calendar_events','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('cdp_results','INSERT','nelvyon_web_jobs'),
    ('changelog_entries','SELECT','nelvyon_web_jobs'),
    ('chatbot_configs','INSERT, SELECT','nelvyon_web_jobs'),
    ('chatbot_conversations','INSERT, SELECT','nelvyon_web_jobs'),
    ('chatwidget_results','INSERT','nelvyon_web_jobs'),
    ('churn_results','INSERT','nelvyon_web_jobs'),
    ('ciberseguridad_results','INSERT','nelvyon_web_jobs'),
    ('client_briefings','INSERT, SELECT','nelvyon_web_jobs'),
    ('client_profiles','INSERT, SELECT','nelvyon_web_jobs'),
    ('cold_email_campaigns','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('cold_email_prospects','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('communities','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('community_posts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('community_results','INSERT','nelvyon_web_jobs'),
    ('comparator_results','INSERT','nelvyon_web_jobs'),
    ('competitive_rt_results','INSERT','nelvyon_web_jobs'),
    ('compliance_results','INSERT','nelvyon_web_jobs'),
    ('consultoria_results','INSERT','nelvyon_web_jobs'),
    ('contabilidad_results','INSERT','nelvyon_web_jobs'),
    ('contactenrichmentmasivo_results','INSERT','nelvyon_web_jobs'),
    ('contacts','INSERT, SELECT','nelvyon_web_jobs'),
    ('contentscore_results','INSERT','nelvyon_web_jobs'),
    ('copywriting_results','INSERT','nelvyon_web_jobs'),
    ('countdown_timers','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('creative_assets','INSERT','nelvyon_web_jobs'),
    ('creative_results','INSERT','nelvyon_web_jobs'),
    ('crm_activities','INSERT, SELECT','nelvyon_web_jobs'),
    ('crm_contacts','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('crm_deals','SELECT','nelvyon_web_jobs'),
    ('crypto_results','INSERT','nelvyon_web_jobs'),
    ('custom_object_records','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('custom_objects','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('customerjourney_results','INSERT','nelvyon_web_jobs'),
    ('customersuccess_results','INSERT','nelvyon_web_jobs'),
    ('databaseimport_results','INSERT','nelvyon_web_jobs'),
    ('deals','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('demo_results','INSERT','nelvyon_web_jobs'),
    ('deporte_results','INSERT','nelvyon_web_jobs'),
    ('dialer_results','INSERT','nelvyon_web_jobs'),
    ('digital_contracts','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('disenoweb_results','INSERT','nelvyon_web_jobs'),
    ('documents','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('dragdrop_workflows','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('dunning_log','INSERT, SELECT','nelvyon_web_jobs'),
    ('early_adopter_config','SELECT, UPDATE','nelvyon_web_jobs'),
    ('ecommerce_results','INSERT','nelvyon_web_jobs'),
    ('ecommerceconv_results','INSERT','nelvyon_web_jobs'),
    ('email_marketing_results','INSERT','nelvyon_web_jobs'),
    ('email_queue','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('energia_results','INSERT','nelvyon_web_jobs'),
    ('enterprisequalitycalibration_results','INSERT','nelvyon_web_jobs'),
    ('erp_audit_events','INSERT','nelvyon_web_jobs'),
    ('erp_domain_snapshots','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('erp_inventory_products','INSERT, SELECT','nelvyon_web_jobs'),
    ('erp_manufacturing_orders','INSERT, SELECT','nelvyon_web_jobs'),
    ('erp_purchase_orders','INSERT, SELECT','nelvyon_web_jobs'),
    ('erp_suppliers','INSERT, SELECT','nelvyon_web_jobs'),
    ('erp_warehouses','INSERT, SELECT','nelvyon_web_jobs'),
    ('estetica_results','INSERT','nelvyon_web_jobs'),
    ('eventos_results','INSERT','nelvyon_web_jobs'),
    ('experiencemanagement_results','INSERT','nelvyon_web_jobs'),
    ('feedback_items','INSERT, SELECT','nelvyon_web_jobs'),
    ('fintech_results','INSERT','nelvyon_web_jobs'),
    ('firstparty_results','INSERT','nelvyon_web_jobs'),
    ('fiscalbilling_results','INSERT','nelvyon_web_jobs'),
    ('formulariosencuestas_results','INSERT','nelvyon_web_jobs'),
    ('fotografia_results','INSERT','nelvyon_web_jobs'),
    ('franquicias_results','INSERT','nelvyon_web_jobs'),
    ('funnelmultipaso_results','INSERT','nelvyon_web_jobs'),
    ('gaming_results','INSERT','nelvyon_web_jobs'),
    ('gbp_reviews','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('gcalzoom_results','INSERT','nelvyon_web_jobs'),
    ('generated_logos','INSERT, SELECT','nelvyon_web_jobs'),
    ('geo_ai_checks','INSERT, SELECT','nelvyon_web_jobs'),
    ('geo_ai_scores','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('geoengine_results','INSERT','nelvyon_web_jobs'),
    ('gobierno_results','INSERT','nelvyon_web_jobs'),
    ('growthhacking_results','INSERT','nelvyon_web_jobs'),
    ('heatmap_alerts','INSERT, SELECT','nelvyon_web_jobs'),
    ('heatmap_events','INSERT, SELECT','nelvyon_web_jobs'),
    ('heatmap_sessions','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('heatmap_sites','INSERT, SELECT','nelvyon_web_jobs'),
    ('helpdesk_tickets','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('helpdeskomnichannel_results','INSERT','nelvyon_web_jobs'),
    ('hipaacompliance_results','INSERT','nelvyon_web_jobs'),
    ('hospitality_results','INSERT','nelvyon_web_jobs'),
    ('hrtech_results','INSERT','nelvyon_web_jobs'),
    ('iapredictiva_results','INSERT','nelvyon_web_jobs'),
    ('imagenes_results','INSERT','nelvyon_web_jobs'),
    ('incidents','SELECT','nelvyon_web_jobs'),
    ('influencer_results','INSERT','nelvyon_web_jobs'),
    ('influencers_results','INSERT','nelvyon_web_jobs'),
    ('inmobiliariacomercial_results','INSERT','nelvyon_web_jobs'),
    ('integracionesnativas_results','INSERT','nelvyon_web_jobs'),
    ('integration_ga4','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_google_ads','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_linkedin_ads','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_meta_ads','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_search_console','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_semrush','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_shopify','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_telegram','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_tiktok_ads','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_twilio','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('integration_whatsapp','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('intent_actions','INSERT, SELECT','nelvyon_web_jobs'),
    ('intent_signals','INSERT, SELECT','nelvyon_web_jobs'),
    ('investigador_results','INSERT','nelvyon_web_jobs'),
    ('invoices','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('klaviyo_results','INSERT','nelvyon_web_jobs'),
    ('knowledgebaseai_results','INSERT','nelvyon_web_jobs'),
    ('landing_analytics','SELECT','nelvyon_web_jobs'),
    ('landing_pages','SELECT','nelvyon_web_jobs'),
    ('landing_results','INSERT','nelvyon_web_jobs'),
    ('leadenrich_results','INSERT','nelvyon_web_jobs'),
    ('leaderboard_results','INSERT','nelvyon_web_jobs'),
    ('local_ai_ingest_jobs','INSERT','nelvyon_web_jobs'),
    ('local_ai_memory','INSERT, SELECT','nelvyon_web_jobs'),
    ('local_ai_rag_chunks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('local_ai_rag_documents','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('manufactura_results','INSERT','nelvyon_web_jobs'),
    ('marca_results','INSERT','nelvyon_web_jobs'),
    ('marketing_leads','INSERT','nelvyon_web_jobs'),
    ('marketplace_results','INSERT','nelvyon_web_jobs'),
    ('membershipportalwhitelabel_results','INSERT','nelvyon_web_jobs'),
    ('membresiacursos_results','INSERT','nelvyon_web_jobs'),
    ('mfa_results','INSERT','nelvyon_web_jobs'),
    ('mobile_results','INSERT','nelvyon_web_jobs'),
    ('multicurrency_results','INSERT','nelvyon_web_jobs'),
    ('multiidiomaautomatico_results','INSERT','nelvyon_web_jobs'),
    ('multimodal_results','INSERT','nelvyon_web_jobs'),
    ('nelvyon_campaigns','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('nelvyon_clients','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('nelvyon_pack_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('nelvyon_projects','SELECT','nelvyon_web_jobs'),
    ('nelvyon_rag_chunks','SELECT','nelvyon_web_jobs'),
    ('nelvyon_users','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('neuromarketing_results','INSERT','nelvyon_web_jobs'),
    ('newsletter_results','INSERT','nelvyon_web_jobs'),
    ('nps_responses','INSERT, SELECT','nelvyon_web_jobs'),
    ('oauth_connections','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('oauth_tokens','SELECT, UPDATE','nelvyon_web_jobs'),
    ('observability_results','INSERT','nelvyon_web_jobs'),
    ('okrmanagement_results','INSERT','nelvyon_web_jobs'),
    ('onboarding','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('onboarding_results','INSERT','nelvyon_web_jobs'),
    ('optimizador_results','INSERT','nelvyon_web_jobs'),
    ('os_agent_audit_events','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_agent_data_cache','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_assets','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('os_brief_diff_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_clients','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_competitor_gap_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_cron_logs','INSERT','nelvyon_web_jobs'),
    ('os_deliverable_approval_tokens','INSERT, UPDATE','nelvyon_web_jobs'),
    ('os_deliverable_reviews','INSERT','nelvyon_web_jobs'),
    ('os_deliverables','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_delivery_certificates','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_envato_seed_registry','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_health_reports','INSERT','nelvyon_web_jobs'),
    ('os_job_results','SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_jobs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_learning_run_log','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_pack_certifications','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_pack_gate_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_portal_invites','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_portal_users','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_projects','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_qa_audit_runs','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_qa_review_queue','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_recurring_run_log','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('os_reports','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_retainer_cycles','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_sector_certifications','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_sector_readiness','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_sector_shield_audits','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_seed_weights','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_service_catalog','SELECT','nelvyon_web_jobs'),
    ('os_service_contracts','SELECT','nelvyon_web_jobs'),
    ('os_template_dna_scores','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_truth_guard_audits','INSERT, SELECT','nelvyon_web_jobs'),
    ('os_upsell_suggestions','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('outboundb2b_results','INSERT','nelvyon_web_jobs'),
    ('partner_client_billing','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('partner_rebilling_ledger','INSERT, SELECT','nelvyon_web_jobs'),
    ('partner_stripe_accounts','INSERT, SELECT','nelvyon_web_jobs'),
    ('partnership_results','INSERT','nelvyon_web_jobs'),
    ('payment_results','INSERT','nelvyon_web_jobs'),
    ('perfpredictor_results','INSERT','nelvyon_web_jobs'),
    ('personalizacionmasiva_results','INSERT','nelvyon_web_jobs'),
    ('pinterestads_results','INSERT','nelvyon_web_jobs'),
    ('pipeline_deals','SELECT','nelvyon_web_jobs'),
    ('podcast_results','INSERT','nelvyon_web_jobs'),
    ('podcasts_results','INSERT','nelvyon_web_jobs'),
    ('prestashop_results','INSERT','nelvyon_web_jobs'),
    ('pricingdinamico_results','INSERT','nelvyon_web_jobs'),
    ('productanalytics_results','INSERT','nelvyon_web_jobs'),
    ('products','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('proteccionip_results','INSERT','nelvyon_web_jobs'),
    ('publicapi_results','INSERT','nelvyon_web_jobs'),
    ('push_results','INSERT','nelvyon_web_jobs'),
    ('pwa_results','INSERT','nelvyon_web_jobs'),
    ('qr_codes','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('qrcodegenerator_results','INSERT','nelvyon_web_jobs'),
    ('quality_scores','INSERT, SELECT','nelvyon_web_jobs'),
    ('ratelimit_results','INSERT','nelvyon_web_jobs'),
    ('realestate_results','INSERT','nelvyon_web_jobs'),
    ('realtime_results','INSERT','nelvyon_web_jobs'),
    ('referral_results','INSERT','nelvyon_web_jobs'),
    ('reporting_results','INSERT','nelvyon_web_jobs'),
    ('restaurantes_results','INSERT','nelvyon_web_jobs'),
    ('retail_results','INSERT','nelvyon_web_jobs'),
    ('revenueintelligence_results','INSERT','nelvyon_web_jobs'),
    ('reviews_results','INSERT','nelvyon_web_jobs'),
    ('roadmap_items','SELECT','nelvyon_web_jobs'),
    ('roi_conversions','INSERT, SELECT','nelvyon_web_jobs'),
    ('roi_events','INSERT, SELECT','nelvyon_web_jobs'),
    ('roi_loops','INSERT, UPDATE','nelvyon_web_jobs'),
    ('roi_prediction_results','INSERT, SELECT','nelvyon_web_jobs'),
    ('roi_predictions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_activation_checklist','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_activity_log','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_ads_campaign_links','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_ads_connections','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_ads_metrics_cache','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_ads_optimizer_rules','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_affiliate_commissions','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_affiliate_links','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_affiliate_programs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_agent_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_api_keys','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_api_usage','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_appointments','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_approval_channel_settings','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_autopilot_settings','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_benchmark_snapshots','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_campania_recipients','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_campanias','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_ceo_brief_runs','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_ceo_brief_settings','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_chat_messages','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_client_profiles','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_compliance_vault','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_connect_rebilling','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_contact_activities','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_contacts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_contracts','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_conversation_messages','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_conversations','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_crm_sync_state','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_crm_territories','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_custom_roles','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_data_playbook_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_data_playbooks','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_deals','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_deliverability_snapshots','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_deliverable_links','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_deliverable_revenue','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_dunning_events','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_exchange_rates','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_form_submissions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_forms','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_funnel_events','INSERT','nelvyon_web_jobs'),
    ('saas_funnel_step_variants','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_funnel_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_funnels','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_gdpr_requests','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_geo_visibility_runs','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_helpdesk_macros','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_helpdesk_messages','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_helpdesk_tickets','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_hubspot_sync_state','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_inbox_agent_settings','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_inbox_agent_suggestions','INSERT, UPDATE','nelvyon_web_jobs'),
    ('saas_inbox_routing','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_inbox_sla_policies','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_integration_connections','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_invoices','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_kb_articles','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_kb_categories','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_lead_attribution','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_lead_scores','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_lead_scoring_rules','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_certificates','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_courses','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_enrollments','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_lessons','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_modules','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_lms_progress','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_loyalty_balances','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_loyalty_programs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_loyalty_transactions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_marketplace_apps','SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_mcp_tool_audit','INSERT','nelvyon_web_jobs'),
    ('saas_member_custom_roles','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_membership_access','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_membership_members','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_membership_plans','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_notifications','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_pack_entitlements','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_pack_launches','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_partner_referrals','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_partner_retail_prices','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_partners','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_playbook_actions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_playbooks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_private_ai_approvals','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_private_ai_audit','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_private_ai_settings','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_profile_changelog','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_projects_erp','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_prospecting_lists','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_prospecting_prospects','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_prospecting_searches','INSERT, UPDATE','nelvyon_web_jobs'),
    ('saas_pwa_installs','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_pwa_push_queue','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_pwa_push_subscriptions','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_quote_items','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_quote_sequences','INSERT','nelvyon_web_jobs'),
    ('saas_quotes','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_recurring_deliverables','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_reports','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_sandbox_tenants','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_seo_tracked_keywords','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_sequence_enrollments','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_sequence_steps','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_sequences','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_service_results','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_shared_memory_audit','INSERT','nelvyon_web_jobs'),
    ('saas_shared_memory_entries','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_sms_log','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_social_accounts','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_social_posts','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_social_proof_drafts','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_sso_configs','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_sso_identities','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_stage_probabilities','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_stripe_meter_items','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_subcuenta_meter_daily','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_subcuentas','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_tenant_installed_apps','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_tenant_ip_allowlist','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_tenant_memory_chunks','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_tenant_memory_settings','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_tenants','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_twilio_a2p_registrations','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_twilio_rebilling_ledger','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_usage_meter_daily','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_user_mfa','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_utm_clicks','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_utm_links','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_voice_commands','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_wa_catalog_products','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_wa_settings','SELECT','nelvyon_web_jobs'),
    ('saas_wa_templates','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_web_page_versions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_web_pages','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_webhook_failures','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_whitelabel_configs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_workflow_recipes','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_workflow_runs','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saas_workflow_versions','INSERT, SELECT','nelvyon_web_jobs'),
    ('saas_workflows','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('saasb2b_results','INSERT','nelvyon_web_jobs'),
    ('salesintelligence_results','INSERT','nelvyon_web_jobs'),
    ('scaling_results','INSERT','nelvyon_web_jobs'),
    ('seguridadcodigo_results','INSERT','nelvyon_web_jobs'),
    ('seguros_results','INSERT','nelvyon_web_jobs'),
    ('sentiment_alerts','INSERT, SELECT','nelvyon_web_jobs'),
    ('sentiment_mentions','INSERT, SELECT','nelvyon_web_jobs'),
    ('seo_results','INSERT','nelvyon_web_jobs'),
    ('sessionreplay_results','INSERT','nelvyon_web_jobs'),
    ('sla_results','INSERT','nelvyon_web_jobs'),
    ('slack_results','INSERT','nelvyon_web_jobs'),
    ('snippets','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('social_results','INSERT','nelvyon_web_jobs'),
    ('social_share_results','INSERT','nelvyon_web_jobs'),
    ('sociallisteningbrand_results','INSERT','nelvyon_web_jobs'),
    ('socialvideo_results','INSERT','nelvyon_web_jobs'),
    ('sports_results','INSERT','nelvyon_web_jobs'),
    ('status_checks','DELETE, INSERT, SELECT','nelvyon_web_jobs'),
    ('store_order_items','INSERT, SELECT','nelvyon_web_jobs'),
    ('store_orders','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('store_settings','INSERT, SELECT','nelvyon_web_jobs'),
    ('stripe_webhook_events','INSERT, UPDATE','nelvyon_web_jobs'),
    ('subscriptions','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('superiorabtesting_results','INSERT','nelvyon_web_jobs'),
    ('superiorattribution_results','INSERT','nelvyon_web_jobs'),
    ('superiorchurn_results','INSERT','nelvyon_web_jobs'),
    ('superiorcompetitive_results','INSERT','nelvyon_web_jobs'),
    ('superiorcontentai_results','INSERT','nelvyon_web_jobs'),
    ('superiorcrm_results','INSERT','nelvyon_web_jobs'),
    ('superioremail_results','INSERT','nelvyon_web_jobs'),
    ('superiorinfluencer_results','INSERT','nelvyon_web_jobs'),
    ('superiorlandingpage_results','INSERT','nelvyon_web_jobs'),
    ('superiorleadenrichment_results','INSERT','nelvyon_web_jobs'),
    ('superiorperformance_results','INSERT','nelvyon_web_jobs'),
    ('superiorreporting_results','INSERT','nelvyon_web_jobs'),
    ('superiorreviews_results','INSERT','nelvyon_web_jobs'),
    ('superiorseo_results','INSERT','nelvyon_web_jobs'),
    ('superiorsocialmedia_results','INSERT','nelvyon_web_jobs'),
    ('support_templates','SELECT','nelvyon_web_jobs'),
    ('support_tickets','INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('survey_responses','INSERT, SELECT','nelvyon_web_jobs'),
    ('surveys','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('team_members','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('technicalseoaudit_results','INSERT','nelvyon_web_jobs'),
    ('telecomunicaciones_results','INSERT','nelvyon_web_jobs'),
    ('telegram_messages','INSERT, SELECT','nelvyon_web_jobs'),
    ('template_outcomes','INSERT, SELECT','nelvyon_web_jobs'),
    ('testimonials_results','INSERT','nelvyon_web_jobs'),
    ('timezone_results','INSERT','nelvyon_web_jobs'),
    ('transcriptions','INSERT, SELECT','nelvyon_web_jobs'),
    ('transporte_results','INSERT','nelvyon_web_jobs'),
    ('twilio_messages','INSERT, SELECT','nelvyon_web_jobs'),
    ('uiux_results','INSERT','nelvyon_web_jobs'),
    ('uptime_checks','INSERT, SELECT','nelvyon_web_jobs'),
    ('uptime_incidents','SELECT','nelvyon_web_jobs'),
    ('usage_events','INSERT, SELECT','nelvyon_web_jobs'),
    ('usage_limits','SELECT','nelvyon_web_jobs'),
    ('user_roles','SELECT','nelvyon_web_jobs'),
    ('video_enhancements','INSERT, SELECT','nelvyon_web_jobs'),
    ('videomarketing_results','INSERT','nelvyon_web_jobs'),
    ('voiceagent_results','INSERT','nelvyon_web_jobs'),
    ('voicev10_results','INSERT','nelvyon_web_jobs'),
    ('voicev2_results','INSERT','nelvyon_web_jobs'),
    ('voicev3_results','INSERT','nelvyon_web_jobs'),
    ('voicev4_results','INSERT','nelvyon_web_jobs'),
    ('voicev5_results','INSERT','nelvyon_web_jobs'),
    ('voicev6_results','INSERT','nelvyon_web_jobs'),
    ('voicev7_results','INSERT','nelvyon_web_jobs'),
    ('voicev8_results','INSERT','nelvyon_web_jobs'),
    ('voicev9_results','INSERT','nelvyon_web_jobs'),
    ('waitlist','INSERT','nelvyon_web_jobs'),
    ('web3d_results','INSERT','nelvyon_web_jobs'),
    ('webhook_deliveries','INSERT, SELECT','nelvyon_web_jobs'),
    ('webhooks','DELETE, INSERT, SELECT, UPDATE','nelvyon_web_jobs'),
    ('webinar_results','INSERT','nelvyon_web_jobs'),
    ('webs3d_results','INSERT','nelvyon_web_jobs'),
    ('whatsapp_messages','INSERT, SELECT','nelvyon_web_jobs'),
    ('widget_results','INSERT','nelvyon_web_jobs'),
    ('woocommerce_results','INSERT','nelvyon_web_jobs'),
    ('workflow_results','INSERT','nelvyon_web_jobs'),
    ('workspace_members','INSERT, SELECT','nelvyon_web_jobs'),
    ('workspaces','INSERT, SELECT','nelvyon_web_jobs'),
    ('youtubeads_results','INSERT','nelvyon_web_jobs'),
    ('youtubers_results','INSERT','nelvyon_web_jobs'),
    ('zapier_results','INSERT','nelvyon_web_jobs')
  ) AS t(tabla, privilegios, rol)
  LOOP
    IF to_regclass('public.' || quote_ident(f.tabla)) IS NULL THEN
      omitidas := omitidas + 1;
      CONTINUE;
    END IF;
    EXECUTE format('GRANT %s ON public.%I TO %I', f.privilegios, f.tabla, f.rol);
    aplicadas := aplicadas + 1;
  END LOOP;
  RAISE NOTICE '577: % privilegios concedidos, % omitidos por tabla ausente',
    aplicadas, omitidas;
END $$;

-- ── El fichero se desmiente solo si algo de esto cambia ──
DO $$
DECLARE sobra int;
BEGIN
  SELECT count(*) INTO sobra FROM pg_roles
   WHERE rolname IN ('nelvyon_web_app','nelvyon_web_jobs')
     AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication);
  IF sobra > 0 THEN
    RAISE EXCEPTION '577: un rol del web quedo con privilegios administrativos';
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='nelvyon_web_app' AND rolbypassrls) THEN
    RAISE EXCEPTION '577: nelvyon_web_app salta RLS: el cutover no serviria de nada';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='nelvyon_web_jobs' AND rolbypassrls) THEN
    RAISE EXCEPTION '577: nelvyon_web_jobs NO salta RLS: los crons y los webhooks '
      'devolverian cero filas en vez de trabajar';
  END IF;
END $$;
