/**
 * Certified enterprise workflow catalog — patterns over existing orchestrator agents.
 * Does not create a second orchestrator. Sandbox-executable by agentId lists.
 */

export type WorkflowPattern =
  | "planner_executor_reviewer"
  | "proposer_critic_judge"
  | "execute_validate_rollback"
  | "detect_diagnose_remediate_verify"
  | "supervisor_fanout";

export type WorkforceWorkflowDef = {
  id: string;
  domain: "engineering" | "growth" | "revenue" | "customer" | "ops" | "finance" | "executive";
  title: string;
  pattern: WorkflowPattern;
  agents: string[];
  defaultMode: "observe" | "draft" | "assisted";
  requiresHumanApproval: boolean;
  sloMs: number;
  certified: boolean;
  inputSchema: Record<string, string>;
  outputSchema: Record<string, string>;
};

export const WORKFORCE_WORKFLOWS: WorkforceWorkflowDef[] = [
  // Engineering (Block D)
  {
    id: "eng.feature_change",
    domain: "engineering",
    title: "Cambio de funcionalidad",
    pattern: "planner_executor_reviewer",
    agents: ["cto", "development", "qa"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { brief: "string", scope: "string" },
    outputSchema: { plan: "string", risks: "string[]", nextSteps: "string[]" },
  },
  {
    id: "eng.bug_fix",
    domain: "engineering",
    title: "Reparación de bug",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["development", "qa"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { symptom: "string", repro: "string" },
    outputSchema: { rootCause: "string", fixPlan: "string", verifySteps: "string[]" },
  },
  {
    id: "eng.code_review",
    domain: "engineering",
    title: "Revisión de código",
    pattern: "proposer_critic_judge",
    agents: ["development", "security_compliance", "cto"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { diffSummary: "string" },
    outputSchema: { findings: "string[]", verdict: "string" },
  },
  {
    id: "eng.migration_review",
    domain: "engineering",
    title: "Creación y revisión de migración",
    pattern: "planner_executor_reviewer",
    agents: ["development", "devops", "cto"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { migrationName: "string", ddlIntent: "string" },
    outputSchema: { checklist: "string[]", rollback: "string" },
  },
  {
    id: "eng.security_analysis",
    domain: "engineering",
    title: "Análisis de seguridad",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["security_compliance", "cto"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { surface: "string" },
    outputSchema: { risks: "string[]", remediations: "string[]" },
  },
  {
    id: "eng.dependency_update",
    domain: "engineering",
    title: "Actualización de dependencias",
    pattern: "execute_validate_rollback",
    agents: ["devops", "qa", "security_compliance"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { packages: "string[]" },
    outputSchema: { plan: "string", rollback: "string" },
  },
  {
    id: "eng.e2e_regression",
    domain: "engineering",
    title: "Regresión E2E",
    pattern: "execute_validate_rollback",
    agents: ["qa", "development"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 180_000,
    certified: true,
    inputSchema: { suite: "string" },
    outputSchema: { results: "string", failures: "string[]" },
  },
  {
    id: "eng.incident_investigate",
    domain: "engineering",
    title: "Investigación de incidente",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["devops", "cto", "operations"],
    defaultMode: "assisted",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { alert: "string", impact: "string" },
    outputSchema: { timeline: "string", rca: "string", actions: "string[]" },
  },
  {
    id: "eng.rollback",
    domain: "engineering",
    title: "Rollback",
    pattern: "execute_validate_rollback",
    agents: ["devops", "cto"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 60_000,
    certified: true,
    inputSchema: { releaseId: "string", reason: "string" },
    outputSchema: { steps: "string[]", verification: "string" },
  },
  {
    id: "eng.release_candidate",
    domain: "engineering",
    title: "Release candidate",
    pattern: "planner_executor_reviewer",
    agents: ["cto", "qa", "devops"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { version: "string", changelog: "string" },
    outputSchema: { gateChecklist: "string[]", goNoGo: "string" },
  },
  {
    id: "eng.deploy_sandbox",
    domain: "engineering",
    title: "Despliegue sandbox/staging simulado",
    pattern: "execute_validate_rollback",
    agents: ["devops", "qa"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { target: "sandbox|staging", artifact: "string" },
    outputSchema: { plan: "string", healthChecks: "string[]" },
  },
  {
    id: "eng.perf_audit",
    domain: "engineering",
    title: "Auditoría de rendimiento",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["devops", "development"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { surface: "string", budget: "string" },
    outputSchema: { bottlenecks: "string[]", recommendations: "string[]" },
  },
  {
    id: "eng.backup_validate",
    domain: "engineering",
    title: "Validación de backups",
    pattern: "execute_validate_rollback",
    agents: ["devops", "operations"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { scope: "string" },
    outputSchema: { status: "string", gaps: "string[]" },
  },
  {
    id: "eng.docs_generate",
    domain: "engineering",
    title: "Generación de documentación",
    pattern: "planner_executor_reviewer",
    agents: ["development", "cto"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { topic: "string" },
    outputSchema: { outline: "string", draft: "string" },
  },
  // Growth / Product / Sales (Block E)
  {
    id: "growth.market_analysis",
    domain: "growth",
    title: "Análisis de mercado",
    pattern: "planner_executor_reviewer",
    agents: ["marketing", "product", "reporting"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { segment: "string" },
    outputSchema: { insights: "string[]", opportunities: "string[]" },
  },
  {
    id: "growth.product_strategy",
    domain: "growth",
    title: "Estrategia de producto",
    pattern: "proposer_critic_judge",
    agents: ["product", "cto", "marketing"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { goal: "string" },
    outputSchema: { strategy: "string", bets: "string[]" },
  },
  {
    id: "growth.roadmap",
    domain: "growth",
    title: "Roadmap",
    pattern: "planner_executor_reviewer",
    agents: ["product", "cto", "ceo_supervisor"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { horizon: "string" },
    outputSchema: { themes: "string[]", priorities: "string[]" },
  },
  {
    id: "growth.full_campaign",
    domain: "growth",
    title: "Campaña completa",
    pattern: "supervisor_fanout",
    agents: ["marketing", "content", "email_marketing", "social_media"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { objective: "string", channels: "string[]" },
    outputSchema: { briefs: "string[]", calendar: "string" },
  },
  {
    id: "growth.seo_audit",
    domain: "growth",
    title: "Auditoría SEO",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["seo", "content"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { urlOrBrief: "string" },
    outputSchema: { findings: "string[]", fixes: "string[]" },
  },
  {
    id: "growth.content_create",
    domain: "growth",
    title: "Creación de contenido",
    pattern: "planner_executor_reviewer",
    agents: ["content", "seo", "marketing"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { topic: "string", format: "string" },
    outputSchema: { draft: "string", seoNotes: "string" },
  },
  {
    id: "growth.multichannel_dist",
    domain: "growth",
    title: "Distribución multicanal",
    pattern: "supervisor_fanout",
    agents: ["social_media", "email_marketing", "content"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { asset: "string" },
    outputSchema: { variants: "string[]", schedule: "string" },
  },
  {
    id: "growth.social_calendar",
    domain: "growth",
    title: "Calendario social",
    pattern: "planner_executor_reviewer",
    agents: ["social_media", "marketing"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 60_000,
    certified: true,
    inputSchema: { month: "string" },
    outputSchema: { calendar: "string", themes: "string[]" },
  },
  {
    id: "growth.ads_plan",
    domain: "growth",
    title: "Plan publicidad (sin gasto real)",
    pattern: "proposer_critic_judge",
    agents: ["google_ads", "meta_ads", "tiktok_ads", "marketing"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { objective: "string", budgetSimulated: "number" },
    outputSchema: { strategy: "string", creatives: "string[]", spendGuard: "string" },
  },
  {
    id: "revenue.lead_gen",
    domain: "revenue",
    title: "Lead generation",
    pattern: "planner_executor_reviewer",
    agents: ["sales", "marketing", "crm"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { icp: "string" },
    outputSchema: { channels: "string[]", messaging: "string" },
  },
  {
    id: "revenue.lead_qualify",
    domain: "revenue",
    title: "Lead qualification",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["sales", "crm"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { lead: "string" },
    outputSchema: { score: "string", nextAction: "string" },
  },
  {
    id: "revenue.proposal",
    domain: "revenue",
    title: "Propuesta",
    pattern: "planner_executor_reviewer",
    agents: ["sales", "finance", "product"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { account: "string", package: "string" },
    outputSchema: { proposalOutline: "string", risks: "string[]" },
  },
  {
    id: "revenue.follow_up",
    domain: "revenue",
    title: "Seguimiento",
    pattern: "execute_validate_rollback",
    agents: ["sales", "crm"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 45_000,
    certified: true,
    inputSchema: { dealId: "string" },
    outputSchema: { sequence: "string[]" },
  },
  {
    id: "revenue.crm_update",
    domain: "revenue",
    title: "Actualización CRM",
    pattern: "execute_validate_rollback",
    agents: ["crm", "sales"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 45_000,
    certified: true,
    inputSchema: { contact: "string", fields: "string" },
    outputSchema: { proposedWrites: "string[]", validation: "string" },
  },
  {
    id: "revenue.pipeline_analysis",
    domain: "revenue",
    title: "Análisis de pipeline",
    pattern: "planner_executor_reviewer",
    agents: ["sales", "reporting", "finance"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { period: "string" },
    outputSchema: { stages: "string", risks: "string[]" },
  },
  {
    id: "revenue.revenue_report",
    domain: "revenue",
    title: "Informe de ingresos",
    pattern: "planner_executor_reviewer",
    agents: ["finance", "reporting", "ceo_supervisor"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { period: "string" },
    outputSchema: { summary: "string", kpis: "string[]" },
  },
  {
    id: "growth.competitive",
    domain: "growth",
    title: "Análisis competitivo",
    pattern: "proposer_critic_judge",
    agents: ["marketing", "product", "reporting"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { competitors: "string[]" },
    outputSchema: { matrix: "string", implications: "string[]" },
  },
  // Customer / Ops / Finance / Exec (Block F)
  {
    id: "customer.onboarding",
    domain: "customer",
    title: "Onboarding de cliente",
    pattern: "planner_executor_reviewer",
    agents: ["support", "portal_client", "operations"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { tenant: "string" },
    outputSchema: { checklist: "string[]", risks: "string[]" },
  },
  {
    id: "customer.ticket_resolve",
    domain: "customer",
    title: "Clasificación y resolución de ticket",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["support", "portal_client"],
    defaultMode: "assisted",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { ticket: "string" },
    outputSchema: { triage: "string", replyDraft: "string" },
  },
  {
    id: "customer.tech_escalate",
    domain: "customer",
    title: "Escalado técnico",
    pattern: "supervisor_fanout",
    agents: ["support", "development", "devops"],
    defaultMode: "assisted",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { ticket: "string", severity: "string" },
    outputSchema: { owners: "string[]", plan: "string" },
  },
  {
    id: "customer.churn_detect",
    domain: "customer",
    title: "Detección de churn",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["support", "reporting", "sales"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { account: "string" },
    outputSchema: { risk: "string", signals: "string[]" },
  },
  {
    id: "customer.retention_plan",
    domain: "customer",
    title: "Plan de retención",
    pattern: "planner_executor_reviewer",
    agents: ["support", "sales", "marketing"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { account: "string", risk: "string" },
    outputSchema: { plan: "string", owners: "string[]" },
  },
  {
    id: "customer.health",
    domain: "customer",
    title: "Análisis de customer health",
    pattern: "planner_executor_reviewer",
    agents: ["support", "reporting", "product"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { account: "string" },
    outputSchema: { score: "string", drivers: "string[]" },
  },
  {
    id: "finance.reconcile_sim",
    domain: "finance",
    title: "Conciliación simulada",
    pattern: "execute_validate_rollback",
    agents: ["finance", "reporting"],
    defaultMode: "observe",
    requiresHumanApproval: true,
    sloMs: 60_000,
    certified: true,
    inputSchema: { period: "string" },
    outputSchema: { deltas: "string[]", notes: "string" },
  },
  {
    id: "finance.forecast",
    domain: "finance",
    title: "Forecast",
    pattern: "planner_executor_reviewer",
    agents: ["finance", "sales", "reporting"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { horizon: "string" },
    outputSchema: { forecast: "string", assumptions: "string[]" },
  },
  {
    id: "finance.unit_economics",
    domain: "finance",
    title: "Unit economics",
    pattern: "proposer_critic_judge",
    agents: ["finance", "product", "reporting"],
    defaultMode: "draft",
    requiresHumanApproval: false,
    sloMs: 90_000,
    certified: true,
    inputSchema: { cohort: "string" },
    outputSchema: { metrics: "string", recommendations: "string[]" },
  },
  {
    id: "finance.report",
    domain: "finance",
    title: "Informe financiero",
    pattern: "planner_executor_reviewer",
    agents: ["finance", "ceo_supervisor"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 60_000,
    certified: true,
    inputSchema: { period: "string" },
    outputSchema: { report: "string", flags: "string[]" },
  },
  {
    id: "finance.anomaly",
    domain: "finance",
    title: "Anomaly detection",
    pattern: "detect_diagnose_remediate_verify",
    agents: ["finance", "security_compliance"],
    defaultMode: "observe",
    requiresHumanApproval: true,
    sloMs: 60_000,
    certified: true,
    inputSchema: { series: "string" },
    outputSchema: { anomalies: "string[]", actions: "string[]" },
  },
  {
    id: "ops.continuity",
    domain: "ops",
    title: "Continuidad de negocio",
    pattern: "planner_executor_reviewer",
    agents: ["operations", "devops", "security_compliance"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 90_000,
    certified: true,
    inputSchema: { scenario: "string" },
    outputSchema: { playbook: "string", gaps: "string[]" },
  },
  {
    id: "exec.integrated_report",
    domain: "executive",
    title: "Informe ejecutivo integrado",
    pattern: "supervisor_fanout",
    agents: ["ceo_supervisor", "cto", "marketing", "sales", "finance", "operations", "support"],
    defaultMode: "observe",
    requiresHumanApproval: false,
    sloMs: 120_000,
    certified: true,
    inputSchema: { period: "string" },
    outputSchema: { summary: "string", decisions: "string[]" },
  },
  {
    id: "exec.quarterly_plan",
    domain: "executive",
    title: "Planificación trimestral",
    pattern: "planner_executor_reviewer",
    agents: ["ceo_supervisor", "product", "cto", "marketing", "finance"],
    defaultMode: "draft",
    requiresHumanApproval: true,
    sloMs: 120_000,
    certified: true,
    inputSchema: { quarter: "string", objectives: "string[]" },
    outputSchema: { plan: "string", owners: "string[]", risks: "string[]" },
  },
];

export function listCertifiedWorkflows(): WorkforceWorkflowDef[] {
  return WORKFORCE_WORKFLOWS.filter((w) => w.certified);
}

export function getWorkforceWorkflow(id: string): WorkforceWorkflowDef | null {
  return WORKFORCE_WORKFLOWS.find((w) => w.id === id) ?? null;
}

export function workflowCatalogStatus() {
  const byDomain: Record<string, number> = {};
  for (const w of WORKFORCE_WORKFLOWS) {
    byDomain[w.domain] = (byDomain[w.domain] ?? 0) + 1;
  }
  return {
    total: WORKFORCE_WORKFLOWS.length,
    certified: WORKFORCE_WORKFLOWS.filter((w) => w.certified).length,
    byDomain,
  };
}
