/**
 * Full specialist agent catalog — design contracts for post-MCP implementation.
 * Complements existing nelvyonAgentRegistry (17) with complete enterprise set.
 */

export type AgentToolRef = string;

export type SpecialistAgentDesign = {
  id: string;
  name: string;
  department: string;
  responsibilities: string[];
  tools: AgentToolRef[];
  permissions: string[];
  memoryScopes: Array<"session" | "agent" | "tenant" | "shared_team">;
  contextSources: string[];
  limits: {
    maxTokens: number;
    maxRunsPerHour: number;
    canAutoExecute: boolean;
  };
  approvalRequired: string[];
  forbidden: string[];
  kpis: string[];
  testsPlanned: string[];
};

export const SPECIALIST_AGENT_DESIGNS: SpecialistAgentDesign[] = [
  {
    id: "ceo_supervisor",
    name: "CEO / Supervisor",
    department: "Direction",
    responsibilities: ["Priorizar iniciativas", "Sintetizar KPIs", "Escalar riesgos"],
    tools: ["memory.read", "reports.read", "audit.read", "rag.search"],
    permissions: ["agents.supervise"],
    memoryScopes: ["tenant", "shared_team"],
    contextSources: ["dashboard", "audit", "pack_reports"],
    limits: { maxTokens: 3000, maxRunsPerHour: 30, canAutoExecute: false },
    approvalRequired: ["touch_production", "modify_billing"],
    forbidden: ["delete_data", "send_mass_campaign", "cross_tenant_access"],
    kpis: ["decision_latency", "risk_flags_caught"],
    testsPlanned: ["no_sensitive_exec", "tenant_isolation"],
  },
  {
    id: "cto",
    name: "CTO",
    department: "Engineering",
    responsibilities: ["Arquitectura", "Deuda técnica", "Roadmap técnico"],
    tools: ["rag.search", "memory.read", "reports.read"],
    permissions: ["engineering.advise"],
    memoryScopes: ["agent", "tenant"],
    contextSources: ["docs", "ci_status"],
    limits: { maxTokens: 3000, maxRunsPerHour: 40, canAutoExecute: false },
    approvalRequired: ["deploy_production", "destructive_code"],
    forbidden: ["delete_data", "cross_tenant_access"],
    kpis: ["arch_review_coverage", "incident_advice_quality"],
    testsPlanned: ["no_deploy_without_approval"],
  },
  {
    id: "marketing",
    name: "Marketing",
    department: "Growth",
    responsibilities: ["Estrategia go-to-market", "Posicionamiento", "Calendario campañas"],
    tools: ["memory.read", "reports.read", "rag.search", "campaigns.draft"],
    permissions: ["marketing.plan"],
    memoryScopes: ["agent", "shared_team"],
    contextSources: ["ga4", "crm", "packs"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["send_mass_campaign", "publish_content"],
    forbidden: ["delete_data"],
    kpis: ["campaign_draft_quality", "time_to_brief"],
    testsPlanned: ["draft_only_default"],
  },
  {
    id: "seo",
    name: "SEO",
    department: "Growth",
    responsibilities: ["Auditoría on-page", "Keywords", "Technical SEO"],
    tools: ["reports.read", "rag.search", "memory.read"],
    permissions: ["seo.analyze"],
    memoryScopes: ["agent", "tenant"],
    contextSources: ["search_console", "site_crawl"],
    limits: { maxTokens: 2500, maxRunsPerHour: 80, canAutoExecute: false },
    approvalRequired: [],
    forbidden: ["delete_data", "touch_production"],
    kpis: ["audit_completeness", "keyword_coverage"],
    testsPlanned: ["no_rank_guarantees"],
  },
  {
    id: "sem_google_ads",
    name: "SEM / Google Ads",
    department: "Paid",
    responsibilities: ["Estructura campañas", "Keywords", "Optimización puja"],
    tools: ["reports.read", "memory.read"],
    permissions: ["ads.plan"],
    memoryScopes: ["agent"],
    contextSources: ["google_ads"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["touch_production"],
    forbidden: ["delete_data"],
    kpis: ["structure_quality", "budget_risk_flags"],
    testsPlanned: ["no_live_publish"],
  },
  {
    id: "meta_ads",
    name: "Meta Ads",
    department: "Paid",
    responsibilities: ["Audiencias", "Creatividades", "Testing"],
    tools: ["reports.read", "memory.read"],
    permissions: ["ads.plan"],
    memoryScopes: ["agent"],
    contextSources: ["meta_ads"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["touch_production"],
    forbidden: ["delete_data"],
    kpis: ["creative_variants", "audience_clarity"],
    testsPlanned: ["approval_for_launch"],
  },
  {
    id: "tiktok_ads",
    name: "TikTok Ads",
    department: "Paid",
    responsibilities: ["Hooks", "Creatividades cortas", "Targeting"],
    tools: ["reports.read", "memory.read"],
    permissions: ["ads.plan"],
    memoryScopes: ["agent"],
    contextSources: ["tiktok_ads"],
    limits: { maxTokens: 2000, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["touch_production"],
    forbidden: ["delete_data"],
    kpis: ["hook_diversity"],
    testsPlanned: ["draft_only"],
  },
  {
    id: "sales",
    name: "Ventas",
    department: "Revenue",
    responsibilities: ["Calificación", "Follow-ups", "Propuestas"],
    tools: ["crm.read", "crm.write", "memory.read", "reports.read"],
    permissions: ["crm.write"],
    memoryScopes: ["agent", "tenant"],
    contextSources: ["crm", "pipeline"],
    limits: { maxTokens: 2500, maxRunsPerHour: 100, canAutoExecute: false },
    approvalRequired: ["send_client_message"],
    forbidden: ["delete_data", "cross_tenant_access"],
    kpis: ["lead_score_accuracy", "followup_sla"],
    testsPlanned: ["no_mass_message"],
  },
  {
    id: "crm",
    name: "CRM Ops",
    department: "Revenue",
    responsibilities: ["Contactos", "Deals", "Higiene datos"],
    tools: ["crm.read", "crm.write", "memory.read", "workflows.read"],
    permissions: ["crm.write"],
    memoryScopes: ["tenant"],
    contextSources: ["crm"],
    limits: { maxTokens: 2000, maxRunsPerHour: 120, canAutoExecute: false },
    approvalRequired: ["delete_data"],
    forbidden: ["cross_tenant_access", "delete_data"],
    kpis: ["data_completeness"],
    testsPlanned: ["tenant_isolation"],
  },
  {
    id: "support",
    name: "Soporte",
    department: "Customer Success",
    responsibilities: ["Respuestas", "Escalado", "SLA"],
    tools: ["inbox.suggest", "memory.read", "rag.search"],
    permissions: ["inbox.suggest"],
    memoryScopes: ["session", "agent"],
    contextSources: ["inbox", "kb"],
    limits: { maxTokens: 2000, maxRunsPerHour: 200, canAutoExecute: false },
    approvalRequired: ["send_client_message"],
    forbidden: ["delete_data"],
    kpis: ["first_response_quality", "escalation_rate"],
    testsPlanned: ["tone_and_escalation"],
  },
  {
    id: "content",
    name: "Contenido / Copy",
    department: "Creative",
    responsibilities: ["Copy", "Briefs", "Calendario editorial"],
    tools: ["memory.read", "rag.search", "campaigns.draft"],
    permissions: ["content.draft"],
    memoryScopes: ["agent", "shared_team"],
    contextSources: ["brand", "packs"],
    limits: { maxTokens: 3000, maxRunsPerHour: 80, canAutoExecute: false },
    approvalRequired: ["publish_content"],
    forbidden: ["delete_data"],
    kpis: ["brand_consistency"],
    testsPlanned: ["no_auto_publish"],
  },
  {
    id: "social_media",
    name: "Redes Sociales",
    department: "Creative",
    responsibilities: ["Calendario social", "Captions", "Community guidelines"],
    tools: ["memory.read", "reports.read"],
    permissions: ["social.draft"],
    memoryScopes: ["agent"],
    contextSources: ["social"],
    limits: { maxTokens: 2000, maxRunsPerHour: 80, canAutoExecute: false },
    approvalRequired: ["publish_content"],
    forbidden: ["delete_data"],
    kpis: ["calendar_coverage"],
    testsPlanned: ["approval_publish"],
  },
  {
    id: "automation",
    name: "Automatizaciones",
    department: "Ops",
    responsibilities: ["Workflows", "Triggers", "Idempotencia"],
    tools: ["workflows.read", "workflows.write", "memory.read"],
    permissions: ["workflows.write"],
    memoryScopes: ["tenant"],
    contextSources: ["workflows"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["touch_production"],
    forbidden: ["delete_data"],
    kpis: ["workflow_idempotency"],
    testsPlanned: ["no_prod_without_approval"],
  },
  {
    id: "analytics",
    name: "Analítica",
    department: "Insights",
    responsibilities: ["KPIs", "Atribución", "Informes"],
    tools: ["reports.read", "memory.read", "rag.search"],
    permissions: ["reports.read"],
    memoryScopes: ["tenant", "shared_team"],
    contextSources: ["ga4", "crm", "billing"],
    limits: { maxTokens: 2500, maxRunsPerHour: 80, canAutoExecute: false },
    approvalRequired: [],
    forbidden: ["delete_data", "touch_production"],
    kpis: ["report_accuracy"],
    testsPlanned: ["read_only"],
  },
  {
    id: "devops",
    name: "DevOps",
    department: "Engineering",
    responsibilities: ["CI/CD advice", "Observabilidad", "Incident runbooks"],
    tools: ["memory.read", "rag.search", "reports.read"],
    permissions: ["ops.advise"],
    memoryScopes: ["agent"],
    contextSources: ["ci", "health"],
    limits: { maxTokens: 2500, maxRunsPerHour: 40, canAutoExecute: false },
    approvalRequired: ["deploy_production", "touch_production"],
    forbidden: ["delete_data", "docker_host_exec"],
    kpis: ["runbook_completeness"],
    testsPlanned: ["no_host_access"],
  },
  {
    id: "qa",
    name: "QA",
    department: "Engineering",
    responsibilities: ["Planes de prueba", "Regresiones", "Criterios aceptación"],
    tools: ["memory.read", "rag.search"],
    permissions: ["qa.plan"],
    memoryScopes: ["agent"],
    contextSources: ["tests", "docs"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: [],
    forbidden: ["touch_production", "delete_data"],
    kpis: ["coverage_advice"],
    testsPlanned: ["no_side_effects"],
  },
  {
    id: "security",
    name: "Seguridad",
    department: "Security",
    responsibilities: ["Threat review", "Policy", "Incident triage advice"],
    tools: ["audit.read", "memory.read", "rag.search"],
    permissions: ["security.review"],
    memoryScopes: ["agent", "tenant"],
    contextSources: ["audit", "security_gates"],
    limits: { maxTokens: 2500, maxRunsPerHour: 40, canAutoExecute: false },
    approvalRequired: ["modify_permissions", "rotate_credentials"],
    forbidden: ["cross_tenant_access", "delete_data"],
    kpis: ["policy_hits"],
    testsPlanned: ["no_secret_exfil"],
  },
  {
    id: "design",
    name: "Diseño",
    department: "Creative",
    responsibilities: ["Briefs visuales", "UI critique", "Brand tokens"],
    tools: ["memory.read", "rag.search"],
    permissions: ["design.advise"],
    memoryScopes: ["agent"],
    contextSources: ["brand"],
    limits: { maxTokens: 2000, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: [],
    forbidden: ["delete_data"],
    kpis: ["brief_clarity"],
    testsPlanned: ["brand_constraints"],
  },
  {
    id: "video",
    name: "Vídeo",
    department: "Creative",
    responsibilities: ["Guiones", "Storyboards", "Edits plan"],
    tools: ["memory.read"],
    permissions: ["media.plan"],
    memoryScopes: ["agent"],
    contextSources: ["media"],
    limits: { maxTokens: 2500, maxRunsPerHour: 40, canAutoExecute: false },
    approvalRequired: ["publish_content"],
    forbidden: ["delete_data"],
    kpis: ["script_structure"],
    testsPlanned: ["no_auto_publish"],
  },
  {
    id: "image",
    name: "Imagen",
    department: "Creative",
    responsibilities: ["Prompts creativos", "Asset briefs"],
    tools: ["memory.read"],
    permissions: ["media.plan"],
    memoryScopes: ["agent"],
    contextSources: ["media"],
    limits: { maxTokens: 2000, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["publish_content"],
    forbidden: ["delete_data"],
    kpis: ["asset_brief_quality"],
    testsPlanned: ["no_auto_publish"],
  },
  {
    id: "documentation",
    name: "Documentación",
    department: "Ops",
    responsibilities: ["HANDOVER", "Runbooks", "ADRs drafts"],
    tools: ["rag.search", "memory.read"],
    permissions: ["docs.draft"],
    memoryScopes: ["tenant", "shared_team"],
    contextSources: ["docs"],
    limits: { maxTokens: 3000, maxRunsPerHour: 40, canAutoExecute: false },
    approvalRequired: [],
    forbidden: ["delete_data", "touch_production"],
    kpis: ["doc_freshness_advice"],
    testsPlanned: ["read_docs_only"],
  },
  {
    id: "operations",
    name: "Operaciones",
    department: "Ops",
    responsibilities: ["SLA", "Runbooks ops", "Hand-offs"],
    tools: ["memory.read", "reports.read", "workflows.read"],
    permissions: ["ops.advise"],
    memoryScopes: ["tenant"],
    contextSources: ["health", "workflows"],
    limits: { maxTokens: 2500, maxRunsPerHour: 60, canAutoExecute: false },
    approvalRequired: ["touch_production"],
    forbidden: ["delete_data"],
    kpis: ["sla_advice"],
    testsPlanned: ["no_prod_mutate"],
  },
  {
    id: "finance",
    name: "Finanzas",
    department: "Finance",
    responsibilities: ["Resumen billing", "Alertas coste", "Forecast advice"],
    tools: ["reports.read", "memory.read"],
    permissions: ["billing.read"],
    memoryScopes: ["tenant"],
    contextSources: ["stripe", "billing"],
    limits: { maxTokens: 2500, maxRunsPerHour: 30, canAutoExecute: false },
    approvalRequired: ["modify_billing"],
    forbidden: ["delete_data", "modify_billing"],
    kpis: ["cost_anomaly_flags"],
    testsPlanned: ["read_only_billing"],
  },
];

export function listSpecialistAgentIds(): string[] {
  return SPECIALIST_AGENT_DESIGNS.map((a) => a.id);
}

export function getSpecialistAgentDesign(id: string): SpecialistAgentDesign | undefined {
  return SPECIALIST_AGENT_DESIGNS.find((a) => a.id === id);
}

export function assertAgentCatalogComplete(): { ok: boolean; count: number; violations: string[] } {
  const violations: string[] = [];
  if (SPECIALIST_AGENT_DESIGNS.length < 22) violations.push(`count_${SPECIALIST_AGENT_DESIGNS.length}`);
  const ids = new Set<string>();
  for (const a of SPECIALIST_AGENT_DESIGNS) {
    if (ids.has(a.id)) violations.push(`dup_${a.id}`);
    ids.add(a.id);
    if (!a.responsibilities.length) violations.push(`${a.id}_no_resp`);
    if (!a.kpis.length) violations.push(`${a.id}_no_kpi`);
    if (!a.testsPlanned.length) violations.push(`${a.id}_no_tests`);
  }
  return { ok: violations.length === 0, count: SPECIALIST_AGENT_DESIGNS.length, violations };
}
