import {
  MessageSquare, Mail, CalendarCheck, Share2, Phone,
  Target, BarChart3, Star, Brain, PenTool, Palette,
  DollarSign, Globe, Workflow, Users,
  type LucideIcon,
} from "lucide-react";

export type PlanTier = "starter" | "pro" | "enterprise";

export interface ClientAgent {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  icon: LucideIcon;
  color: string;
  gradient: string;
  borderColor: string;
  plan: PlanTier;
  category: string;
  capabilities: string[];
  metrics: { label: string; value: string }[];
  popular?: boolean;
}

export const CLIENT_AGENTS: ClientAgent[] = [
  // ── STARTER PLAN (3 agents) ──
  {
    id: "web-assistant",
    name: "ASISTENTE WEB",
    subtitle: "Chatbot Nelvyon 24/7",
    description: "Chatbot inteligente para tu web que responde FAQs, captura leads y guía visitantes hacia la conversión. Disponible 24/7 sin intervención humana.",
    icon: MessageSquare,
    color: "text-blue-400",
    gradient: "from-blue-500 to-cyan-500",
    borderColor: "border-blue-500/20",
    plan: "starter",
    category: "Atención al Cliente",
    capabilities: [
      "Respuestas automáticas a FAQs ilimitadas",
      "Captura de leads con formularios dinámicos",
      "Derivación inteligente a humano cuando necesario",
      "Widget personalizable con tu branding",
      "Análisis de conversaciones y sentimiento",
      "Integración con CRM automática",
      "Soporte multi-idioma (50+ idiomas)",
      "Disponible 24/7/365",
    ],
    metrics: [
      { label: "Tiempo respuesta", value: "<2s" },
      { label: "Resolución auto", value: "87%" },
      { label: "Leads capturados", value: "+340%" },
      { label: "Satisfacción", value: "94.2%" },
    ],
    popular: true,
  },
  {
    id: "email-bot",
    name: "EMAIL BOT",
    subtitle: "Automatización de Email Nelvyon",
    description: "Respuestas automáticas inteligentes a emails, seguimiento de leads, nurturing secuencial y campañas personalizadas con Nelvyon.",
    icon: Mail,
    color: "text-emerald-400",
    gradient: "from-emerald-500 to-green-500",
    borderColor: "border-emerald-500/20",
    plan: "starter",
    category: "Marketing",
    capabilities: [
      "Respuestas automáticas contextuales",
      "Secuencias de nurturing Nelvyon",
      "Personalización dinámica por contacto",
      "A/B testing automático de asuntos",
      "Detección de intención del email",
      "Follow-up inteligente programado",
      "Templates adaptativos por sector",
      "Analytics de apertura y conversión",
    ],
    metrics: [
      { label: "Tasa apertura", value: "68%" },
      { label: "Respuesta auto", value: "92%" },
      { label: "Conversión", value: "+45%" },
      { label: "Tiempo ahorrado", value: "15h/sem" },
    ],
  },
  {
    id: "booking-bot",
    name: "BOOKING BOT",
    subtitle: "Gestión de Citas Nelvyon",
    description: "Gestión completa de citas automática: programación, confirmaciones, recordatorios multicanal y optimización de agenda.",
    icon: CalendarCheck,
    color: "text-violet-400",
    gradient: "from-violet-500 to-purple-500",
    borderColor: "border-violet-500/20",
    plan: "starter",
    category: "Operaciones",
    capabilities: [
      "Reservas automáticas 24/7",
      "Confirmaciones por email, SMS y WhatsApp",
      "Recordatorios inteligentes multi-canal",
      "Sync con Google/Outlook/Apple Calendar",
      "Gestión de cancelaciones y reagendamiento",
      "Optimización de horarios por demanda",
      "Pagos al reservar integrados",
      "Reducción de no-shows al 3%",
    ],
    metrics: [
      { label: "No-shows", value: "3%" },
      { label: "Reservas auto", value: "96%" },
      { label: "Satisfacción", value: "97%" },
      { label: "Revenue +", value: "+28%" },
    ],
  },

  // ── PRO PLAN (5 additional agents) ──
  {
    id: "social-bot",
    name: "SOCIAL BOT",
    subtitle: "Social Media Nelvyon",
    description: "Gestión completa de redes sociales: respuestas automáticas, generación de contenido, programación de posts y análisis de engagement.",
    icon: Share2,
    color: "text-pink-400",
    gradient: "from-pink-500 to-rose-500",
    borderColor: "border-pink-500/20",
    plan: "pro",
    category: "Marketing",
    capabilities: [
      "Respuestas automáticas en todas las redes",
      "Generación de contenido con Nelvyon",
      "Programación inteligente por mejor horario",
      "Análisis de engagement en tiempo real",
      "Detección de menciones y sentimiento",
      "Hashtag optimization automático",
      "Generación de stories y reels copy",
      "Reportes semanales automáticos",
    ],
    metrics: [
      { label: "Engagement", value: "+180%" },
      { label: "Respuesta", value: "<5min" },
      { label: "Posts/mes", value: "120+" },
      { label: "Alcance", value: "+250%" },
    ],
    popular: true,
  },
  {
    id: "call-bot",
    name: "CALL BOT",
    subtitle: "Asistente Telefónico Nelvyon",
    description: "Asistente telefónico con Nelvyon que califica llamadas, transcribe conversaciones, programa callbacks y gestiona la cola de llamadas.",
    icon: Phone,
    color: "text-amber-400",
    gradient: "from-amber-500 to-orange-500",
    borderColor: "border-amber-500/20",
    plan: "pro",
    category: "Ventas",
    capabilities: [
      "Recepción automática de llamadas",
      "Calificación de leads por teléfono",
      "Transcripción automática con Nelvyon",
      "Resumen de llamada automático",
      "Derivación inteligente por departamento",
      "Programación de callbacks",
      "Análisis de sentimiento en voz",
      "Integración con CRM automática",
    ],
    metrics: [
      { label: "Llamadas gestionadas", value: "500+/día" },
      { label: "Calificación auto", value: "94%" },
      { label: "Tiempo espera", value: "<10s" },
      { label: "Satisfacción", value: "91%" },
    ],
  },
  {
    id: "sales-bot",
    name: "SALES BOT",
    subtitle: "Automatización de Ventas Nelvyon",
    description: "Seguimiento automático de oportunidades, generación de propuestas, gestión de pipeline y predicción de cierre con Nelvyon.",
    icon: Target,
    color: "text-red-400",
    gradient: "from-red-500 to-rose-600",
    borderColor: "border-red-500/20",
    plan: "pro",
    category: "Ventas",
    capabilities: [
      "Seguimiento automático de oportunidades",
      "Generación de propuestas comerciales",
      "Scoring de leads predictivo",
      "Pipeline management automático",
      "Alertas de deals en riesgo",
      "Predicción de cierre con Nelvyon",
      "Secuencias de follow-up personalizadas",
      "Reportes de ventas automáticos",
    ],
    metrics: [
      { label: "Cierre rate", value: "+35%" },
      { label: "Pipeline value", value: "+60%" },
      { label: "Follow-ups auto", value: "100%" },
      { label: "Deals perdidos", value: "-40%" },
    ],
  },
  {
    id: "analytics-bot",
    name: "ANALYTICS BOT",
    subtitle: "Inteligencia de Datos Nelvyon",
    description: "Reportes automáticos, alertas de KPIs, predicciones de tendencias y recomendaciones de negocio basadas en datos.",
    icon: BarChart3,
    color: "text-cyan-400",
    gradient: "from-cyan-500 to-blue-500",
    borderColor: "border-cyan-500/20",
    plan: "pro",
    category: "Analytics",
    capabilities: [
      "Reportes automáticos diarios/semanales",
      "Alertas inteligentes de KPIs",
      "Predicción de tendencias con ML",
      "Dashboards personalizados auto-generados",
      "Detección de anomalías en datos",
      "Recomendaciones de acción basadas en datos",
      "Benchmarking contra industria",
      "Exportación automática multi-formato",
    ],
    metrics: [
      { label: "Predicción", value: "94% acc" },
      { label: "Alertas/día", value: "12" },
      { label: "Tiempo análisis", value: "-80%" },
      { label: "Decisiones data", value: "+200%" },
    ],
  },
  {
    id: "review-bot",
    name: "REVIEW BOT",
    subtitle: "Gestión de Reputación Nelvyon",
    description: "Monitoreo y gestión automática de reseñas en todas las plataformas, respuestas inteligentes y análisis de reputación.",
    icon: Star,
    color: "text-yellow-400",
    gradient: "from-yellow-500 to-amber-500",
    borderColor: "border-yellow-500/20",
    plan: "pro",
    category: "Atención al Cliente",
    capabilities: [
      "Monitoreo de reseñas en 20+ plataformas",
      "Respuestas automáticas personalizadas",
      "Solicitud proactiva de reseñas",
      "Análisis de sentimiento en reseñas",
      "Alertas de reseñas negativas instantáneas",
      "Reportes de reputación automáticos",
      "Detección de reseñas falsas",
      "Mejora continua de rating",
    ],
    metrics: [
      { label: "Rating promedio", value: "4.8★" },
      { label: "Respuesta", value: "<1h" },
      { label: "Reseñas +", value: "+300%" },
      { label: "Negativas", value: "-60%" },
    ],
  },

  // ── ENTERPRISE PLAN (7 additional agents) ──
  {
    id: "strategy-bot",
    name: "STRATEGY BOT",
    subtitle: "Inteligencia Estratégica Nelvyon",
    description: "Análisis competitivo automático, recomendaciones de negocio, market intelligence y planificación estratégica con Nelvyon.",
    icon: Brain,
    color: "text-indigo-400",
    gradient: "from-indigo-500 to-blue-600",
    borderColor: "border-indigo-500/20",
    plan: "enterprise",
    category: "Estrategia",
    capabilities: [
      "Análisis competitivo automático",
      "Market intelligence en tiempo real",
      "Recomendaciones estratégicas con Nelvyon",
      "Detección de oportunidades de mercado",
      "Análisis SWOT automático",
      "Forecasting de mercado predictivo",
      "Benchmarking competitivo continuo",
      "Reportes ejecutivos automáticos",
    ],
    metrics: [
      { label: "Oportunidades", value: "+45/mes" },
      { label: "Precisión", value: "92%" },
      { label: "ROI decisiones", value: "+180%" },
      { label: "Tiempo análisis", value: "-90%" },
    ],
  },
  {
    id: "content-bot",
    name: "CONTENT BOT",
    subtitle: "Creación de Contenido Nelvyon",
    description: "Generación automática de blogs, landing pages, copy publicitario, SEO automático y content calendar inteligente.",
    icon: PenTool,
    color: "text-teal-400",
    gradient: "from-teal-500 to-emerald-500",
    borderColor: "border-teal-500/20",
    plan: "enterprise",
    category: "Marketing",
    capabilities: [
      "Generación de blogs SEO de 3000+ palabras",
      "Landing pages con copy optimizado",
      "Copy publicitario para todas las plataformas",
      "SEO automático con keywords research",
      "Content calendar inteligente",
      "Adaptación de tono por audiencia",
      "Generación de meta descriptions",
      "Plagiarism check integrado",
    ],
    metrics: [
      { label: "Artículos/mes", value: "60+" },
      { label: "SEO score", value: "95+" },
      { label: "Tráfico org.", value: "+400%" },
      { label: "Tiempo creación", value: "-85%" },
    ],
  },
  {
    id: "design-bot",
    name: "DESIGN BOT",
    subtitle: "Diseño Gráfico Nelvyon",
    description: "Generación automática de creatividades, banners, social media graphics, branding assets y presentaciones visuales.",
    icon: Palette,
    color: "text-fuchsia-400",
    gradient: "from-fuchsia-500 to-pink-500",
    borderColor: "border-fuchsia-500/20",
    plan: "enterprise",
    category: "Diseño",
    capabilities: [
      "Generación de banners y creatividades",
      "Social media graphics automáticos",
      "Adaptación de formatos por plataforma",
      "Branding consistency automático",
      "Presentaciones visuales con Nelvyon",
      "Thumbnails y covers automáticos",
      "Infografías generadas con datos",
      "A/B testing de creatividades",
    ],
    metrics: [
      { label: "Creatividades/día", value: "50+" },
      { label: "CTR mejora", value: "+65%" },
      { label: "Brand consistency", value: "99%" },
      { label: "Tiempo diseño", value: "-90%" },
    ],
  },
  {
    id: "finance-bot",
    name: "FINANCE BOT",
    subtitle: "Director Financiero Nelvyon",
    description: "Facturación automática, gestión de cobros, reportes financieros, forecasting de revenue y optimización de cash flow.",
    icon: DollarSign,
    color: "text-emerald-400",
    gradient: "from-emerald-600 to-green-600",
    borderColor: "border-emerald-500/20",
    plan: "enterprise",
    category: "Finanzas",
    capabilities: [
      "Facturación automática recurrente",
      "Gestión de cobros e impagos",
      "Reportes financieros automáticos",
      "Revenue forecasting con ML",
      "Optimización de cash flow",
      "Detección de fraude",
      "Multi-moneda automático",
      "Exportación contable compatible",
    ],
    metrics: [
      { label: "Cobro auto", value: "98%" },
      { label: "Impagos", value: "-70%" },
      { label: "Forecast acc.", value: "93%" },
      { label: "Cash flow +", value: "+40%" },
    ],
  },
  {
    id: "multilingual-bot",
    name: "MULTILINGUAL BOT",
    subtitle: "Traducción & Localización Nelvyon",
    description: "Traducción automática de todo el contenido, localización cultural, soporte multi-idioma y adaptación por mercado.",
    icon: Globe,
    color: "text-sky-400",
    gradient: "from-sky-500 to-blue-500",
    borderColor: "border-sky-500/20",
    plan: "enterprise",
    category: "Internacional",
    capabilities: [
      "Traducción automática en 100+ idiomas",
      "Localización cultural por mercado",
      "Adaptación de contenido por región",
      "Soporte multi-idioma en chatbot",
      "SEO multilingüe automático",
      "Detección de idioma automática",
      "Glosario personalizado por marca",
      "Quality assurance de traducciones",
    ],
    metrics: [
      { label: "Idiomas", value: "100+" },
      { label: "Precisión", value: "97%" },
      { label: "Mercados", value: "+15" },
      { label: "Revenue intl.", value: "+200%" },
    ],
  },
  {
    id: "workflow-bot",
    name: "WORKFLOW BOT",
    subtitle: "Automatización Avanzada Nelvyon",
    description: "Automatización de procesos complejos, integraciones custom, triggers avanzados y orquestación de workflows multi-paso.",
    icon: Workflow,
    color: "text-orange-400",
    gradient: "from-orange-500 to-red-500",
    borderColor: "border-orange-500/20",
    plan: "enterprise",
    category: "Operaciones",
    capabilities: [
      "Workflows multi-paso ilimitados",
      "Triggers condicionales avanzados",
      "Integraciones custom con API",
      "Orquestación de procesos complejos",
      "Branching y loops inteligentes",
      "Error handling automático",
      "Logs y auditoría completa",
      "Templates de workflows por industria",
    ],
    metrics: [
      { label: "Workflows activos", value: "200+" },
      { label: "Ejecuciones/día", value: "5K+" },
      { label: "Errores", value: "<0.1%" },
      { label: "Tiempo ahorrado", value: "40h/sem" },
    ],
  },
  {
    id: "hr-bot",
    name: "HR BOT",
    subtitle: "Gestión de Talento Nelvyon",
    description: "Gestión completa de equipo: onboarding automático, evaluaciones de desempeño, formación personalizada y gestión de talento.",
    icon: Users,
    color: "text-lime-400",
    gradient: "from-lime-500 to-green-500",
    borderColor: "border-lime-500/20",
    plan: "enterprise",
    category: "RRHH",
    capabilities: [
      "Onboarding automático de empleados",
      "Evaluaciones de desempeño con Nelvyon",
      "Planes de formación personalizados",
      "Gestión de vacaciones y ausencias",
      "Encuestas de clima laboral",
      "Detección de riesgo de rotación",
      "Knowledge base interno automático",
      "Reportes de RRHH automáticos",
    ],
    metrics: [
      { label: "Onboarding", value: "-60% tiempo" },
      { label: "Retención", value: "+25%" },
      { label: "Satisfacción", value: "92%" },
      { label: "Productividad", value: "+30%" },
    ],
  },
];

export const PLAN_AGENT_COUNTS: Record<PlanTier, number> = {
  starter: 3,
  pro: 8,
  enterprise: 15,
};

export const PLAN_LABELS: Record<PlanTier, string> = {
  starter: "Starter",
  pro: "Pro",
  enterprise: "Enterprise",
};

export const PLAN_COLORS: Record<PlanTier, string> = {
  starter: "from-blue-500 to-cyan-500",
  pro: "from-blue-600 to-violet-600",
  enterprise: "from-violet-600 to-purple-600",
};

export const CATEGORIES = [
  "Todos",
  "Atención al Cliente",
  "Marketing",
  "Ventas",
  "Operaciones",
  "Analytics",
  "Estrategia",
  "Diseño",
  "Finanzas",
  "Internacional",
  "RRHH",
];

export function getAgentsForPlan(plan: PlanTier): ClientAgent[] {
  const planHierarchy: PlanTier[] = ["starter", "pro", "enterprise"];
  const planIndex = planHierarchy.indexOf(plan);
  return CLIENT_AGENTS.filter((a) => {
    const agentPlanIndex = planHierarchy.indexOf(a.plan);
    return agentPlanIndex <= planIndex;
  });
}