import {
  Bot, MessageSquare, Phone, Mail, Calendar, Target,
  Users, BarChart3, Globe, Megaphone, CreditCard,
  FileText, Share2, Workflow, Headphones, Palette,
  ShoppingCart, Layers, BookOpen, Sparkles, Shield,
  Zap, Brain, Rocket, PenTool, Search,
  type LucideIcon,
} from "lucide-react";

export interface SaasAgent {
  id: string;
  name: string;
  role: string;
  description: string;
  icon: LucideIcon;
  color: string;
  gradient: string;
  category: "ventas" | "marketing" | "comunicacion" | "operaciones" | "contenido" | "analytics";
  configurable: string[];
  metrics: { label: string; value: string; color: string }[];
  capabilities: string[];
  useCases: string[];
  status: "active" | "configurable" | "premium";
}

export const saasAgentCategories = [
  { key: "ventas", label: "Ventas & CRM", icon: Target, color: "text-red-400" },
  { key: "marketing", label: "Marketing", icon: Megaphone, color: "text-violet-400" },
  { key: "comunicacion", label: "Comunicación", icon: MessageSquare, color: "text-blue-400" },
  { key: "operaciones", label: "Operaciones", icon: Workflow, color: "text-emerald-400" },
  { key: "contenido", label: "Contenido", icon: PenTool, color: "text-rose-400" },
  { key: "analytics", label: "Analytics", icon: BarChart3, color: "text-amber-400" },
];

export const saasAgents: SaasAgent[] = [
  {
    id: "lead-catcher",
    name: "Lead Catcher",
    role: "Captura y cualificación de leads",
    description: "Captura leads de todas tus fuentes (web, redes, ads, formularios) y los cualifica automáticamente según tu tipo de negocio. Configura los criterios de scoring para tu sector.",
    icon: Target,
    color: "#EF4444",
    gradient: "from-red-500 to-rose-600",
    category: "ventas",
    configurable: [
      "Criterios de scoring por sector",
      "Fuentes de captura (web, ads, social, referidos)",
      "Campos personalizados por tipo de negocio",
      "Reglas de asignación automática",
      "Notificaciones y alertas",
    ],
    metrics: [
      { label: "Leads/día", value: "150+", color: "text-red-400" },
      { label: "Scoring", value: "Auto", color: "text-emerald-400" },
      { label: "Conversión", value: "12.4%", color: "text-amber-400" },
      { label: "Respuesta", value: "<30s", color: "text-blue-400" },
    ],
    capabilities: [
      "Captura multi-fuente automática",
      "Lead scoring personalizable",
      "Asignación automática a vendedores",
      "Deduplicación inteligente",
      "Enriquecimiento de datos",
      "Integración con formularios y landing pages",
    ],
    useCases: [
      "Inmobiliarias: Captura leads de portales y web",
      "Clínicas: Formularios de cita + scoring",
      "E-commerce: Carritos abandonados",
      "Agencias: Leads de campañas multicanal",
    ],
    status: "active",
  },
  {
    id: "sales-bot",
    name: "Sales Bot",
    role: "Asistente de ventas conversacional",
    description: "Bot de ventas que atiende a tus prospects 24/7 por chat, WhatsApp y web. Responde preguntas, agenda citas y cualifica — adaptado a tu negocio y productos.",
    icon: Bot,
    color: "#EC4899",
    gradient: "from-pink-500 to-rose-600",
    category: "ventas",
    configurable: [
      "Personalidad y tono del bot",
      "Catálogo de productos/servicios",
      "Preguntas de cualificación",
      "Horarios de atención",
      "Respuestas por idioma",
      "Escalamiento a humano",
    ],
    metrics: [
      { label: "Chats/día", value: "500+", color: "text-pink-400" },
      { label: "Resolución", value: "87%", color: "text-emerald-400" },
      { label: "Citas agendadas", value: "45/día", color: "text-amber-400" },
      { label: "Satisfacción", value: "96%", color: "text-blue-400" },
    ],
    capabilities: [
      "Chat en vivo 24/7 multicanal",
      "WhatsApp Business integrado",
      "Agenda citas automáticamente",
      "Responde FAQs del negocio",
      "Cualifica leads en conversación",
      "Transferencia a humano inteligente",
    ],
    useCases: [
      "Restaurantes: Reservas y menú por WhatsApp",
      "Dentistas: Agendar citas y presupuestos",
      "Tiendas: Consultas de stock y precios",
      "Consultoras: Cualificación de prospects",
    ],
    status: "active",
  },
  {
    id: "caller-ai",
    name: "Caller AI",
    role: "Llamadas automáticas con voz natural",
    description: "Realiza y recibe llamadas con voz profesional humana. Confirma citas, hace seguimiento, cualifica por teléfono — configura el script para tu negocio.",
    icon: Phone,
    color: "#8B5CF6",
    gradient: "from-violet-500 to-purple-600",
    category: "ventas",
    configurable: [
      "Script de llamada personalizado",
      "Voz y tono (profesional, amigable, formal)",
      "Idioma de las llamadas",
      "Horarios de llamada",
      "Reglas de seguimiento",
      "Manejo de objeciones por sector",
    ],
    metrics: [
      { label: "Llamadas/día", value: "200+", color: "text-violet-400" },
      { label: "Contacto", value: "68%", color: "text-emerald-400" },
      { label: "Cierre", value: "23%", color: "text-amber-400" },
      { label: "Calidad", value: "4.8/5", color: "text-blue-400" },
    ],
    capabilities: [
      "Voz natural indistinguible de humano",
      "Scripts adaptativos en tiempo real",
      "Confirmación de citas automática",
      "Follow-up de leads calientes",
      "Manejo de objeciones",
      "Grabación y transcripción",
    ],
    useCases: [
      "Seguros: Llamadas de cotización",
      "Inmobiliarias: Confirmación de visitas",
      "Clínicas: Recordatorio de citas",
      "B2B: Prospección telefónica",
    ],
    status: "active",
  },
  {
    id: "email-engine",
    name: "Email Engine",
    role: "Email marketing automatizado",
    description: "Crea y envía campañas de email personalizadas. Secuencias automáticas, newsletters, follow-ups — todo adaptado a tu audiencia y sector.",
    icon: Mail,
    color: "#F59E0B",
    gradient: "from-amber-500 to-yellow-600",
    category: "marketing",
    configurable: [
      "Templates por tipo de negocio",
      "Secuencias de nurturing",
      "Segmentación de audiencia",
      "Horarios de envío óptimos",
      "Personalización por contacto",
      "A/B testing automático",
    ],
    metrics: [
      { label: "Emails/mes", value: "50K+", color: "text-amber-400" },
      { label: "Open rate", value: "42%", color: "text-emerald-400" },
      { label: "Click rate", value: "8.7%", color: "text-blue-400" },
      { label: "ROI", value: "4200%", color: "text-violet-400" },
    ],
    capabilities: [
      "Campañas masivas personalizadas",
      "Secuencias de nurturing automáticas",
      "A/B testing de asuntos y contenido",
      "Segmentación avanzada",
      "Templates responsive",
      "Analytics en tiempo real",
    ],
    useCases: [
      "E-commerce: Carritos abandonados + ofertas",
      "SaaS: Onboarding + retención",
      "Academias: Cursos y promociones",
      "Retail: Newsletters semanales",
    ],
    status: "active",
  },
  {
    id: "social-manager",
    name: "Social Manager",
    role: "Gestión de redes sociales",
    description: "Publica, programa y analiza contenido en todas tus redes. Genera posts adaptados a tu marca, sector y audiencia automáticamente.",
    icon: Share2,
    color: "#EC4899",
    gradient: "from-pink-500 to-fuchsia-600",
    category: "marketing",
    configurable: [
      "Redes sociales conectadas",
      "Tono y estilo de marca",
      "Calendario de publicación",
      "Hashtags por sector",
      "Tipos de contenido preferidos",
      "Respuestas automáticas a comentarios",
    ],
    metrics: [
      { label: "Posts/semana", value: "28+", color: "text-pink-400" },
      { label: "Engagement", value: "8.2%", color: "text-emerald-400" },
      { label: "Seguidores", value: "+2.4K/mes", color: "text-blue-400" },
      { label: "Alcance", value: "125K", color: "text-amber-400" },
    ],
    capabilities: [
      "Publicación multi-plataforma",
      "Generación de contenido por IA",
      "Programación inteligente",
      "Analytics de engagement",
      "Respuesta a comentarios",
      "Tendencias y hashtags",
    ],
    useCases: [
      "Restaurantes: Fotos de platos + stories",
      "Fitness: Rutinas + motivación diaria",
      "Moda: Lookbooks + reels",
      "B2B: LinkedIn thought leadership",
    ],
    status: "active",
  },
  {
    id: "ads-optimizer",
    name: "Ads Optimizer",
    role: "Optimización de campañas publicitarias",
    description: "Gestiona y optimiza tus campañas en Meta, Google, TikTok y LinkedIn. Ajusta pujas, audiencias y creativos automáticamente para maximizar ROI.",
    icon: Megaphone,
    color: "#06B6D4",
    gradient: "from-cyan-500 to-teal-600",
    category: "marketing",
    configurable: [
      "Plataformas de ads",
      "Presupuesto diario/mensual",
      "Audiencias objetivo",
      "Objetivos de campaña",
      "Creativos y copy",
      "Reglas de optimización",
    ],
    metrics: [
      { label: "ROAS", value: "4.8x", color: "text-cyan-400" },
      { label: "CPA", value: "-32%", color: "text-emerald-400" },
      { label: "Conversiones", value: "+45%", color: "text-amber-400" },
      { label: "Campañas", value: "24", color: "text-violet-400" },
    ],
    capabilities: [
      "Optimización de pujas automática",
      "A/B testing de creativos",
      "Audiencias lookalike",
      "Retargeting inteligente",
      "Reportes de rendimiento",
      "Alertas de presupuesto",
    ],
    useCases: [
      "E-commerce: Shopping Ads + retargeting",
      "Servicios locales: Google Local Ads",
      "Apps: Install campaigns",
      "B2B: LinkedIn Ads cualificados",
    ],
    status: "active",
  },
  {
    id: "chat-support",
    name: "Chat Support",
    role: "Soporte al cliente 24/7",
    description: "Atiende a tus clientes por chat, email y WhatsApp 24/7. Resuelve dudas, gestiona tickets y escala problemas — configurado con tu base de conocimiento.",
    icon: Headphones,
    color: "#3B82F6",
    gradient: "from-blue-500 to-indigo-600",
    category: "comunicacion",
    configurable: [
      "Base de conocimiento del negocio",
      "Canales de soporte activos",
      "Nivel de escalamiento",
      "Respuestas predefinidas",
      "Horarios de atención humana",
      "Idiomas de soporte",
    ],
    metrics: [
      { label: "Tickets/día", value: "200+", color: "text-blue-400" },
      { label: "Resolución", value: "94%", color: "text-emerald-400" },
      { label: "Respuesta", value: "<8s", color: "text-amber-400" },
      { label: "CSAT", value: "98%", color: "text-violet-400" },
    ],
    capabilities: [
      "Chat en vivo multicanal",
      "Resolución automática de FAQs",
      "Gestión de tickets",
      "Escalamiento inteligente",
      "Base de conocimiento auto-actualizada",
      "Detección de sentimiento",
    ],
    useCases: [
      "SaaS: Soporte técnico nivel 1-2",
      "E-commerce: Seguimiento de pedidos",
      "Servicios: Consultas y reservas",
      "Educación: Dudas de alumnos",
    ],
    status: "active",
  },
  {
    id: "whatsapp-bot",
    name: "WhatsApp Bot",
    role: "Automatización de WhatsApp Business",
    description: "Bot de WhatsApp que atiende clientes, envía catálogos, confirma pedidos y agenda citas. Configurado para tu negocio específico.",
    icon: MessageSquare,
    color: "#22C55E",
    gradient: "from-green-500 to-emerald-600",
    category: "comunicacion",
    configurable: [
      "Menú interactivo personalizado",
      "Catálogo de productos/servicios",
      "Flujos de conversación",
      "Mensajes de bienvenida",
      "Horarios de respuesta",
      "Plantillas de mensajes",
    ],
    metrics: [
      { label: "Mensajes/día", value: "1.2K+", color: "text-green-400" },
      { label: "Respuesta", value: "<5s", color: "text-emerald-400" },
      { label: "Conversión", value: "18%", color: "text-amber-400" },
      { label: "Retención", value: "92%", color: "text-blue-400" },
    ],
    capabilities: [
      "Respuestas automáticas 24/7",
      "Catálogo interactivo",
      "Confirmación de pedidos",
      "Agendamiento de citas",
      "Envío de promociones",
      "Encuestas de satisfacción",
    ],
    useCases: [
      "Restaurantes: Pedidos por WhatsApp",
      "Peluquerías: Reserva de citas",
      "Tiendas: Catálogo y precios",
      "Clínicas: Confirmación de turnos",
    ],
    status: "active",
  },
  {
    id: "appointment-scheduler",
    name: "Appointment Scheduler",
    role: "Gestión de citas y calendario",
    description: "Agenda, confirma y recuerda citas automáticamente. Sincroniza con Google Calendar, envía recordatorios por SMS/email/WhatsApp.",
    icon: Calendar,
    color: "#A855F7",
    gradient: "from-purple-500 to-violet-600",
    category: "operaciones",
    configurable: [
      "Tipos de cita/servicio",
      "Duración por servicio",
      "Disponibilidad del equipo",
      "Recordatorios (timing y canal)",
      "Política de cancelación",
      "Zona horaria",
    ],
    metrics: [
      { label: "Citas/día", value: "85+", color: "text-purple-400" },
      { label: "No-shows", value: "-78%", color: "text-emerald-400" },
      { label: "Confirmación", value: "96%", color: "text-blue-400" },
      { label: "Satisfacción", value: "99%", color: "text-amber-400" },
    ],
    capabilities: [
      "Agendamiento online 24/7",
      "Recordatorios multi-canal",
      "Sync con Google/Outlook Calendar",
      "Gestión de disponibilidad",
      "Reagendamiento automático",
      "Pagos anticipados",
    ],
    useCases: [
      "Dentistas: Citas con recordatorio SMS",
      "Abogados: Consultas con pago previo",
      "Salones: Reservas online",
      "Consultores: Demos y reuniones",
    ],
    status: "active",
  },
  {
    id: "workflow-builder",
    name: "Workflow Builder",
    role: "Automatización de procesos",
    description: "Crea flujos de trabajo automatizados sin código. Conecta acciones entre servicios: cuando pasa X, haz Y automáticamente.",
    icon: Workflow,
    color: "#0EA5E9",
    gradient: "from-sky-500 to-blue-600",
    category: "operaciones",
    configurable: [
      "Triggers personalizados",
      "Acciones por servicio",
      "Condiciones y filtros",
      "Delays y esperas",
      "Notificaciones",
      "Integraciones externas",
    ],
    metrics: [
      { label: "Workflows", value: "50+", color: "text-sky-400" },
      { label: "Ejecuciones/día", value: "2.4K", color: "text-emerald-400" },
      { label: "Ahorro", value: "20h/sem", color: "text-amber-400" },
      { label: "Éxito", value: "99.8%", color: "text-violet-400" },
    ],
    capabilities: [
      "Builder visual drag & drop",
      "Triggers multi-evento",
      "Acciones condicionales",
      "Integraciones con 200+ apps",
      "Logs y debugging",
      "Templates por sector",
    ],
    useCases: [
      "Lead → Email → SMS → Llamada automática",
      "Compra → Factura → Envío → Follow-up",
      "Cita agendada → Recordatorio → Feedback",
      "Ticket → Asignación → Resolución → Encuesta",
    ],
    status: "active",
  },
  {
    id: "invoice-bot",
    name: "Invoice Bot",
    role: "Facturación y cobros automáticos",
    description: "Genera facturas, envía recordatorios de pago, gestiona suscripciones y cobra automáticamente. Configurado con tus datos fiscales.",
    icon: CreditCard,
    color: "#10B981",
    gradient: "from-emerald-500 to-green-600",
    category: "operaciones",
    configurable: [
      "Datos fiscales de la empresa",
      "Plantilla de factura",
      "Métodos de pago aceptados",
      "Recordatorios de cobro",
      "Impuestos por región",
      "Moneda y formato",
    ],
    metrics: [
      { label: "Facturas/mes", value: "500+", color: "text-emerald-400" },
      { label: "Cobro auto", value: "94%", color: "text-blue-400" },
      { label: "Morosidad", value: "-65%", color: "text-amber-400" },
      { label: "Precisión", value: "99.9%", color: "text-violet-400" },
    ],
    capabilities: [
      "Facturación automática recurrente",
      "Recordatorios de pago escalonados",
      "Múltiples métodos de pago",
      "Gestión de suscripciones",
      "Reportes financieros",
      "Compliance fiscal multi-país",
    ],
    useCases: [
      "SaaS: Suscripciones mensuales",
      "Freelancers: Facturas por proyecto",
      "Agencias: Facturación a clientes",
      "Consultorios: Cobro de servicios",
    ],
    status: "active",
  },
  {
    id: "content-writer",
    name: "Content Writer",
    role: "Generación de contenido",
    description: "Escribe blogs, posts, emails, copy y cualquier contenido adaptado a tu marca, tono y sector. SEO optimizado automáticamente.",
    icon: PenTool,
    color: "#F43F5E",
    gradient: "from-rose-500 to-red-600",
    category: "contenido",
    configurable: [
      "Tono de marca (formal, casual, técnico)",
      "Sector y audiencia objetivo",
      "Keywords SEO principales",
      "Formato preferido",
      "Idiomas de contenido",
      "Calendario editorial",
    ],
    metrics: [
      { label: "Piezas/día", value: "25+", color: "text-rose-400" },
      { label: "SEO Score", value: "96/100", color: "text-emerald-400" },
      { label: "Engagement", value: "+180%", color: "text-amber-400" },
      { label: "Idiomas", value: "12+", color: "text-blue-400" },
    ],
    capabilities: [
      "Blog posts SEO-optimizados",
      "Copy para landing pages",
      "Posts para redes sociales",
      "Emails de marketing",
      "Descripciones de productos",
      "Whitepapers y case studies",
    ],
    useCases: [
      "E-commerce: Descripciones de productos",
      "SaaS: Blog técnico + case studies",
      "Restaurantes: Menús y promociones",
      "Inmobiliarias: Descripciones de propiedades",
    ],
    status: "active",
  },
  {
    id: "seo-agent",
    name: "SEO Agent",
    role: "Optimización para buscadores",
    description: "Analiza y optimiza tu SEO automáticamente. Keywords, meta tags, contenido, backlinks, velocidad — todo para posicionarte #1 en Google.",
    icon: Search,
    color: "#F97316",
    gradient: "from-orange-500 to-amber-600",
    category: "contenido",
    configurable: [
      "Keywords objetivo",
      "Competidores a monitorear",
      "Páginas prioritarias",
      "Frecuencia de auditoría",
      "Idioma y región objetivo",
      "Reportes automáticos",
    ],
    metrics: [
      { label: "Keywords #1", value: "47", color: "text-orange-400" },
      { label: "Tráfico orgánico", value: "+340%", color: "text-emerald-400" },
      { label: "Domain Authority", value: "72", color: "text-blue-400" },
      { label: "Auditorías/sem", value: "7", color: "text-violet-400" },
    ],
    capabilities: [
      "Auditoría SEO completa",
      "Keyword research automático",
      "Optimización on-page",
      "Monitoreo de posiciones",
      "Análisis de competencia",
      "Reportes de rendimiento",
    ],
    useCases: [
      "Cualquier negocio con web",
      "E-commerce: SEO de productos",
      "Servicios locales: SEO local",
      "SaaS: SEO técnico + contenido",
    ],
    status: "active",
  },
  {
    id: "funnel-builder",
    name: "Funnel Builder",
    role: "Constructor de embudos de venta",
    description: "Crea embudos de venta completos: landing page → captura → nurturing → venta. Templates por sector con conversión probada.",
    icon: Layers,
    color: "#14B8A6",
    gradient: "from-teal-500 to-cyan-600",
    category: "ventas",
    configurable: [
      "Tipo de embudo (webinar, producto, servicio)",
      "Páginas del funnel",
      "Ofertas y precios",
      "Secuencia de emails",
      "Upsells y downsells",
      "Tracking y analytics",
    ],
    metrics: [
      { label: "Funnels activos", value: "12", color: "text-teal-400" },
      { label: "Conversión", value: "8.4%", color: "text-emerald-400" },
      { label: "Revenue", value: "€24K/mes", color: "text-amber-400" },
      { label: "A/B tests", value: "Auto", color: "text-blue-400" },
    ],
    capabilities: [
      "Builder visual de funnels",
      "Templates de alta conversión",
      "A/B testing automático",
      "Integración con pagos",
      "Email sequences incluidas",
      "Analytics de embudo",
    ],
    useCases: [
      "Coaches: Webinar funnel",
      "E-commerce: Product launch funnel",
      "Agencias: Lead generation funnel",
      "SaaS: Free trial funnel",
    ],
    status: "active",
  },
  {
    id: "analytics-pro",
    name: "Analytics Pro",
    role: "Análisis y reportes inteligentes",
    description: "Dashboard de métricas en tiempo real. Reportes automáticos, predicciones, alertas — todo adaptado a los KPIs de tu negocio.",
    icon: BarChart3,
    color: "#6366F1",
    gradient: "from-indigo-500 to-violet-600",
    category: "analytics",
    configurable: [
      "KPIs principales del negocio",
      "Frecuencia de reportes",
      "Alertas personalizadas",
      "Comparativas (vs mes anterior, vs competencia)",
      "Dashboards por departamento",
      "Exportación de datos",
    ],
    metrics: [
      { label: "Métricas", value: "200+", color: "text-indigo-400" },
      { label: "Reportes/sem", value: "7", color: "text-emerald-400" },
      { label: "Predicción", value: "94%", color: "text-amber-400" },
      { label: "Real-time", value: "Sí", color: "text-blue-400" },
    ],
    capabilities: [
      "Dashboards en tiempo real",
      "Reportes automáticos",
      "Predicciones inteligentes",
      "Alertas inteligentes",
      "Segmentación de datos",
      "Exportación multi-formato",
    ],
    useCases: [
      "Cualquier negocio: KPIs principales",
      "E-commerce: Revenue + conversión",
      "SaaS: MRR + churn + LTV",
      "Agencias: ROI por cliente",
    ],
    status: "active",
  },
  {
    id: "review-manager",
    name: "Review Manager",
    role: "Gestión de reseñas y reputación",
    description: "Solicita reseñas automáticamente, responde reviews en Google/TripAdvisor/Yelp, monitorea tu reputación online — todo en piloto automático.",
    icon: Sparkles,
    color: "#FACC15",
    gradient: "from-yellow-400 to-amber-500",
    category: "marketing",
    configurable: [
      "Plataformas de reseñas",
      "Timing de solicitud de review",
      "Plantillas de respuesta",
      "Alertas de reviews negativas",
      "Incentivos por reseña",
      "Reportes de reputación",
    ],
    metrics: [
      { label: "Reviews/mes", value: "85+", color: "text-yellow-400" },
      { label: "Rating medio", value: "4.8★", color: "text-emerald-400" },
      { label: "Respuesta", value: "100%", color: "text-blue-400" },
      { label: "Reputación", value: "A+", color: "text-violet-400" },
    ],
    capabilities: [
      "Solicitud automática de reviews",
      "Respuesta automática a reseñas",
      "Monitoreo multi-plataforma",
      "Alertas de reviews negativas",
      "Dashboard de reputación",
      "Análisis de sentimiento",
    ],
    useCases: [
      "Restaurantes: Google + TripAdvisor",
      "Hoteles: Booking + TripAdvisor",
      "Clínicas: Google + Doctoralia",
      "E-commerce: Reviews de productos",
    ],
    status: "active",
  },
];